### ISSUE TITLE
Unlayer doesn't work on development domains

### ISSUE THREAD

**Issue by LorenzoSapora** [spatie/mailcoach-support#100]
When Unlayer is selected as the editor, and I use a .test domain, it hangs.

![image](https://user-images.githubusercontent.com/25519274/76515542-a74a1480-6451-11ea-811d-fe37fd93bc31.png)

Console error
![image](https://user-images.githubusercontent.com/25519274/76515653-d9f40d00-6451-11ea-91c1-6abf518a8d05.png)

**Comment by riasvdv** [comment]
I'm not seeing the issue on a `.test` domain, some debugging questions:
- Which browser are you using?
- Is there a specific domain you're using?
- Do you have any ad blocking / tracking blocking extensions?

**Comment by LorenzoSapora** [comment]
Heh, I usually include those, sorry, brain not working today.

- Browser: Firefox (latest), Ubuntu 19.10
- `https://mc.test` (self signed cert)
- Laravel: 7.1.0
- Fresh install from `composer create-project spatie/Mailcoach sandbox/mailcoach`
- Adblocking yes, but not in incognito mode, which this is viewed in.
- No blocks on my pihole

**Comment by LorenzoSapora** [comment]
Tested on multiple browsers (fresh, no extensions chromium), still repeatable :thinking:

**Comment by riasvdv** [comment]
So I've tracked down the error, and it seems `document.referrer` is empty, can you verify that by trying to output it in the console?

**Comment by riasvdv** [comment]
![image](https://user-images.githubusercontent.com/3626559/76520874-087ae380-6464-11ea-937a-025d831d5245.png)

If in `about:config` I set `network.http.sendRefererHeader` to `0` (it's set to `2` here by default), Firefox will stop sending referers, and I get the same error.

Can you make sure your browser sends the referer?

**Comment by LorenzoSapora** [comment]
Still persists. No effect before or after restarting browser. Mine was indeed set to 2, and is now set to 0.

**Comment by riasvdv** [comment]
You should keep it at 2 then, can you try something else for me?

Open the `views/app.blade.php` and add `<meta name="referrer" content="always">` to the `<head>` in there, and see if it helps

**Comment by LorenzoSapora** [comment]
That works, but not for `views/app.blade.php`. I had to publish the mailcoach views, then change `resources/views/vendor/mailcoach/app/layouts/app.blade.php`

**Comment by riasvdv** [comment]
Okay, I've tagged a new version (2.0.2) that adds this, should be available in a few minutes, thanks for helping us debug!
