### ISSUE TITLE
[FEATURE REQUEST] Send a campaign to multiple lists

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/mailcoach-support#102]
Would it be possible to implement the feature to have the campaign be sent to multiple email lists? Currently, we have to duplicate each campaign and attach a separate email list and this creates multiple campaigns and aggregating the stats for them is kind of difficult. 

Here is a scenario that we have that we would like this option
 
We have multiple email list for 
- Class signups
- Subscription signups
- Video Class signup

When we have to announce our summer camps that include about 10 events and if we have to drive a sequence-based email, we have to create 10 campaigns for each email list times each sequence email. 

I am hoping that makes sense.

**Comment by freekmurze** [comment]
Currently, this is not possible. What you could do is setting up only one list, and use tags and segments to create the target audience you want to send a campaign to.
