### ISSUE TITLE
[FEATURE REQUEST] Add feature for Email Sequences

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/mailcoach-support#103]
Would it be possible to add a feature to create Email Sequences? 

- When creating an email sequence, they will be attached to a single email list 
- Each email sequence will have multiple email templates. 
- Each template will be configured to be sent to the email list subscribers on a specific day from the date when they sign up to the email list.

**Comment by connecteev** [comment]
I assume by email sequences you mean drip campaigns. Really, really want this feature too. I hope this gets built.

**Comment by freekmurze** [comment]
We discussed this with our team, and we're currently thinking about it. Closing this for now, but know that we're seriously considering it.
