### ISSUE TITLE
Unlayer Editor converting png to jpeg

### ISSUE THREAD

**Issue by smorris1709** [spatie/mailcoach-support#104]
Not sure if this is an issue or a config I need to change.

but when I'm uploading images with the unlayer image uploader its converting my transparent background png file to a jpeg which is then not transparent anymore, is there some sort of configuration I can look at to change this default behaviour?

**Comment by riasvdv** [comment]
I've fixed this in the Unlayer package 1.0.1, this should be fixed after running `composer update`
