### ISSUE TITLE
Add ability to create segments of untagged contacts

### ISSUE THREAD

**Issue by simonhamp** [spatie/mailcoach-support#105]
Segments are currently only really useful when using tags. It's currently not possible to build a segment that represents all of the contacts that have _no_ tags.

My solution for this is the following:

#### Add a new column to `mailcoach_segments`

Something like `no_tags_required`. (I haven't spent much time thinking up the name.)

#### Edit `src/Models/TagSegment.php`

Add a reference to the new `no_tags_required` field and an associated scope-modifying method to the model:

```php
    public $casts = [
        'all_positive_tags_required' => 'boolean',
        'all_negative_tags_required' => 'boolean',
        'no_tags_required' => 'boolean',
    ];

...

    public function scopeOnTags(Builder $subscribersQuery): void
    {
        $this->buildPositiveTagsQuery($subscribersQuery);

        $this->buildNegativeTagsQuery($subscribersQuery);

        $this->buildNoTagsQuery($subscribersQuery);
    }

...

    protected function buildNoTagsQuery(Builder $subscribersQuery)
    {
        if (! $this->no_tags_required) {
            return;
        }

        $subscribersQuery->whereDoesntHave('tags');
    }
```

#### Edit `resources/views/app/emailLists/segment/edit.blade.php`

Add a checkbox field that will allow for changing the value stored in the new column:

```php
<x-checkbox-field label="Select only subscribers with no tags" name="no_tags_required" :checked="$segment->no_tags_required" />
```

#### Edit `src/Http/App/Controllers/EmailLists/Segments/EditSegmentController.php`

Store the new field value in the new column:

```php
    public function update(EmailList $emailList, TagSegment $segment, UpdateSegmentRequest $request)
    {
        $segment->update([
            'name' => $request->name,
            'all_positive_tags_required' => $request->allPositiveTagsRequired(),
            'all_negative_tags_required' => $request->allNegativeTagsRequired(),
            'no_tags_required' => $request->no_tags_required,
        ]);

...

    }
```

#### Edit `src/Http/App/Requests/UpdateSegmentRequest.php`

Add a validation rule for the new field, for completeness:

```php
    public function rules(): array
    {
        return [
            'name' => 'required',
            'positive_tags_operator' => [Rule::in(['any', 'all'])],
            'positive_tags.*' => [Rule::in($this->emailListTagNames())],
            'negative_tags_operator' => [Rule::in(['any', 'all'])],
            'negative_tags.*' => [Rule::in($this->emailListTagNames())],
            'no_tags_required' => 'boolean',
        ];
    }
```

**Comment by freekmurze** [comment]
I like the idea, but changing something on the migrations is a breaking change.

I'll revisit this when creating a new major version of the package.

**Comment by simonhamp** [comment]
Interesting. I only saw it as additive. How does a migration break backwards compatibility?

**Comment by freekmurze** [comment]
People that already have the package installed do not have that extra db field. If that db field is used in the code it breaks their apps.

**Comment by raulp** [comment]
@freekmurze i kind of like the idea of making segments a bit more flexible as well. 
I can see other cases too, like:

1. users with no tags
2. segment based on custom attributes
3. any other query based segment

From the docs, i can see i can create my own segment based on a query or the subscription itself, so i guess we could make a table where we can store all these segments? And maybe make a migration script on the upgrade where we migrate the current ones to this new table and the interface can show from there (just thinking out loud).

The reality is that i'm already preparing my backend to use mailcoach as a package, and i will do all my extra work from there. But i would love to be able to save them and maybe even display them in a dropdown somehow. Maybe they all can implement an interface where a name and description is required, so in the interface they can tell what that segment will do to their query.
