### ISSUE TITLE
[Feature Request] Upload media

### ISSUE THREAD

**Issue by dimzeta** [spatie/mailcoach-support#106]
Hello,

Would it be possible to upload medias (images, video, docs...) and integrate them in email (by link and/or by attachment)?
Currently we only can upload images though Unlayer editor, but I'm using Monaco. I'd really appreciate if we could have a "media" section in my campaign, where we can upload any files. Once uploaded, we could get the public link and doing whatever i want with, or directly attach it to the mail.

FYI I have installed mailcoach as a standalone application.

Thank you for mailcoach, i ❤️ it!

**Comment by freekmurze** [comment]
Currently we have no plans to add this, but I'll consider this for a future major version.

Technically, you could already create a screen yourself that allows you to upload a file and display a URL to that file. Granted, it would be nice if the package would do this out of the box.
