### ISSUE TITLE
[Feature Request] add more data to subscribers

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#107]
It would be very helpful for building the segments if it's possibile to extend the subscribers data. Especially for using mailcoach in shops adding more data to subscribers like city, address, ecommerce data and so one would be very nice / necessary

**Comment by satoved** [comment]
I think you already can do it by importing CSV file with additional field. They'll be stored under mailcoach_subscribers.extra_attributes

I guess, additional logic on how to use them is up to you.

**Comment by freekmurze** [comment]
Thanks for answering this one @satoved

**Comment by satoved** [comment]
It also turned out you can then use ::subscriber.extra_attributes.city:: in the template.
