### ISSUE TITLE
Text Version shows markdown

### ISSUE THREAD

**Issue by AlexisSerneels** [spatie/mailcoach-support#108]
The text version is a simple markdown conversion of the HTML.

Which means it shows links and images like `![Alt Text](https://longURL.com "Alt text") `
The plain version should remove images and links reference IMO. Just its content.

Cheers,

**Comment by AlexisSerneels** [comment]
The plain version is also often used for iOS notification content. A email using an image header has the markdown image code shown as first text in the notification...

**Comment by freekmurze** [comment]
I'll consider changing this behaviour in a future version. 

Right now, you can change the default implementation for this by specific an action of your own in the `actions.convert_html_to_text` key in of the `mailcoach.php` config file.
