### ISSUE TITLE
Cannot import subscribers

### ISSUE THREAD

**Issue by satoved** [spatie/mailcoach-support#109]
I'm trying to import subscribers from a CSV file.

Default disk for media is s3.

The job fails with message:
Box\Spout\Common\Exception\IOException: Could not open 725/list1.csv for reading! File does not exist. in /home/forge/annuitiesgenius.com/vendor/box/spout/src/Spout/Reader/ReaderAbstract.php:118

![image](https://user-images.githubusercontent.com/14319239/76886368-6145e400-6889-11ea-9cf9-40389d51dcb1.png)

Seems like the returned path for the file is not full.

![image](https://user-images.githubusercontent.com/14319239/76885965-c220ec80-6888-11ea-863e-d9a3328da29f.png)

Laravel: 7.1.1
MediaLibrary: 8.0.1
Mailcoach: 2.0.2

**Comment by satoved** [comment]
Can file path be used with s3 at all?

I also cannot change the disk for this SubscriberImport model:

![image](https://user-images.githubusercontent.com/14319239/76886692-d31e2d80-6889-11ea-937a-702b79d0e7f5.png)

**Comment by satoved** [comment]
Is there an option like the one for Unlayer, but for inner mailcoach uploads?

```
'unlayer' => [
    'disk_name' => env('MAILCOACH_UPLOAD_DISK', 'public'),
]
```

**Comment by freekmurze** [comment]
Importing from S3 is not supported.  How did you start the import? Did you use the UI we provided?

> inner mailcoach uploads
I don't know what you mean with that.

**Comment by satoved** [comment]
Yes, I used the UI.

Here's my config/media-library.php

![image](https://user-images.githubusercontent.com/14319239/76903995-bb55a200-68a7-11ea-93c4-1e5ae3cb1d7b.png)

S3 is the default filesystem.

And as far as I can see, the media of SubscriberImport will be loaded to the default filesystem with no option to change it.

P.S. I'm using Mailcoach as a package in a project.

**Comment by satoved** [comment]
@freekmurze do I need to provide more details?

Currently as a workaround I find Media record for SubscriberImport (importFile collection) in database, change `disk` to 'local', and then upload the file manually to storage/app where it should be.

Then I rerun failed job, and it's going ok.

Maybe something like this on SubscriberImport can solve the problem:

![image](https://user-images.githubusercontent.com/14319239/77108774-7fe3e080-6a2b-11ea-8c90-a73bb5b31ce4.png)

**Comment by satoved** [comment]
Another issue is that all jobs except ImportSubscribersJob has $queue set in __construct() of the job class. ImportSubscribersJob goes to the 'default' queue.

**Comment by freekmurze** [comment]
In the latest release I've added a config option `import_subscribers_disk` which can be used to set the disk used for importing subscribers. You can view the latest version of the config file on this page: https://mailcoach.app/docs/v2/package/general/installation-and-setup

Also, in the latest version, the queue for the `ImportSubscribersJob` can be set in the config file.

Let me know if these options fix your issue.

**Comment by freekmurze** [comment]
Closing this as using a local disk will probably solve this.
