### ISSUE TITLE
webhook_calls table

### ISSUE THREAD

**Issue by arthurkirkosa** [spatie/mailcoach-support#110]
Do we need old entries in the table? Can we delete them?

**Comment by freekmurze** [comment]
Yes, you can delete old rows there.

**Comment by arthurkirkosa** [comment]
Is there a plan to add this as a console command in the package?

**Comment by freekmurze** [comment]
I'll look into this soon.

**Comment by freekmurze** [comment]
Will be handled by @AlexVanderbist who is solving performance issues atm.
