### ISSUE TITLE
InvalidArgumentException ConfirmSubscriberController not defined when routes are cached

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#114]
Laravel: 7.2.2
Mailcoach: 2.0.4

![Captura de Pantalla 2020-03-22 a la(s) 3 43 05 p  m](https://user-images.githubusercontent.com/6526545/77260191-80ab8b00-6c54-11ea-872a-333c4edccea4.png)

Hi there,

If `php artisan route:cache` is used the `InvalidArgumentException` is generated.

If you run `php artisan route:clear` it does not generate any error.

**Comment by riasvdv** [comment]
This should be fixed in laravel-mailcoach 2.1.1
