### ISSUE TITLE
SendMailJobs all failed, still received campaign confirmation

### ISSUE THREAD

**Issue by shatterproof** [spatie/mailcoach-support#117]
**PHP:** 7.4.3
**Laravel:** 7.2.2
**Mailcoach:** 2.0.4

Tried to send a scheduled email campaign that initially appeared successful (even received the campaign email confirmation it was sent), but all the SendMailJobs failed several times which caused none of the emails to actually be sent out. My last campaign went out March 19 with no issue, so I'm not sure what could have changed since then besides the Mailcoach 2.0.4 upgrade.

The failed jobs in Horizon were showing one of two different exceptions:
`Undefined offset: 1 in /home/forge/site/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php:107`
`Undefined offset: 2 in /home/forge/site/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php:109`

I was able to resolve this by upgrading to the latest version of Mailcoach (2.1.1) and then retrying the jobs manually in Horizon to send them out. However, I am concerned that I received the campaign success email despite all of the jobs failing.

If I hadn't checked Horizon I might not have known the campaign emails were never actually sent out. Could the campaign success email be adjusted to alert if there was an issue sending the campaign?

**Comment by freekmurze** [comment]
Thanks for reporting.

In the outbox of a sent campaign, you would have seen the failed mails and also a button dispatch jobs to send them.

But indeed, the confirmation mail (and the campaign index screen) should have a warning when there were emails didn't get send correctly.

**Comment by freekmurze** [comment]
We'll take care of this next week.

**Comment by shatterproof** [comment]
Awesome, love the package and all the great work you guys do. Thank you!

**Comment by freekmurze** [comment]
This has been fixed by @riasvdv in the newly tagged `v2.4.3`
