### ISSUE TITLE
Configured outgoing webhooks in standalone

### ISSUE THREAD

**Issue by leeovery** [spatie/mailcoach-support#12]
Hey

I’m trying to think of the best way I can use this without polluting my main app (I’m not against the idea yet. Just playing with options). 

If the standalone app had **configurable outgoing webhooks** it would be awesome. 

These webhooks would relate directly to the events which are already dispatched in mailcoach and would ping the registered url(s) (if any configured). Would essentially allow external apps to respond to the events. :)

So rather than reacting to Mailcoach events in my main app (with mailcoach installed as a package) I would setup mc standalone and then register webhooks to do stuff when those events fire in my main app. 

Cheers
Lee

Ps. The other big one would be a simple api for doing things in the standalone install. But I know this has been raised already. :)

**Comment by freekmurze** [comment]
It's an interesting idea for sure.

Some people have indeed asked for an API. I'll consider adding it in the future. 

For now, you could add it yourself to the standalone app.

**Comment by leeovery** [comment]
Does the standalone install mailcoach as a package inside a fresh Laravel install? Or is the Laravel app just a custom mailcoach install with auth etc. 

Just thinking how easy future updates would be if I did it myself.

**Comment by freekmurze** [comment]
The standalone app is a fresh Laravel app, where we added auth screens and already preconfigured the Mailcoach package.

If I were to do this: I'd create a fresh Laravel app myself and install the package inside it. That way a mailcoach update is just a `composer update` away. You can add the API of your dreams in that app.

**Comment by leeovery** [comment]
Thanks Freek. Thats exactly what my notes say in front of me :)

**Comment by freekmurze** [comment]
👍 

You could opt to use our webhook server package to send out the webhooks: https://github.com/spatie/laravel-webhook-server

**Comment by leeovery** [comment]
Do you have a spy cam in my office?!

https://www.dropbox.com/s/par3sxt6pwykstw/Screenshot%202020-01-31%2010.24.16.png?dl=0

Ha!! Thanks for the suggestion!!
