### ISSUE TITLE
[Feature Request] Duplicate Template

### ISSUE THREAD

**Issue by looxis-renaud** [spatie/mailcoach-support#121]
To create and edit Templates, we use _Unlayer_
For different services/projects within our company, we're using different Logos, Links to those projects and texts.
Thus we require different email templates - it would be great if we could just duplicate an existing template (and then adjust and tweak what's different).
This feature would greatly reduce workload.

We're currently doing this with a **workaround**:

- create and save template in _Unlayer_
- switch to _Textlayer_
- copy HTML Code
- create new template and save it
- switch back to _Unlayer_
- Edit/Tweak new template with _Unlayer_

**Comment by freekmurze** [comment]
We'll consider adding this soon.

**Comment by freekmurze** [comment]
You can duplicate templates in the newly released `v2.3.0`.
