### ISSUE TITLE
[Feature Request] use Templates and Unlayer Editor in List > Settings > Welcome Email

### ISSUE THREAD

**Issue by looxis-renaud** [spatie/mailcoach-support#122]
It would be great if we could use the Unlayer Editor and existing Templates
for Transactional Mails (_Welcome Email_ and _Confirmation Mail_)
that can be found in `List > Settings`
when using the option _send customised mail_

**Comment by freekmurze** [comment]
This probably won't be added in the short term, as it would require quite some work and not many people need this.

I suggest that you somehow generate the html needed and copy that in the welcome/confirmation mail fields.
