### ISSUE TITLE
HTML is not valid for multiple href query string parameters in href links (For campaign editor)

### ISSUE THREAD

**Issue by krizzdev** [spatie/mailcoach-support#123]
We have problems to add href links with multiple query string parameters.

Steps to reproduce:
Edit the email content of a campaign with the editor of your choice. (In our case monaco or Unlayer)

Add a link to a text or button with multiple Query String parameters:

`<a href="https://example.com?foo=bar&bar=foo">Test</a>`

And hit Save Content.

It will throw a The HTML is not valid (DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1).

When using only one query param it works
`<a href="https://example.com?foo=bar">Test</a>`

I think the HtmlRule isn't passing. But I don't know why yet.

When we edit the template itself, it works.

Short script for testing in Tinkerwell:

`
```
$dom = new DOMDocument('1.0', 'UTF-8');

$value = '<a href="https://example.com?foo=bar&bar=foo">Test</a>';
$dom->loadHTML($value, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_NOWARNING);
````

**Comment by raulp** [comment]
@ChrisSFR in all my projects where i used DOMDocument for HTML i used:

```
libxml_use_internal_errors(true);
libxml_disable_entity_loader(true);
```

I'll start some research to see exactly if they are safe or not, but i never had issues before, and i did lots of XPath related queries and so on on HTML.

But, also, in my cases, i do `htmlentities()` om the value before i load it (which will fix the error too). And i do `html_entity_decode()` when i call `$dom->saveHTML()`

**Comment by krizzdev** [comment]
thanks @raulp for the response. But it's not in my own code, it's in the HtmlRule.php of spatie.
I reposted the issue now directly in spatie/mailcoach :)

**Comment by freekmurze** [comment]
Closing this here. We'll continue the conversation on spatie/mailcoach.
