### ISSUE TITLE
Email list sort by subscribers tags count fails

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#124]
Hi there,

I'm trying to sort tags by count, I got:

![Captura de Pantalla 2020-03-28 a la(s) 10 45 18 a  m](https://user-images.githubusercontent.com/6526545/77827276-9dc3dc00-70e2-11ea-88f0-b949c5dcf76b.png)

If that were possible you can have a visual of the mayor subscribers per tag

**Comment by riasvdv** [comment]
Fixed in 2.4.4!
