### ISSUE TITLE
ImportSubscribersJob fails importing 40k subscribers

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#125]
Hi there

I'm trying to import 40k subscribers, the job filed and UI does not reflect that also.

Do I need to change some config to allow tho import such a huge list?

Images references are below.

![Captura de Pantalla 2020-03-28 a la(s) 11 38 37 a  m](https://user-images.githubusercontent.com/6526545/77828428-5ab93700-70e9-11ea-94c4-0a1c8e2eb281.png)
![Captura de Pantalla 2020-03-28 a la(s) 11 40 19 a  m](https://user-images.githubusercontent.com/6526545/77828431-5d1b9100-70e9-11ea-969b-89cddffb7fa5.png)

**Comment by goaround** [comment]
You have to raise the timeout for the mailcaoch queue in config/horizon.php. How many subscriber have been imported?

**Comment by RicardoRamirezR** [comment]
Thanks @goaround about 27k

**Comment by goaround** [comment]
Than raise the timeout to 1200 seconds = 20 minutes and the import should be completed. 

I run into the same issue. @freekmurze I think it would be better to chunk an import job into 1.000 subscribers. That should solve the issue.

**Comment by freekmurze** [comment]
@goaround right now, we already use generators to process each row individually so memory usage is low, even for big files. Do you have a specific code change in mind?

**Comment by freekmurze** [comment]
@RicardoRamirezR In the installation instructions I've updated the default timeout values of the queues to an hour. I think that your import problem will be solved when setting your timeouts to higher values too.

https://mailcoach.app/docs/v2/package/general/installation-and-setup#install-horizon

**Comment by goaround** [comment]
> @goaround right now, we already use generators to process each row individually so memory usage is low, even for big files. Do you have a specific code change in mind?

It the timeout is large enough, the import runs smooth but it can take quite long for a large list of subscribers. I would at suggest a warning if you try to import more than 10.000 subscribers and the timeout is quite low.

**Comment by freekmurze** [comment]
Holding off to adding a such a message. I've updated the default timeout to an hour, I think this should be sufficient for 99% of cases.
