### ISSUE TITLE
Push to spatie/laravel-mailcoach

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#126]
Is there a possibilty to push some commits to spatie/laravel-mailcoach?

**Comment by freekmurze** [comment]
Unfortunately not. GitHub does not allow us to make repo accessible for our licensees in a cost effective way.

For now, the easiest way to give us code changes is to create a patch file. Most IDEs allow to do this. 

Feel free to open up a new issue that includes a patch file and a description of what it does, make sure to update the tests as well.
