### ISSUE TITLE
[Suggestion] Include campaign name in delete popup

### ISSUE THREAD

**Issue by jorenvh** [spatie/mailcoach-support#128]
Currently when deleting a campaign a confirmation popup is shown, but it would even be better if the confirmation message would include the name of the campaign that is going to be removed.

**Comment by freekmurze** [comment]
Good idea.

@sebastiandedeyne Right now, that text is hardcoded in the `x-modal` in the `layouts/app.blade.php`  It is triggered by the  `data-confirm` on the `x-form-button` in the `row.blade.php`. 

If it doesn't take too much time, could you add a way to pass a string with the confirmation message?
