### ISSUE TITLE
Spatie\Mailcoach\Jobs\ImportSubscribersJob fails with S3 disk

### ISSUE THREAD

**Issue by arthurkirkosa** [spatie/mailcoach-support#129]
`'import_subscribers_disk' => env('MAILCOACH_UPLOAD_DISK', 'mailcoach-s3'),`
Using an S3 disk fails the import job

`Box\Spout\Common\Exception\IOException: Could not open 11/customers.csv for reading! File does not exist. in /var/www/deliciisanatoase.ro/vendor/box/spout/src/Spout/Reader/ReaderAbstract.php:118`

**Comment by freekmurze** [comment]
Currently, the must set to `import_subscribers_disk` to a disk that uses the `local` driver. I'll add this to the comment of the config file

**Comment by arthurkirkosa** [comment]
Can you update the ticket when this changes?

Or is there a way to subscribe to the change-log changes?

**Comment by freekmurze** [comment]
You can view the changelog here. https://mailcoach.app/roadmap

**Comment by arthurkirkosa** [comment]
Already doing this. Thanks
