### ISSUE TITLE
Support for Postmark bulk sending?

### ISSUE THREAD

**Issue by Spone** [spatie/mailcoach-support#13]
Hi,

would you add Postmark to your supported email providers? They recently introduced their Bulk sending API (see https://postmarkapp.com/blog/api-bulk-the-final-frontier and https://postmarkapp.com/developer/user-guide/sending-email/sending-with-api#batch-emails)

Thanks!

**Comment by freekmurze** [comment]
Currently we have no plans for adding another driver, but if enough people ask for I'd I'll consider adding support.

You could also opt to build the driver yourself. Here's the video on how a driver works: https://mailcoach.app/video-course/how-mailcoach-was-built/tracking-opens-and-clicks
