### ISSUE TITLE
[Feature Request] ongoing/recurring campaign

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#130]
Is there a possiblity (beside the welcome mail) to have a campaign which is ongoing and not finished after it is sent to actual list.

For example an onboarding mail where you get x days after subscribed to the list an email with instructions how to use the product and after another x days the second mail how to do more exiting things with it.
In the actual setup I can only send the mails to the existing subscriber... and the future subscriber don't get the email or I've to send it a second time...

**Comment by freekmurze** [comment]
What you are describing are drip campaigns. We are currently discussing whether we should add support for it, but it might take a while, at the earliest at the end of Summer.

**Comment by connecteev** [comment]
+1 @freekmurze Drip campaigns would be incredibly useful.

**Comment by crzzano** [comment]
+1 @freekmurze  Drip campaigns would be incredibly useful. :-)
