### ISSUE TITLE
[Feature Request] Translation (frontend/backend/mails)

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#131]
Add translation to mailcoach

[translation_mails.patch.zip](https://github.com/spatie/mailcoach-support/files/4408548/translation_mails.patch.zip)
[translation_landingPage.patch.zip](https://github.com/spatie/mailcoach-support/files/4408550/translation_landingPage.patch.zip)

Or would you prefer shortkeys?

update:
[translate_app_templates.patch.zip](https://github.com/spatie/mailcoach-support/files/4410033/translate_app_templates.patch.zip)
[translate_app_layouts.patch.zip](https://github.com/spatie/mailcoach-support/files/4410036/translate_app_layouts.patch.zip)

**Comment by freekmurze** [comment]
We have decided not to add translations for now. Not too many people are asking for localisation options atm, and we'd like to keep the code base as simple as possible.

We might change our stance on this in the future.

**Comment by nsouto** [comment]
Hope you change your mind, I really need translations as currently I have to send both languages in the same email or find a way to flag users for one or another language.

**Comment by mbardelmeijer** [comment]
@freekmurze would you accept a full PR with translations in Dutch for mails & application on the `spatie/laravel-mailcoach` branch?
