### ISSUE TITLE
Using a custom mailable results in CouldNotSendCampaign::noContent exception

### ISSUE THREAD

**Issue by jbraband** [spatie/mailcoach-support#133]
From the documentation regarding custom Mailable classes:
```
Campaign::create()
    ->useMailable(MyCustomMailable::class)
    ->sendTo($emailList);
```

The Campaign::useMailable() method sets the campaign property 'mailable_class'

After executing $campaign->send(), the ensureSendable method checks for the property 'mailable'. I believe this should be checking 'mailable_class'

I have v2.4.1 pulled and the proposed change is in this file: spatie\laravel-mailcoach\src\Models\Campaign.php, line 332

Change 
```
        if (! is_null($this->mailable)) {
            return;
        }
```

to

```
        if (! is_null($this->mailable_class)) {
            return;
        }
```

I hope this is the proper place to report this. I'm unable to submit a PR because the repo is private.

Cheers!

**Comment by RicardoRamirezR** [comment]
@jbraband change and to are identical

**Comment by jbraband** [comment]
> @jbraband change and to are identical

Thanks! I updated the first post

**Comment by jbraband** [comment]
It also appears to be not injecting the custom Mailable even with the above change.

DOMDocument::loadHTML() is being passed an empty string in PrepareEmailHtmlAction.php

I am digging into this now.

**Comment by jbraband** [comment]
this is not a working solution, but the Campaign model needs to have its html set at some point when using a custom Mailable.

put this just before the return of Campaign::useMailable() does the trick.

`
        $this->content($this->getMailable()->setCampaign($this)->render());
`

I'm not convinced this is the correct place for it though.

Is anyone successfully using a custom Mailable or have insights?

**Comment by jbraband** [comment]
Thanks @freekmurze! Please let me know if there is anything I can help with or test out for you.

**Comment by freekmurze** [comment]
I've made the suggested change and released it as `v2.6.2`

According to [this test](https://github.com/spatie/laravel-mailcoach-tests/blob/master/Jobs/SendMailJobTest.php#L67-L77), it should work.

Could you let me know if the problem is solved? If not, could you suggest a test for us to fix?

**Comment by jbraband** [comment]
the issue in the first post is resolved.

There is still the problem with the Mailable's content not being injected into the Campaign model as seen in this comment on this issue: https://github.com/spatie/mailcoach-support/issues/133#issuecomment-607508409

Here is the exception I am seeing. I will work up a test method for this and post in the next comment.
![image](https://user-images.githubusercontent.com/1907283/78575062-75c62e00-77f0-11ea-87f6-3b73b37d19aa.png)

**Comment by jbraband** [comment]
@freekmurze I think I'm missing an important concept here.

The test method you linked, I think that it'd fail given the exception I just posted. I went to run the test myself, but the spatie/laravel-mailcoach repository has no tests in it (that I could find)

I tried to `composer require spatie/laravel-mailcoach-tests` but it isnt available via packagist

Any tips for me being able to run tests and work out a new test method that covers the exception above?

**Comment by freekmurze** [comment]
@jbraband The tests seem to be working fine.


 I think that if you put the content of ` spatie/laravel-mailcoach-tests` in a directory called `tests` inside `laravel-mailcoach` you'll be able to run tests.

**Comment by jbraband** [comment]
@freekmurze thanks, i have the test suite running now, slightly embarrassed that i didnt think to just clone the test repo into /tests

going to dig in this morning and track down the difference in how my Mailable is being used versus the test Mailable

**Comment by jbraband** [comment]
@freekmurze so I see that the test it_can_use_a_custom_mailable() dispatches the job SendMailJob

whereas this code snippet dispatches SendCampaignJob at the end of the Campaign::send() method.

`
Campaign::create()->useMailable(MyCustomMailable::class)->sendTo($emailList);
`

I am still digging however, because although the test fails if I switch it to use SendCampaignJob, the campaign has html content by the time it gets to PrepareEmailHtmlAction

I will keep you posted

**Comment by jbraband** [comment]
Ah, i see it now. For the test, the Campaign factory injects the html into $campaign->html. That is how it passes through PrepareEmailHtmlAction and my Mailable does not.

**Comment by freekmurze** [comment]
Thanks for you time investigating this. If you see a simple solution, please send me a diff. Otherwise, I'll try to dig in later this week.

**Comment by jbraband** [comment]
This is a modified test method that throws the same error I'm seeing

```
use Spatie\Mailcoach\Jobs\SendCampaignJob;

    /** @test */
    public function it_can_use_a_custom_mailable()
    {
        $pendingSend = factory(Send::class)->create();

        $pendingSend->campaign->html = null;

        $pendingSend->campaign->useMailable(TestCampaignMail::class);

        dispatch(new SendCampaignJob($pendingSend->campaign));

        Mail::assertSent(TestCampaignMail::class, 1);
    }
```

that tests the ability to do this in our app's codebase
```
Campaign::create()
                   ->useMailable(MyCustomMailable::class)
                   ->sendTo($emailList);
```

**Comment by jbraband** [comment]
I think one approach to fixing this would be to chain in another ActionClass in SendCampaignAction::execute()


```
class SendCampaignAction
{
    public function execute(Campaign $campaign)
    {
        if ($campaign->wasAlreadySent()) {
            return;
        }

        $this
            ->prepareSubject($campaign)
            ->prepareHtml($campaign)                  /* the new action method chained in */
            ->prepareEmailHtml($campaign)
            ->prepareWebviewHtml($campaign)
            ->sendMailsForCampaign($campaign);
    }



    protected function prepareHtml(Campaign $campaign)
    {
        /** @var \Spatie\Mailcoach\Actions\Campaigns\prepareHtmlAction $prepareHtmlAction */
        $prepareHtmlAction = Config::getActionClass('prepare_html', PrepareHtmlAction::class);

        $prepareHtmlAction->execute($campaign);

        return $this;
    }
    ....
}
```

and within PrepareHtmlAction::class we would extract the html from the Mailable and insert it into the html property of the campaign model. Then PrepareEmailHtml and PrepareWebviewHtml actions would have the html available. The new PrepareHtmlAction would only do the work if the $campaign->mailable_class is not null

I'd be more than happy to WIP up a PR if there's a way to do that? I could figure out how to create a patch file too to give you the differences. That's probably the way to go.

**Comment by jbraband** [comment]
I have this coded out and will provide a 'git diff' patch file

the next problem I need to solve is being able to pass data to my custom mailable.

The use case is a Mailable for notifying subscribers of a new article on the site. I want a single Mailable, backed by a blade template, the I pass the article ID to and it fetches the data and passes to the view.

The Campaign::useMailable() method may need another optional argument (and subsequent database field) for parameters to pass to the Mailable. Is there an existing pattern that can be used for this?

**Comment by jbraband** [comment]
[mailable-patch-1.txt](https://github.com/spatie/mailcoach-support/files/4446441/mailable-patch-1.txt)

This patch file is incomplete, but might be worth a look. I added a new action called PrepareHtmlAction that is responsible for injecting the Mailable's rendered HTML into the campaign. The problem with this approach is that by the time the action is called in Spatie\Mailcoach\Actions\Campaigns\SendCampaignAction, the campaign is already flagged as CampaignStatus::SENDING and therefore the mail's HTML cannot be added to the campaign.


[mailable-patch-2.txt](https://github.com/spatie/mailcoach-support/files/4446461/mailable-patch-2.txt)

This second patch works completely for me. It added a check in Campaign::send() just before marking it as "sending"

```

    public function contentFromMailable(): self
    {
        $html = $this->getMailable()
                      ->setCampaign($this)
                      ->render();

        $this->content($html);

        return $this;
    }

    public function send(): self
    {
        .....
        if (! is_null($this->mailable_class)) {
          $this->contentFromMailable();
        }
        .....
    }
```

I'd like to help push this across the finish line, please let me know what else I can do!

**Comment by jbraband** [comment]
I also submitted a PR to the tests repository to cover the html injection

https://github.com/spatie/laravel-mailcoach-tests/pull/1

**Comment by jbraband** [comment]
update: i am getting an exception when the campaign actually sends but only when the mail is queued.

`Serialization of 'Closure' is not allowed`

gotta love code diving :)

**Comment by jbraband** [comment]
found it. The custom Mailable has a callbacks property that is set in CampaignMail::withSwiftMessage()

That callbacks array is causing the serialization exception with the Mailable is queued.

For some reason, a normal campaign does not have this issue. I'm still investigating....

_(note that this string of posts is serving as a trace of what I've done/discovered)_

**Comment by jbraband** [comment]
I see, the stock MailCoach campaign mailable (when not specifying my own) does not implement ShouldQueue. adding ShouldQueue to Spatie\Mailcoach\Mails\CampaignMail breaks sending with the serialization error I am seeing.

I suppose this makes sense, since mailcoach is already queueing a job which send the mail, no need to queue from a queue for performance reasons, just let the SendMailJob take a little longer to synchronously send the mail.

I learned a lot today! My recommendation would be mailable-patch-2.txt above and the PR in the tests repository.

Happy to help! Let me know what else I can do!

**Comment by freekmurze** [comment]
I'll take a look at this today 👍

**Comment by freekmurze** [comment]
This issue has been fixed in `v2.6.4`. Thanks for your help @jbraband 👍

**Comment by nkeena** [comment]
I'm running the latest version `v2.13.0` and this still seems to be an issue. When using a custom mailable it's passing an empty string into line 34 of the `PrepareEmailHtmlAction.php`. Am I missing something that needs to be added to my mailable to inject the HTML?

> It also appears to be not injecting the custom Mailable even with the above change.
> 
> DOMDocument::loadHTML() is being passed an empty string in PrepareEmailHtmlAction.php
> 
> I am digging into this now.

This is the error I keep getting in my `failed_jobs` table only when using a custom mailable:
```
ErrorException: DOMDocument::loadHTML(): Empty string supplied as input in /.../vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/PrepareEmailHtmlAction.php:34
```

**Comment by jbraband** [comment]
Sounds like your mailable implements ShouldQueue, is that correct?

I'm pretty sure the custom mailable must not be queued for it to work. I'll check the next time I'm at my desk.

Consider that mailcoach only sends mail from inside a queued job, so queueing the mail isn't really needed since the "slowness" of sending mail won't slow down a web response to the user.

**Comment by nkeena** [comment]
This is my mailable. It's only extending `CampaignMail` as per the mailcoach documentation.

```php
<?php

namespace App\Mail;

use App\EmailAttachment;
use Spatie\Mailcoach\Mails\CampaignMail;

class ClassMessage extends CampaignMail
{
    public function build()
    {
        $this
            ->from(
                $this->campaign->from_email ?? $this->campaign->emailList->default_from_email,
                $this->campaign->from_name ?? $this->campaign->emailList->default_from_name ?? null
            )
            ->subject($this->subject)
            ->view('mailcoach::mails.campaignHtml')
            ->text('mailcoach::mails.campaignText')
            ->addUnsubscribeHeaders()
            ->storeTransportMessageId();

        foreach (EmailAttachment::query()->where('campaign_id', $this->campaign->id)->get() as $attachment) {
            $this->attachFromStorage($attachment->source);
        }

        return $this;
    }
}

```
