### ISSUE TITLE
[Feature Request] load template on campaign edit

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#134]
It would be a good improvement if i could load my preconfigured templates into a campaing. not just inital config of a campaign to overwrite the actual template.

Perhaps in the content-edit view besides the "Preview" button

**Comment by freekmurze** [comment]
I think most people are happy with initially selecting a template when creating a campaign. I'm going to leave it like it is for now, but we might change our stance when more people should ask for this.
