### ISSUE TITLE
SNS Confirmation

### ISSUE THREAD

**Issue by nsouto** [spatie/mailcoach-support#135]
Hello,

Using 1-click on DO and I’m running into this:

production.ERROR: "Message" is required to verify the SNS Message. {"exception":"[object] (InvalidArgumentException(code: 0): \"Message\" is required to verify the SNS Message. at /var/www/html/vendor/aws/aws-php-sns-message-validator/src/Message.php:150)

When attempting to confirm the SNS subscription to get the data from Amazon.

Thanks

**Comment by riasvdv** [comment]
@nsouto did you enable `raw message delivery` in your AWS settings? This should be **disabled**

**Comment by nsouto** [comment]
Hey @riasvdv I don't have the raw message delivery enabled, I remember seeing that and not enabling it as per the SES docs of Mailcoach but I just confirmed and it's off, which is the default anyway.

**Comment by riasvdv** [comment]
Hmm that's weird, can't find any reason why SNS would send a wrong message.

Can you look into your `webhook_calls` table in the database and copy the payload of what is sent here?

**Comment by nsouto** [comment]
That table is empty, and here is the full stack trace:

[2020-04-03 14:36:16] production.ERROR: "Message" is required to verify the SNS Message. {"exception":"[object] (InvalidArgumentException(code: 0): \"Message\" is required to verify the SNS Message. at /var/www/html/vendor/aws/aws-php-sns-message-validator/src/Message.php:150)
[stacktrace]
#0 /var/www/html/vendor/aws/aws-php-sns-message-validator/src/Message.php(85): Aws\\Sns\\Message->validateRequiredKeys()
#1 /var/www/html/vendor/spatie/laravel-mailcoach-ses-feedback/src/SesSignatureValidator.php(18): Aws\\Sns\\Message->__construct()
#2 /var/www/html/vendor/spatie/laravel-webhook-client/src/WebhookProcessor.php(39): Spatie\\MailcoachSesFeedback\\SesSignatureValidator->isValid()
#3 /var/www/html/vendor/spatie/laravel-webhook-client/src/WebhookProcessor.php(26): Spatie\\WebhookClient\\WebhookProcessor->ensureValidSignature()
#4 /var/www/html/vendor/spatie/laravel-mailcoach-ses-feedback/src/SesWebhookController.php(14): Spatie\\WebhookClient\\WebhookProcessor->process()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Spatie\\MailcoachSesFeedback\\SesWebhookController->__invoke()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(225): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(182): Illuminate\\Routing\\Route->runController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#25 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#30 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#31 {main}
"}

**Comment by nsouto** [comment]
On a side note I did try this on two different installs with the same result.

**Comment by nsouto** [comment]
I put in some debug logging and this is what is found on the validateRequiredKeys function:

[2020-04-03 14:41:10] production.ERROR: array (
  '/ses-feedback' => NULL,
)
[2020-04-03 14:41:10] production.ERROR: array (
  0 => 'Message',
  1 => 'MessageId',
  2 => 'Timestamp',
  3 => 'TopicArn',
  4 => 'Type',
  5 => 'Signature',
  6 =>
  array (
    0 => 'SigningCertURL',
    1 => 'SigningCertUrl',
  ),
  7 => 'SignatureVersion',
)

**Comment by nsouto** [comment]
Let me know if there is anything else I can do on my end to help debug this.

Seems AWS is not sending anything or it's being stripped somewhere else maybe?

I tried looking at the request() but its contents are the same as the $data var, so I'm guessing that var is set to the request() content at some point.

**Comment by riasvdv** [comment]
Could you try logging `file_get_contents('php://input')` inside `SesSignatureValidator` inside the `isValid` function? Then we know exactly what SNS is passing in.

Could you also try recreating the topic? I've read that in some cases that also fixes it

**Comment by nsouto** [comment]
This is the result:

[2020-04-03 15:35:31] production.ERROR: {
  "Type" : "SubscriptionConfirmation",
  "MessageId" : "410147f9-e883-4870-af56-2a17267d9236",
  "Token" : "2336412f37fb687f5d51e6e2425f004aed7b74017577c53203a2867d78b7c8926db45719d27623044541a2a1bc26d2b35d6fd215bc590ab7f707fa39e2fce8e18fff010d177930bfb43f3cc4552b02c78ef237754f6675658ed8d55637b223f31d134832da9b6bed028a3467cf07a7371edb8171227b69845f53e0daab58dd1b",
  "TopicArn" : "arn:aws:sns:us-east-1:315013043735:mailcoach-serveby",
  "Message" : "You have chosen to subscribe to the topic arn:aws:sns:us-east-1:315013043735:mailcoach-serveby.
To confirm the subscription, visit the SubscribeURL included in this message.",
  "SubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-east-1:315013043735:mailcoach-serveby&Token=2336412f37fb687f5d51e6e2425f004aed7b74017577c53203a2867d78b7c8926db45719d27623044541a2a1bc26d2b35d6fd215bc590ab7f707fa39e2fce8e18fff010d177930bfb43f3cc4552b02c78ef237754f6675658ed8d55637b223f31d134832da9b6bed028a3467cf07a7371edb8171227b69845f53e0daab58dd1b",
  "Timestamp" : "2020-04-03T15:35:31.414Z",
  "SignatureVersion" : "1",
  "Signature" : "VhKol2CBty77iUbqKboE5kufzbZzUJY/CJVxw6KzOao7ohaemXCjNmRWvh0zOMvaFmaRBC4bY94bDDIjf+sHwHw7ZL9VGkYXSLPbsmRx+7iEm1x9NXRnHZsezhVBVbSMXbPMwypXRNNNVXm02xdVrEG47QTqFTBlr7UrlDdgbC7NPCtURx0YLXIAxIfRiqgZcn5Hmd5Rcs0JbH9sE/X6QhdRQn0nbplHCQaJ30vdr+cPFLBscT6CJMaHKGx2lp/SsNsuKrJXyXcS5ihmaOwlD/zZ4Q1N2TLI+TjRilzHnnah22+pXPVaHJCSCJ43fj3+BBJBxOAAkuVp40TE0wUTKA==",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-a86cb10b4e1f29c941702d737128f7b6.pem"
}

**Comment by riasvdv** [comment]
Hmm, there is definitely a "Message" in there, I'll research it a bit further

**Comment by riasvdv** [comment]
Before I commit anything, could you test the following for me?

Replace this

```php
$message = count($request->all())
    ? new Message($request->all())
    : Message::fromRawPostData();
```

With this

```php
$message = Message::fromJsonString((string) $request->getContent());
```

Inside `SesSignatureValidator` 

Sorry for the way we're debugging this, but I really can't seem to reproduce this myself

**Comment by nsouto** [comment]
That seems to have worked, no errors and the subscription was confirmed successfully

**Comment by riasvdv** [comment]
Awesome!

**Comment by riasvdv** [comment]
I've tagged 2.1.1 of laravel-mailcoach-ses-feedback that contains this fix!
