### ISSUE TITLE
special char "&" cannot be used in content editor

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#136]
special char "&" cannot be used in content editor.
Not in links not in normal text

> The HTML is not valid (DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 1).

perhaps this would help:
https://www.php.net/manual/en/function.libxml-use-internal-errors.php
https://stackoverflow.com/questions/1685277/warning-domdocumentloadhtml-htmlparseentityref-expecting-in-entity/10482622#10482622

**Comment by riasvdv** [comment]
Should be fixed in 2.4.5!

**Comment by timmoh** [comment]
@riasvdv thx for quick fix - saving works now. but the same fix should be in PrepareEmailHtmlAction.php
Sending doesn't work anymore

> ErrorException: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 3 in /vendor/spatie/laravel-mailcoach/src/Actions/Campaigns/PrepareEmailHtmlAction.php:32

by the way: if the use a link like https://test.test/?foo1=bar&foo=bar the query get's deleted. For tracking with google and other tools it would be better if it stays

**Comment by riasvdv** [comment]
This should be fixed in 2.4.6, I thought sending used the same validation.

I've tested sending now with the editor, and all query params are intact when sending

![image](https://user-images.githubusercontent.com/3626559/78346989-18d43900-75a0-11ea-9b99-257f9ff2fdfc.png)

**Comment by timmoh** [comment]
works fine, can be closed
