### ISSUE TITLE
Can merge tags be used in subject?

### ISSUE THREAD

**Issue by rafahernandez** [spatie/mailcoach-support#137]
Tried to use `::subscriber.first_name::` in the subject but it's not being replaced. Another user told me it was possible, but I just can't seem to be able to use them. 

Running on standalone, with unlayer as editor.

**Comment by freekmurze** [comment]
I'll add this soon.

**Comment by freekmurze** [comment]
You can use replacers in the subject starting from Mailcoach 2.5.0
