### ISSUE TITLE
1-Click Install script error

### ISSUE THREAD

**Issue by nsouto** [spatie/mailcoach-support#138]
Hello,

When using the 1-click install and creating a new user at this stage:

Name: Nuno Souto
/var/opt/mailcoach/setup.sh: line 90: [: too many arguments

Seems to work when the name doesn't contain spaces.

Doesn't seem to break anything though, but not sure how the user is created yet.

Also on this same topic if there is a problem with the composer part we get the following:

> Completing the configuration for Mailcoach...

Setting composer auth.Installing Mailcoach...

Creating a "spatie/mailcoach" project at "/var/www/mailcoach"
Installing spatie/mailcoach (2.0.12)
  - Installing spatie/mailcoach (2.0.12): Downloading (100%)
Created project in /var/www/mailcoach
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies

  [Composer\Downloader\TransportException]
  The "http://repo.packagist.org/p/league/html-to-markdown%24244d96711c5fe2930457b9907640aaf113cafec4409800ad8c69df4cb9ee9313.json" file could not be downloaded: failed to open stream: Connection refused

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

Setting env files...

Migrating database...

PHP Warning:  require(/var/www/mailcoach/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/mailcoach/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/mailcoach/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mailcoach/artisan on line 18
Creating user...

PHP Warning:  require(/var/www/mailcoach/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/mailcoach/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/mailcoach/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mailcoach/artisan on line 18
Moving files...

> rm -rf public/vendor/mailcoach
> ln -s $(pwd)/vendor/spatie/laravel-mailcoach/resources/dist public/vendor/mailcoach
PHP Warning:  require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/artisan on line 18
Starting Horizon...

horizon: ERROR (not running)
horizon: ERROR (spawn error)
Installation complete. Access your new Mailcoach site in a browser to continue. Database credentials can be found in /root/.digitalocean_password

Nuno

**Comment by riasvdv** [comment]
Seems like this was an unfortunate error during the composer install.

> [Composer\Downloader\TransportException]
The "http://repo.packagist.org/p/league/html-to-markdown%24244d96711c5fe2930457b9907640aaf113cafec4409800ad8c69df4cb9ee9313.json" file could not be downloaded: failed to open stream: Connection refused

Which caused the rest of the commands to continue (and fail). I'll look into making the script more robust when an error happens.

**Comment by freekmurze** [comment]
We'll take care of this at the relevant repo.
