### ISSUE TITLE
[Feature] content on sent campaigns

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#139]
If you want to look back to an old campaign it's hard to remember about the content which you've written and sent month before. therefore the content route should also be in the sent Campaign.

[add_Content_Preview_for_sent_Campaigns.patch.zip](https://github.com/spatie/mailcoach-support/files/4428210/add_Content_Preview_for_sent_Campaigns.patch.zip)

**Comment by freekmurze** [comment]
You can already access the content of a sent campaign by clicking this link.

<img width="753" alt="Screenshot 2020-04-05 at 14 50 18" src="https://user-images.githubusercontent.com/483853/78498820-e1ef5600-774c-11ea-8456-0997e0263ae0.png">
