### ISSUE TITLE
How can I make it run on vapor?

### ISSUE THREAD

**Issue by MarkusNovak** [spatie/mailcoach-support#14]
Hey there,

I have some projects (with each having email subs) running on vapor.laravel.com and would like to use mailcoach there too. Right now i don't own a forge subscription to make maintaining & deployment easier.

The errors are about redis. Has anyone made this working on vapor??

Tested it locally, very good product I want to start using :)

Thank you!

**Comment by freekmurze** [comment]
Hi, thanks for the kind words.

Vapor currently isn't supported. Take a look in this issue #8
