### ISSUE TITLE
InvalidSortQuery sent_at

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#140]
Hi there!

![Captura de Pantalla 2020-04-03 a la(s) 2 56 35 p  m](https://user-images.githubusercontent.com/6526545/78399934-70cc6900-75bb-11ea-86c5-7e115d57e03c.png)

**Comment by freekmurze** [comment]
On which screen do you get this? Could you shared that exception on Flare and past the shared url here?

**Comment by RicardoRamirezR** [comment]
@freekmurze on Campings / camping /outbox / problem

[Flare share](https://flareapp.io/share/v5p282PE#F53)

**Comment by freekmurze** [comment]
This has been fixed in the newly tagged release 2.4.7
