### ISSUE TITLE
Test email - replacer don't work

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#142]
Replacer don't work in Test E-Mail

**Comment by freekmurze** [comment]
The replacers aren't triggered in a the test email because most replacer are personalised and the test email is sent to a loose email address instead of a real subscriber.

We'll try to improve on this in a future version of the package.

**Comment by timmoh** [comment]
@freekmurze just a short question: is there any schedule for the next release step?

**Comment by freekmurze** [comment]
Probably around Laravel 8 gets released, but nothing is set in stone yet.
