### ISSUE TITLE
Campaign not sent

### ISSUE THREAD

**Issue by agus-ngorder** [spatie/mailcoach-support#144]
Hi, I just setup mailcoach with digitaloean 1-click installation. everything is ok on the install process until up and running. But when I start to create campaign and send it I got error.

i inspect to the horizon/failed and see the failed message bellow.

![Screen Shot 2020-04-07 at 20 06 07](https://user-images.githubusercontent.com/52845597/78673099-db5b0d00-790b-11ea-9933-e0e7be014e04.png)

Please help

**Comment by freekmurze** [comment]
That is unfortunate, let's try to fix this.

Could you replace all content in `/var/www/html/config/mailcoach.php` by the content on this page: https://raw.githubusercontent.com/spatie/Mailcoach/master/config/mailcoach.php

After that restart your server and retry the `SendCampaignJob` (by pressing that purple button in the top left corner on your screenshot).

**Comment by agus-ngorder** [comment]
i've changed the config/mailcoach.php with the new one, restart Nginx, retry campaign and get same result, still not work

**Comment by agus-ngorder** [comment]
ok it works now after restarting supervisor, thanks

**Comment by agus-ngorder** [comment]
btw I'm curious what chart library you use? it looks beautiful

**Comment by freekmurze** [comment]
It isn't a library, but something we've made ourselves. It's an animated svg.
