### ISSUE TITLE
Mailcoach API

### ISSUE THREAD

**Issue by agusesetiyono** [spatie/mailcoach-support#148]
Hi,
I want to synchronize users data from our saas to mailcoach, we want to tag registered users as `trial`, and when someday they upgrade the tag will be `paid`, still on same list.

How the best way to do this? will you provide API for managing contacts on the near future?

**Comment by freekmurze** [comment]
We probably won't provide a full blown API anytime soon. If you need this, we recommend installing mailcoach as a package, so you can use the full power of the Laravel framework to create any API you need.

When installed as a package, this is how you can create and manipulate subscribers: https://mailcoach.app/docs/v2/package/working-with-lists/subscribing-to-a-list

**Comment by timmoh** [comment]
@agusesetiyono may be https://github.com/leeovery/mailcoach-api will help you.

**Comment by freekmurze** [comment]
Thanks for the excellent suggestion @timmoh
