### ISSUE TITLE
How to properly use custom Mailable

### ISSUE THREAD

**Issue by Gaia-Nutrition** [spatie/mailcoach-support#149]
I'm currently integrating Mailcoach as a replacement for Mailchimp to allow users to send out pre-formatted, branded newsletters. I have a markdown editor set up on the frontend and have so far just dumped the rendered Markdown into an existing Mailchimp template.

Now with Mailcoach: How do I get the content into my custom Mailable?  The docs say:
```php
Campaign::create()
    ->useMailable(MyCustomMailable::class)
    ->sendTo($emailList);
```
which does not allow me to provide view data to the Mailable. My current workaround is to not use a custom Mailable with Mailcoach but instead pre-render my Mailable and use the resulting HTML as content like this:
```php
$content = (new MyCustomMailable($markdown))->render();

Campaign::create()
    ->content($content)
    ->sendTo($emailList);
```
Problem: The raw Markdown it not persisted anywhere so users cannot modify or duplicate existing campaigns. A workaround for this would be to save the raw Markdown in yet another Model/table.

Am I missing something?

**Comment by freekmurze** [comment]
In the `mailcoach_campaigns` table there is a field called `structered_html`. You could save the markdown in that field. We do that when using the unlayer editor.

**Comment by Gaia-Nutrition** [comment]
This "fixes" both issues (raw markdown persisted + getting data into Mailable) so I'll close the issue.

**Comment by ziming** [comment]
Trying to do the same thing here, @Gaia-Nutrition and @freekmurze 

Is this the correct way and will it display correctly in unlayer or other editor too?

```php
$htmlContent = (new LetterMailable($markdownContent, $user)->render();
Campaign::create(['structured_html' => $markdownContent])->content($htmlContent)
```

Thanks!

**Comment by Gaia-Nutrition** [comment]
@ziming not sure about Unlayer, haven't tried that one before. But according to @freekmurze, Unlayer saves it's markup to `structured_html` so I think you can't use this field yourself then.

**Comment by ziming** [comment]
Didn't freek say:

```
You could save the markdown in that field. We do that when using the unlayer editor.
```

**Comment by ziming** [comment]
Ok, just gave unlayer editor a try, unlayer saves a json to structured_html. So I guess I won't save it to structured_html or it breaks compatibility with unlayer next time if I decide to install it.

**Comment by ziming** [comment]
It will be great if we can set a custom mailable that except arguments to its constructors like this

```php
Campaign::create()->useMailable(new CoolMailable($books));
```

Rather than 

```php
$content = (new MyCustomMailable($markdown))->render();

Campaign::create()
    ->content($content)
    ->sendTo($emailList);
```
