### ISSUE TITLE
Use with an existing user list

### ISSUE THREAD

**Issue by LorenzoSapora** [spatie/mailcoach-support#15]
I have an existing user table that I use for mailing, and I'm scoping out how best to integrate mailcoach into an existing system. 

Would the best way just be seeding users already authorised for newsletters into the `mailcoach_subscribers`?  Seems a lot of duplication, especially considering I'd have to extend user registration, edit, deletion to fill/update the subscribers.

Unless I am missing something?

**Comment by freekmurze** [comment]
Currently, Mailcoach expect all subscribers to be win the `mailcoach_subscribers` table. If your users table should have a 1-1 relation with a subscription. I'd use model events to keep those tables in sync. That way you can subscribe the user when it gets created, and delete the subscriber when the user gets deleted.
