### ISSUE TITLE
Rate-limiting key missing

### ISSUE THREAD

**Issue by Gaia-Nutrition** [spatie/mailcoach-support#150]
Currently, the `mailcoach.throttling.redis_key` config is not being used in `SendMailJob.php`. Since I'm on a tight SES sending limit, I'd like to use the same key for all my Email jobs to prevent SES rejecting emails in case transactional emails go out at the same time.

Also, it might make sense to use the same key on all other emails as well (Welcome, ConfirmSubscriber, CampaignSummary, etc.) in case the same mailer is used there

**Comment by freekmurze** [comment]
For now, we're going to keep things as they are, but I'll consider making some improvements around this in the next major release.

Thanks for your remarks.
