### ISSUE TITLE
Confirmation of imported subscribers email bugs

### ISSUE THREAD

**Issue by renatonascalves** [spatie/mailcoach-support#156]
A small bug I noticed while importing a small list.

The email: Import Subscribers Result Mail.

The first link is sending me to: `imap://MYEMAIL.COM@MYEMAILPROVIDER.COM:993/fetch>UID>/INBOX>LISTPROVIDER`

And the second one is redirecting to the wrong folder.
`https://site.com/storage/22/import.csv` where the correct path is `https://site.com/storage/app/public/22/import.csv`

<img width="762" alt="Screen Shot 2020-04-18 at 13 54 35" src="https://user-images.githubusercontent.com/19148962/79644015-8f665e80-817c-11ea-90f4-a5e0658808ff.png">

**Comment by freekmurze** [comment]
Thanks for reporting this.

Because it's hard to get these link right for every configuration, I've decided to remove them from the mail for now.

**Comment by renatonascalves** [comment]
Understood! Also, I'm not sure how useful this email is.

I'd say spending time on the front-end of the import would be better than the email. Since after importing a list, nothing happens until you refresh the page. Which is not the best UI/experience.

**Comment by freekmurze** [comment]
Don't you see this message after uploading? https://github.com/spatie/laravel-mailcoach/blob/8117e95fae24ba5836578640844bced35540d17c/src/Http/App/Controllers/EmailLists/ImportSubscribersController.php#L33
