### ISSUE TITLE
Middleware Group for the Front routes

### ISSUE THREAD

**Issue by renatonascalves** [spatie/mailcoach-support#157]
I'm looking for a way to add a custom middleware to a specific route:

```php
Route::post('subscribe/{emailListUuid}', '\\' . SubscribeController::class)->name('mailcoach.subscribe')
    ->middleware(\Spatie\Honeypot\ProtectAgainstSpam::class);
```

The use case is that the newsletter form is in another site and I'm using the Laravel Honeypot package, together with a NeverBounce integration to decrease spam (together with other honey pot fixes).

The problem is that right now I need to edit core files (laravel-mailcoach on the vendor folder) to accomplish it. And adding the middleware in the `Kernel.php` is affecting other POST requests.

Could you add the Front routes to  a group so that others can add their own middlewares to it?

**Comment by freekmurze** [comment]
Sure, I'll take care of this in the next few weeks. If you need it fast, I'd accept a PR that adds this to the package.

**Comment by renatonascalves** [comment]
@freekmurze Happy to! But isn't `laravel-mailcoach` a private repo? I can't find this repo on the Spatie org.

**Comment by freekmurze** [comment]
@renatonascalves you can request access via your account at https://mailcoach.app
<img width="1147" alt="Screenshot 2020-04-23 at 09 27 14" src="https://user-images.githubusercontent.com/483853/80071318-afaf6800-8544-11ea-93cc-d40b06da4698.png">

**Comment by renatonascalves** [comment]
Have access now!  Tks! :)

**Comment by freekmurze** [comment]
To keep our issue tracker clean, I'm going to close this one, but will revisit this in the future. Like said above, if you needs this quick, send a PR 👍 

Thank you for your Mailcoach tweet earlier today, really made my day 😄
