### ISSUE TITLE
Uploading image in unlayer does not work

### ISSUE THREAD

**Issue by rnleal** [spatie/mailcoach-support#158]
When uploading image using unlayer, the progress spinner is stuck to 50%. 
![Screen Shot 2020-04-19 at 1 41 36 PM](https://user-images.githubusercontent.com/60339084/79680588-e2571900-8243-11ea-8851-ec2272dae498.png)

Although, the ajax upload is successful.

**Comment by freekmurze** [comment]
Do you get any error in the application log? Is the endpoint where you are uploading to giving a response?

What is the maximum post size and upload size you have set in your `php.ini`?

**Comment by rnleal** [comment]
> Do you get any error in the application log? Is the endpoint where you are uploading to giving a response?
> 
> What is the maximum post size and upload size you have set in your `php.ini`?

There is no error on the application log. The file was uploaded upon checking on the directory. 
Both post size and upload size are 100M

**Comment by betaselect** [comment]
I have the same issue as rnleal. The AJAX uploader works until 50% complete and then just freezes. No further errors in the application log or in the Debugbar. Relevant information: I use digital ocean spaces as S3 like storage, Laravel 7.6.2, Mailcoach 2.7.1

Edit: Did some further investigation: the files does get uploaded to server. I can see it in the database under media and mailcoach_uploads . And it's uploading the file to my local storage public folder. Where it creates a new folder for each upload? (E.g. a folder with the name: 1, containing the upload and a conversion folder?)

**Comment by riasvdv** [comment]
Can you check in your browser console or network tab what the response returns? 

It should contain a json response with only a "url" key like this:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/3626559/80067445-2137e800-853e-11ea-8665-774098417a65.png">

If you have this response, can you check if the url is accessible?

**Comment by freekmurze** [comment]
@InWave could you let us know what the response from that endpoint is? ⏫

**Comment by rnleal** [comment]
The response is a url and the file has been uploaded, but just like @InWave's issue, on the frontend, it stuck on 50%.

I also want to add that this only happens on the package version, it is working perfectly fine on the App version.

**Comment by riasvdv** [comment]
Is the URL accessible? If you copy paste it in your browser?

**Comment by betaselect** [comment]
Sorry missed the response, @riasvdv @freekmurze. 

This is the response: 
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/16295795/80687422-8d7c9380-8aca-11ea-8cae-2bb1515cc89b.png">

And indeed the URL is not accessible from the browser. Although this is not unexpected behavior all my files uploads in the rest of the application are done to Spaces from DigitalOcean.

**Comment by riasvdv** [comment]
Unlayer needs to be able to access the image to finish uploading and displaying it, make sure you're uploading to a publicly accessible bucket.

**Comment by riasvdv** [comment]
It could also be possible you still have to run `php artisan storage:link` in your Laravel install so the public disk is accessible https://laravel.com/docs/master/filesystem#the-public-disk
