### ISSUE TITLE
Feature request: add segment image Pixel option

### ISSUE THREAD

**Issue by axtg** [spatie/mailcoach-support#162]
I am using Segment.com as my Customer Data Platform, I'd love an opportunity to push Mailcoach data in there (encoded e-mail address to link to other data sources).

See: https://segment.com/docs/connections/sources/catalog/libraries/server/pixel-tracking-api/

**Comment by freekmurze** [comment]
This feature request seems a bit too specific. I think most of our users don't need this. Take a look at the `actions` array in the `mailcoach` config file. You'll find several actions that allow you to hook into the sending process and add stuff.
