### ISSUE TITLE
subscribers replaces not substituted in subject

### ISSUE THREAD

**Issue by rafahernandez** [spatie/mailcoach-support#164]
Hello this is related to #137 

Tried testing replacers on subject with partial success, as the 'subscribers' tags weren't not replaced.

Eg. when using this as subject

`foo ::list.name:: ::subscriber.first_name:: ::webviewUrl::  ::subscriber.first_name:: bar`

The following is produced

`foo Test ::subscriber.first_name:: https:/[MY_URL]/webview/b6262f17-b5dc-4ccf-9aa4-fbd4c96a02f4 ::subscriber.first_name:: bar
`

Could not find anything in the logs and not sure if I should look somewhere else. No issue when using any replacers on the body of emails. Thanks in advance.

**Comment by rubenvanassche** [comment]
Hi @rafahernandez,

A `composer update` should solve this problem, we've fixed this bug  in `laravel-mailcoach:2.9.2`. I will close this issue for know, please let me know when you run into any other issues.
