### ISSUE TITLE
Cannot install package at all. Conflict with cakephp/chronos 2.0.4

### ISSUE THREAD

**Issue by binaryk** [spatie/mailcoach-support#167]
![image](https://user-images.githubusercontent.com/6833714/80136063-de135e80-85a9-11ea-86ae-f2e966f03a2f.png)

**Comment by binaryk** [comment]
It works when I manually downgraded this to: 

```
   "cakephp/chronos": "1.3.0",
```

**Comment by ziming** [comment]
Hmm but the latest version of laravel nova (3.4.1) now uses chronos v2. So I would keep this issue open actually.

**Comment by binaryk** [comment]
That's true, just twitted that, because Horizon uses chronos v2 as well. Mailcoach is using v1 and horizon 4. So we cannot have Horizon and Mailcoach at the same time.

**Comment by freekmurze** [comment]
This has been fixed in the latest version of the package.
