### ISSUE TITLE
Custom segment class not visible in campaign detail

### ISSUE THREAD

**Issue by electronick86** [spatie/mailcoach-support#168]
The page /mailcoach/campaigns/42/settings don't show the correct custom segment. It show

I see that the file resources/views/vendor/mailcoach/app/campaigns/draft/partials/emailListFields.blade.php contains  
` 
@if($campaign->usingCustomSegment())
        <x-help>
            Using custom segment class ({{ $emailList->segment_class }}).
        </x-help>
    @else
`

If I'm correct, it should be 
`    
@if($campaign->usingCustomSegment())
        <x-help>
            Using custom segment class ({{ $campaign->segment_class }}).
        </x-help>
    @else
`

Or maybe $campaign->getSegment()->description()?

![AUTO_Gocar_Daily_2020-04-28___Mailcoach](https://user-images.githubusercontent.com/8201501/80496307-4d51cf80-8969-11ea-8934-5436225fc7d6.jpg)

Thank you Spatie for the great work!!!

**Comment by riasvdv** [comment]
Fixed in 2.10.2!

**Comment by electronick86** [comment]
Hello Rias,

Is it the message you expect? 

![Gocar_Daily_2020-05-06___Mailcoach](https://user-images.githubusercontent.com/8201501/81177460-fd958880-8fa6-11ea-8d19-c59055807864.jpg)

I have the feeling that `(class: {{ $campaign->segment_class }})` is not necessary.

**Comment by riasvdv** [comment]
You're right, fixed in 2.11.4!

**Comment by electronick86** [comment]
thanks!
