### ISSUE TITLE
Use sender email of the list for confirmation mails

### ISSUE THREAD

**Issue by hanspagel** [spatie/mailcoach-support#17]
I setup multiple lists with different sender domains (e. g. demo@example1.com, demo@example2.com). Confirmation emails for those lists are sent from the generic sender (config/mail.php) instead of the specific one from the list.

Wouldn’t it make sense to take the sender from the list to send confirmation mails for the list?

**Comment by freekmurze** [comment]
Thanks for your suggestion.

You're right, I've changed this in `v1.2.2`.

Run `composer update` in a couple of minutes to pull that version in.
