### ISSUE TITLE
Campaign summary

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#173]
Is this the new look?
![Captura de Pantalla 2020-04-30 a la(s) 5 18 29 p  m](https://user-images.githubusercontent.com/6526545/80765163-f46c6d80-8b07-11ea-8577-03c5e4f87060.png)

**Comment by sebastiandedeyne** [comment]
Hi @RicardoRamirezR!

There were some CSS changes in the previous release. Republishing Mailcoach's assets should to the trick.

```
php artisan vendor:publish --tag mailcoach-assets --force
```

Although I assume you didn't, if you've customized Mailcoach's views you might need to apply some changes to the class names in `resources/views/app/campaigns/sent/summary.blade.php`. Here's an overview of what changed: https://github.com/spatie/laravel-mailcoach/pull/228/files#diff-2325a30bea9c2b1ebd5629631a330dd2

Happy upgrading! Feel free to ping back if you're still encountering issues.

**Comment by RicardoRamirezR** [comment]
Hi @sebastiandedeyne, thank you for looking at this.

I do have a 
```
php artisan vendor:publish --tag mailcoach-assets --force
```

in the `composer.json` `post-update-cmd`

![Captura de Pantalla 2020-05-04 a la(s) 8 49 59 a  m](https://user-images.githubusercontent.com/6526545/80973806-78af4100-8de5-11ea-98a8-9f40de9515ff.png)

I must say that I'm using Safari on Mac, the issue persist after upgrading to 2.11.3

**Comment by RicardoRamirezR** [comment]
Good day, please reopen this issue since is not fixed yet

**Comment by sebastiandedeyne** [comment]
Hi @RicardoRamirezR,

A few more things to try:

- Could you make sure your browser cache is cleared so the old CSS doesn't get loaded?
- Does `resources/views/vendor/mailcoach` exist in your project? (and could you confirm if it doesn't?)
    - If it exists and you haven't modified any views, you can delete this folder
    - If it exists and you've customized Mailcoach's views, you'll need to apply the HTML changes from the diff I shared above
- If you're still having issues: what exact versions of `spatie/laravel-mailcoach` and `spatie/mailcoach` are installed? Could you send over the `app.css` and full page source from the browser?

**Comment by RicardoRamirezR** [comment]
Hi @sebastiandedeyne 

He we go:

- Cache is cleared
- It does exists; I did changes on mails. Oh my God, I deleted it and now it shows the grid as it supposed to be

THANK YOU!
