### ISSUE TITLE
Campaign to 34,032 subscribers got stocked at 8047 out of 8048 🙄

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#174]
This is still since two hour ago.

![Captura de Pantalla 2020-04-30 a la(s) 6 26 03 p  m](https://user-images.githubusercontent.com/6526545/80768513-39949d80-8b10-11ea-8ecb-a16c90bb733f.png)

and SendCampaignJob is at Pending Jobs

**Comment by freekmurze** [comment]
Where there any failed jobs? Do you see any exception in the log?

In the outbox tab there should be a button display with which you can retry sending mails.

**Comment by RicardoRamirezR** [comment]
Nothing! What I did was to send another campaign  with the missing subscribers. 

(how to mark this as completed)
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/6526545/80813631-fda11d00-8b8f-11ea-98f4-f4de881d40f9.gif)

The campaign thinks it has only 8084 subscribers has only one pending...
![Captura de Pantalla 2020-05-01 a la(s) 9 38 40 a  m](https://user-images.githubusercontent.com/6526545/80813401-95ead200-8b8f-11ea-8055-aa2dcff50b79.png)

In failed there is only one job 
![Captura de Pantalla 2020-05-01 a la(s) 9 44 29 a  m](https://user-images.githubusercontent.com/6526545/80813826-64263b00-8b90-11ea-8700-f6a8a5dc8f41.png)

But it is:
![Captura de Pantalla 2020-05-01 a la(s) 9 45 38 a  m](https://user-images.githubusercontent.com/6526545/80813935-959f0680-8b90-11ea-8630-b08d23d296c4.png)

**Comment by freekmurze** [comment]
I don't know why, but it seems like there is an action missing in your config. 

I've just released v2.11.2 of Mailcoach which will use the default action class if none is specified in the config file. Before contuinuing, make sure to upgrade to that version.

To me it seems strange that your job is halted midway in creating campaign sends. It makes me think that timeout of a job is not correctly configured. Make sure the timeout in the horizon and queue config files is set high enough. See: https://mailcoach.app/docs/v2/package/general/installation-and-setup#install-horizon

Make sure when you change config value to run

```
php artisan config:clear
```

and restart horizon by either starting your machine or running `php artisan horizon:terminate`

If that extra button to restart a campaign on the `Outbox` tab of the campaign is not working, you should manually dispatch a `SendCampaignJob` and pass it your campaign to the constructor. (You could put this all in an artisan command). Rest assured that this job will not sent mails to the 8047 that already got the mail.

**Comment by RicardoRamirezR** [comment]
Thank @freekmurze, um, no action is missing; I've sent another campaign right away to the missing 27,083 subscribers yesterday without any problem. Any way thank you!

**Comment by shatterproof** [comment]
> I don't know why, but it seems like there is an action missing in your config.
> 
> I've just released v2.11.2 of Mailcoach which will use the default action class if none is specified in the config file. Before contuinuing, make sure to upgrade to that version.
> 
@freekmurze I'm using a customized config for Mailcoach in my app so additions to the internal config aren't automatically applied, which could explain how this happens.

Using default values for new additions to the config if nothing is specified would be great going forward since I've been needing to manually copy them over to avoid issues after updating.

**Comment by freekmurze** [comment]
In normal circumstances new config options are merged automatically for people that do not have them. I think in this instance it went wrong because we added a value to an array.
