### ISSUE TITLE
Github actions tests and auth.json

### ISSUE THREAD

**Issue by ziming** [spatie/mailcoach-support#177]
Currently my github action tests are failing as auth.json isn't in my project git repository.

Just wondering if you guys know how to deal with this issue.

**Comment by freekmurze** [comment]
You can set the content of auth.json as an environment variable
https://getcomposer.org/doc/03-cli.md#composer-auth

So you could but the auth.json content in a GitHub secret and use that in your action. Here's an example: https://github.com/spatie/freek.dev/blob/cbfce05037b35825afd5285e376ddb2513c0d826/.github/workflows/run-tests.yml#L45-L48
