### ISSUE TITLE
configuration option to use a different database connection

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#18]
I've chosen to install Mailcoach as a package of a very large app which uses multiple databases. I have a database dedicated to all things "comunication", this includes mail and notifications.

I would very much like the mailcoach tables to be created on that connection. I know I can publish the migration and make the change there. But packages usually require the connection to be set in the configuration as well so it knows to look for the model data on a different connection.

This is a very common configuration setting and I hope you can add it

Thank you

**Comment by freekmurze** [comment]
I'm going to hold off on this on for now. You can indeed publish the migrations and fix it there.

In a future release I might be able to allow to custom the models used. And you could then specify the connection on the custom model.

**Comment by vesper8** [comment]
@freekmurze I really wish you would reconsider and allow us to specify which database connection the tables are created on.. letting us use our own models is a step further but simply specifying the database connection would be a small but very welcome modification
