### ISSUE TITLE
Customization of Frontend

### ISSUE THREAD

**Issue by bluelupin** [spatie/mailcoach-support#180]
There should be some way to customize the header, footer, font, and color theme without editing the file in the vendor folder. It will make it consistent with the main Laravel application.

**Comment by freekmurze** [comment]
Run this command to publish all the views

```bash
php artisan vendor:publish --provider="Spatie\Mailcoach\MailcoachServiceProvider" --tag="mailcoach-views"
```

You can customise the published views to your liking.
