### ISSUE TITLE
Logged in User icon is not appearing in header.

### ISSUE THREAD

**Issue by bluelupin** [spatie/mailcoach-support#185]
We are facing strange problem after we upgraded the package today and published the views/vendor/mailcoach. We are not see logged in user icon to logout or change the settings. Please refer the screenshot.
![mailcoach-screenshot](https://user-images.githubusercontent.com/6630490/82156411-8dd1a880-9898-11ea-8a0a-128b68f126de.jpg)

**Comment by ingoldsby** [comment]
I had (have) that issue too. I did some testing installing mailcoach as a new application.

1. If I installed "using composer" https://mailcoach.app/docs/v2/app/installation/using-composer then it was fine and the settings cog was there
2. If I installed into an existing (newly created with auth) Laravel project, the settings cog was not there

**Comment by bluelupin** [comment]
I installed it in an existing Laravel project.  @ingoldsby  Your theory looks correct.

**Comment by freekmurze** [comment]
The cog icon with user management and mail config options is only used when you use the Mailcoach full app.

When installing the mailcoach package in an existing Laravel app, it is assumed that your app already has mail providers configured in the config file and you already have user management in the admin section of your app.

To get the configuration screens for the Mailcoach full app, you can copy them from the full Mailcoach app to your app.
