### ISSUE TITLE
"FIRST OPENED AT" takes the UTC time, not the local timezone

### ISSUE THREAD

**Issue by w3bleads** [spatie/mailcoach-support#189]
PHP: 7.4.6
Laravel: 7.11.0

Mailcoach 1-Click Application
Mailcoach: 2.11.8

In config/app.php timezone set America/Los_Angeles

Campaign->Statistics->Opens takes the UTC time, not my local timezone which is America/Los_Angeles

![1](https://user-images.githubusercontent.com/65088207/82276170-8f34cb00-9995-11ea-8a94-99c8ba398b9a.PNG)
![2](https://user-images.githubusercontent.com/65088207/82276176-92c85200-9995-11ea-9183-05ae1e279612.PNG)
Thanks

**Comment by riasvdv** [comment]
All dates and times are shown in the same timezone, we've recently had some fixes on the feedback packages (they were not using the correct timestamps)

If updating the feedback packages doesn't work, could you elaborate some more on which dates & times you expect to see? That might help us solve the issue you're having

**Comment by w3bleads** [comment]
Updating to "2.13.0" version not resolve a problem
Campaign->Statistics->Opens->"FIRST OPENED AT" show by UTC time, but I set in config/app.php "America/Los_Angeles" timezone (UTC-7)
Others all dates and times work correctly. 
And I am using SES if its help.

**Comment by w3bleads** [comment]
Some data from mailcoach_campaign_opens and webhook_calls tables
![1 PNG](https://user-images.githubusercontent.com/65088207/83194357-9902bf00-a149-11ea-8b6b-7494059bfd1b.png)
![Screenshot_1](https://user-images.githubusercontent.com/65088207/83194365-9b651900-a149-11ea-8e5a-16988ddb45f3.png)

**Comment by w3bleads** [comment]
it helps me,  but is it correct?
in SesEvent 
`public function getTimestamp(): ?DateTimeInterface`
`{`
`$eventType = strtolower($this->payload['eventType']);`
``
`    $timestamp = $this->payload[$eventType]['timestamp'];`
``
`//        return $timestamp ? Carbon::parse($timestamp) : null;`
`    return $timestamp ? Carbon::parse($timestamp, 'UTC')->setTimezone('America/Los_Angeles') : null;`
`}`

**Comment by riasvdv** [comment]
I've released a new version of laravel-mailcoach-ses-feedback (2.2.2) that takes into account the app's configured timezone, let me know if that fixes your issue!
