### ISSUE TITLE
add possibility to protect UI through a middleware instead of a guard

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#19]
Since all my Laravel projects are pure API I usually don't have an internal user login and instead I protect sensitive routes with a 6 digit unique PIN using a custom middleware. This is how I access things like Telescope, Log Viewer and Horizon.

I would very much appreciate if it was possible to protect Mailcoach with a middleware

Thank you

**Comment by freekmurze** [comment]
Would it solve your problem if we allowed the middlewares on the routes be specified in the config file (like Nova does)?

**Comment by vesper8** [comment]
yes it would, but you would have to also disable the guard so it would use either a middleware or a guard to protect the routes

**Comment by freekmurze** [comment]
Early next week, I'll take care of allow the middleware to be specified in the config file

**Comment by freekmurze** [comment]
I've added a `middleware` key to the default config value starting from `v1.3.0`.

For older versions, simply add this to the `mailcoach.php` config file:

```php

    /*
     *  These middleware will be assigned to every Mailcoach UI route, giving you the chance
     *  to add your own middleware to this stack or override any of the existing middleware.
     */
    'middleware' => [
        'web',
        Spatie\Mailcoach\Http\App\Middleware\Authenticate::class,
        Spatie\Mailcoach\Http\App\Middleware\Authorize::class,
        Spatie\Mailcoach\Http\App\Middleware\SetMailcoachDefaults::class,
    ]
```

I believe overriding/extending the middleware and placing your own classes in this array can solve your issue. If not, let me know.
