### ISSUE TITLE
Custom replacers not working with custom mailable

### ISSUE THREAD

**Issue by funkdoobiest** [spatie/mailcoach-support#192]
Hi,

when I add a campaign with a custom mailable, my custom replacers are not working.
I do not know why, but this workaround helps me:

```
$campaign = Campaign::create()
            ->useMailable(MonthlyStatsMail::class)
            ->segment(ShouldSendMonthlyStats::class);

        $campaign->name = "Test";
        $campaign->subject = 'Test';
        $campaign->email_list_id = 2;
        $campaign->content($campaign->contentFromMailable());
        $campaign->mailable_class = null;
        $campaign->save();
```

I set the mailable to "null" after setting content and then it's working like expected.

PHP 7.4.5
Mailcoach 2.11.5

**Comment by riasvdv** [comment]
I've just added a test with a custom Mailable & Replacer and everything works as expected.

Could you give a little more context:
- what does your Replacer and custom Mailable look like?
- What's the content and what are you expecting to happen?

**Comment by ziming** [comment]
Just to check does replacer work when i am using $this->markdown instead of $this->view in my custom mailable?

**Comment by ziming** [comment]
@riasvdv Isn't there a still open PR on this? Waiting for it to get merged too :)

https://github.com/spatie/laravel-mailcoach/pull/225

**Comment by riasvdv** [comment]
Seems like that PR will indeed solve your issue, I'm closing this in favor for the PR. If the author can't work on it anymore we'll pick it up!

**Comment by jbraband** [comment]
The PR is ready for @riasvdv to review
