### ISSUE TITLE
Unlayer caches the template/content and shows it in every other view

### ISSUE THREAD

**Issue by jonaswouters** [spatie/mailcoach-support#196]
Since updating to the last version, updating any content seems to overwrite all templates and campaign content. 

The content is not actually saved to the database, but it uses the same cached HTML every time unlayer is used in a view.

**Comment by jonaswouters** [comment]
A little update. The Uncaught TypeError: unlayer.init is not a function only happened when you have a pi-hole running.  After disabling that, this problem stays. 

Any change/update anywhere to the template, is visible everywhere else.   You have to clear the cache to show the actual content/template.

**Comment by jonaswouters** [comment]
I did some investigating, and even though the correct template gets loaded via an XHR request, the first opened template gets loaded via unlayer.loadDesign().

Disabling turbolinks on templates and campaigns fixes this issue for me for now.  

```
                        <td class="markup-links">
                            <a data-turbolinks="false" class="break-words" href="{{ route('mailcoach.templates.edit', $template) }}">
                                {{ $template->name }}
                            </a>
                        </td>
```

**Comment by riasvdv** [comment]
Thanks for the research, I'll look into it this week!

**Comment by sebastiandedeyne** [comment]
Hey @jonaswouters,

Thanks for reporting and investigating! I tagged a new version of `laravel-mailcoach-unlayer` that fixes the Turbolinks compatibility issues.
