### ISSUE TITLE
Template controller ignores model configuration

### ISSUE THREAD

**Issue by adamthehutt** [spatie/mailcoach-support#199]
Similar to #198. 

TemplatesController::store() makes a direct call to Template::create(), ignoring the template model specified in the configuration. 

Happy to do pull requests for this kind of thing, but I'm not sure that's possible since the code is in a private repository...

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. If you want to fix this yourself, you can do so.

You can get access to the private mailcoach repo by clicking the "Configure GitHub access" button on this page: https://mailcoach.app/account

**Comment by adamthehutt** [comment]
Great, thank you. Will do!

**Comment by adamthehutt** [comment]
Okay, a pull request has been submitted: https://github.com/spatie/laravel-mailcoach/pull/241

**Comment by freekmurze** [comment]
Merged and tagged. Thanks!
