### ISSUE TITLE
404 in docs

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#20]
This link https://mailcoach.app/docs/package/general/docs/package/using-the-ui/authorizing-users

Clickable from this page https://mailcoach.app/docs/package/general/installation-and-setup

leads to a 404

**Comment by vesper8** [comment]
The correct link is: https://mailcoach.app/docs/package/using-the-ui/authorizing-users

**Comment by freekmurze** [comment]
Thanks, I've fixed this. 

Should you spot more typos, just clicked the "edit" link on top of the page to easily send a PR. 👍
