### ISSUE TITLE
Confirmation Page before actual unsubscribe

### ISSUE THREAD

**Issue by ziming** [spatie/mailcoach-support#200]
Hi,

You may recall some time earlier about having some strange Email List unsubscribe issues. It turns out that for those users in my mailing list, their email client tries to auto check the links in the email which includes triggering the unsubscribe link.

Hence although they did not want to unsubscribe, they keep getting unsubscribed automatically.

Hence I like to propose that the unsubscribe link have a confirmation page. Rather than automatically unsubscribe once the link get clicked (be it by a human or by the email client software by mistake)

Thank you.

https://www.sparkpost.com/blog/list-unsubscribe-give-subscribers-freedom-leave/

**Comment by connecteev** [comment]
It would be better if this would be a configurable option in Mailcoach.

**Comment by freekmurze** [comment]
Having it as a configurable option is a good idea. We'll also make the confirmable behaviour the default in v3.

Closing this now but we'll revisit this when creating v3
