### ISSUE TITLE
Update UI to use custom subscriber fields

### ISSUE THREAD

**Issue by ps-cyrano** [spatie/mailcoach-support#202]
I've added custom fields to the subscriber model via a migration and I've updated the views to reflect these fieds, but how do I update the controller action? 

E.g. the create action: 

The `CreateSubscriberRequest` returns only the first_name and last_name fields, how do I add there my fields so they are stored?

Thanks for this great package

**Comment by freekmurze** [comment]
Currently it seems that this is hard to accomplish without having to write your own controller and letting the route point to that one.

In the next major version of the package we could add an action for this, so it's easily overridable and customisable.

Closing this for now.
