### ISSUE TITLE
Question on using Mailcoach for unlimited domains

### ISSUE THREAD

**Issue by jasonkaplan79** [spatie/mailcoach-support#205]
I have a technical question about the Mailcoach "unlimited domains" plan. 
How is that enforced? If I purchase mailcoach for one domain, I understand that during installation, there is a mailcoach API key used to get the latest code. But what is stopping someone from doing that and using the same downloaded code from mailcoach for additional domains? 
To be clear, I am not advocating that people do that - I love spatie's work and am a fan. Just curious if the domain checks happen during email sending? Will any emails we send will be "gated" by spatie / mailcoach before they get sent? On a technical level how is this enforced?
Thanks and I cant wait to use this product!

**Comment by freekmurze** [comment]
Currently there are no technical checks in place. You should pick the right license though to be in order legally.

If we see abuse, we might add checking code.
