### ISSUE TITLE
Campaign never stops "sending" status

### ISSUE THREAD

**Issue by beberlei** [spatie/mailcoach-support#208]
![Screenshot_2020-06-05 Campaigns Mailcoach](https://user-images.githubusercontent.com/26936/83903226-091ecf80-a75e-11ea-9dd3-5e45067a4d92.png)

I cant seem to find out why this "sending" status never goes away. 1 e-mail seems to be unsent, but never gets sent (for days now).

**Comment by goaround** [comment]
Try to raise the timeout for the send-campaign queue. If the job times out, it will stay like you described it

**Comment by beberlei** [comment]
@goaround any pointers how that is done? I don't usually use Laravel only for Mailcoach.

**Comment by goaround** [comment]
In `config/horizon.php` I created a supervisor just for the queue `send-campaign` and there you can raise the timeout

Here is my supervisor:

```
            'mailcoach-send-campaign' => [
                'connection' => 'mailcoach-redis',
                'queue' => ['send-campaign'],
                'balance' => 'auto',
                'minProcesses' => 1,
                'maxProcesses' => 3,
                'tries' => 3,
                'timeout' => 60 * 60,
            ],
```

Be sure to remove the queue `send-campaign` from the default `mailcoach` supervisor

**Comment by riasvdv** [comment]
@goaround his solution should work! Thanks

@beberlei You could also check Horizon to see what went wrong with the send campaign job. If it's something other than a timeout please open a new issue

**Comment by beberlei** [comment]
@riasvdv can you explain what "checking horizon" entails? I have no clue

**Comment by riasvdv** [comment]
You can access horizon at https://your-mailcoach-domain.com/horizon and get information on the queues

**Comment by beberlei** [comment]
@riasvdv alright, then I think i have the bug. During attempting to send an email it fails, and the failure reason is stored, but that fails with a database column length error:

![Screenshot_2020-06-26 Horizon - Failed Jobs](https://user-images.githubusercontent.com/26936/85842511-1b5dbd80-b7a0-11ea-92ab-2eec3fefb546.png)
