### ISSUE TITLE
Webview on different url like S3 

### ISSUE THREAD

**Issue by bluelupin** [spatie/mailcoach-support#209]
There is need of running Mailcoach on a secure server behind the VPN/firewall. The public URL for webview will not be accessible. There should be a provision to deploy review on different URL, for example, S3 bucket. It could be a simple job that can copy HTML file on some different storage disk.

**Comment by freekmurze** [comment]
This is something that is not supported by Mailcoach itself, but with a little knowledge of Laravel, you can take care of this yourself.

Listen for the event that is fired when a campaign has been sent. Using that event you can get to the html of the sent campaign and you can do whatever you want with that html.
