### ISSUE TITLE
Ability to track open and clicks? can't found the route and controller

### ISSUE THREAD

**Issue by davidstefando** [spatie/mailcoach-support#21]
Hi,

I saw on the documentation
https://mailcoach.app/docs/package/working-with-campaigns/tracking-clicks
It has click & open tracking. But when I look down into the code, I can't find corresponding controller 
Spatie\Mailcoach\Http\Controllers\TrackClicksController

Is there any change on the codebase, or am I miss something?

I'm using spatie/laravel-mailcoach v1.2.2

**Comment by freekmurze** [comment]
The docs were outdated, I've updated them now.

In an easier version of mailcoach it would take care of tracking opens and clicks by itself. In the current version the email service provider takes care off that.

My apologies for the confusion.
