### ISSUE TITLE
No Campaign Stats are seen - Opens, clicks, etc do not get registered

### ISSUE THREAD

**Issue by connecteev** [spatie/mailcoach-support#211]
>_Note that this is a copy of https://github.com/spatie/laravel-mailcoach/issues/253 as I'm not sure what is the appropriate repo to report issues like this (I am finding more as I dig into Mailcoach). Please advise where I should report issues and/or close the other one. Thanks for your work on this package._

**Steps:**
- Set up mailcoach using the steps at https://mailcoach.app/docs/v2/package/general/installation-and-setup
- Once set up, go to http://127.0.0.1:8000/mailcoach
- Create a test email list and campaign
- Go to http://127.0.0.1:8000/mailcoach/campaigns/5/delivery
- Hit "Send Now" and confirm the send by clicking "Send 2 emails"
- You get redirected to http://127.0.0.1:8000/mailcoach/campaigns/5/summary
- Emails get sent (most of the time..but that's a different issue)
- Go to the your (or your recipient's) email and open it from gmail (or your email client).
- Refresh the page at http://127.0.0.1:8000/mailcoach/campaigns/5/settings - the statistics still show 0 opens.
- As recipient, click on the links in the email
- Refresh the page at http://127.0.0.1:8000/mailcoach/campaigns/5/settings - the statistics still show 0 opens, 0 clicks, 0 unique clicks, 0 everything.

There clearly is a bug here.

![test2   Mailcoach](https://user-images.githubusercontent.com/64816/84539294-fe0cf780-aca7-11ea-9558-129e9ca43b9e.png)

**Comment by freekmurze** [comment]
We'll continue the conversation at the laravel-mailcoach repo
