### ISSUE TITLE
Error: "Division by zero" error page on sending a new campaign

### ISSUE THREAD

**Issue by connecteev** [spatie/mailcoach-support#212]
>_Note that this is a copy of https://github.com/spatie/laravel-mailcoach/issues/252 as I'm not sure what is the appropriate repo to report issues like this (I am finding more as I dig into Mailcoach). Please advise where I should report issues and/or close the other one. Thanks for your work on this package._

**Steps:**
I just installed mailcoach as a package and tried to send some test campaigns.

Steps:
- Go to http://127.0.0.1:8000/mailcoach/campaigns/5/delivery
- Hit "Send Now" and confirm the send by clicking "Send 2 emails"
- You get redirected to http://127.0.0.1:8000/mailcoach/campaigns/5/summary

with this error (note that about 20% of the time the error is not seen, no idea why)
Note that the majority of the time, the campaign emails do get sent, despite the error page.

```
Facade\Ignition\Exceptions\ViewException
Division by zero (View: /Users/kp/backend_laravel/vendor/spatie/laravel-mailcoach/resources/views/app/campaigns/sent/summary.blade.php)
http://127.0.0.1:8000/mailcoach/campaigns/5/summary
```
Screenshot:
![🧨 Division by zero backend_laravel vendor spatie laravel-mailcoach resources views app campaigns sent summary blade php ](https://user-images.githubusercontent.com/64816/84538578-c05b9f00-aca6-11ea-993d-0254720fe4b3.png)

**Comment by freekmurze** [comment]
We'll continue the conversation at laravel-mailcoach.

**Comment by electronick86** [comment]
@freekmurze , can you tell me where can I follow this discussion? I have the same problem.

**Comment by freekmurze** [comment]
This problem has already been fixed in the latest version. Just run composer update to pull in the fix 👍

**Comment by electronick86** [comment]
Thank you @freekmurze . Just had to php artisan view:clear ;-)
