### ISSUE TITLE
Images not showing in Campaign email 

### ISSUE THREAD

**Issue by Elandlord** [spatie/mailcoach-support#213]
Hi,

Yesterday, we bought Mailcoach, so that we could integrate it into an existing Laravel project. After a couple problems with Redis and other configuration files, I managed to get it to work. Interesting stuff!

Everything seems to be working fine, however, images I added in a Template are not showing up when sending an e-mail. They are working when I try to preview it.

![image](https://user-images.githubusercontent.com/5966835/84770630-2e220680-afd8-11ea-898b-9c9a8bee6bfc.png)

After sending, this is what's left:

![image](https://user-images.githubusercontent.com/5966835/84770667-42660380-afd8-11ea-99ff-0fdd3998ff45.png)

I'm using SendGrid as a mailer, and Unlayer as the Template editor. I have followed the installation instructions for the Unlayer editor, as listed on: https://mailcoach.app/docs/v2/package/customizing-the-editor/unlayer. I'm running this on my local machine (macOs).

Is this a known problem, any pointers to where the problem might be?

Thanks in advance!

**Comment by freekmurze** [comment]
What is the path used in the broken image?

**Comment by Elandlord** [comment]
https://ci6.googleusercontent.com/proxy/3poPivFLQn9DKtJ9HypDfHR-hYguqwrZ1I_WXumt1A1BPLP3LX6WpmEH8F1-L63-tLqWu20ZnJKI_rEXHZvpxmtsg41DUWHOwE0ax2boC1gZc24pxTRjx1GGmkU=s0-d-e1-ft#http://allesinbeweging.test/storage/3/conversions/bikker-terras-image.jpg

I see it references the local URL, surely that seems to be the problem?

I was unaware of this. I figured the uploads were stored in the database.

**Comment by Elandlord** [comment]
I can confirm this is not an issue. I've deployed my project to a server and got the images to work. 

Thanks!
