### ISSUE TITLE
jobs table not found

### ISSUE THREAD

**Issue by philsam** [spatie/mailcoach-support#218]
@freekmurze  I'm getting a lot of this in my log files. Please help me resolve

Base table or view not found: 1146 Table 'mailcoach.jobs' doesn't exist (SQL: select * from `jobs` where `queue` = default and ((`reserved_at` is null and `available_at` <= 1592804014) or (`reserved_at` <= 1592803924)) order by `id` asc limit 1 for update) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mailcoach.jobs' doesn't exist (SQL: select * from `jobs` where `queue` = default and ((`reserved_at` is null and `available_at` <= 1592804014) or (`reserved_at` <= 1592803924)) order by `id` asc limit 1 for update) at /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)

**Comment by freekmurze** [comment]
It seems like you aren't using Horizon / Redis for queues. Please refer to the installation instruction on how to set that up.
