### ISSUE TITLE
In mailcoach admin show a small warning when not running in production

### ISSUE THREAD

**Issue by beberlei** [spatie/mailcoach-support#221]
It is currently not visible when you run your mailcoach instance in "local" environment instead of "production". The Mailcoach admin could show a small error when this happens.

**Comment by freekmurze** [comment]
Maybe we could add this to the footer. @riasvdv could you take a look at this?

**Comment by riasvdv** [comment]
![image](https://user-images.githubusercontent.com/3626559/86216300-1cb32f80-bb7e-11ea-9955-b7da5e65ab76.png)

We'll now (2.19.3) show a label in the footer when your environment isn't set to production, or debugging is on
