### ISSUE TITLE
Error Import Subcriber After Update To Last Version!

### ISSUE THREAD

**Issue by willyw2k** [spatie/mailcoach-support#222]
Hi , Im got Error Import Subcriber After Update To Last Version 

![image](https://user-images.githubusercontent.com/11731303/85941451-56512400-b94d-11ea-9652-e5d8b0335a5f.png)

![image](https://user-images.githubusercontent.com/11731303/85941444-46394480-b94d-11ea-92b7-7a2ba10fe063.png)

**Comment by mbardelmeijer** [comment]
Hey @willyw2k -- have you restarted Horizon (queue worker) after updating to the latests version?

**Comment by willyw2k** [comment]
@mbardelmeijer  yes, im already restart the horizon 

![image](https://user-images.githubusercontent.com/11731303/85988822-d0e77580-ba19-11ea-856b-b8316e026069.png)

![image](https://user-images.githubusercontent.com/11731303/85988772-bf05d280-ba19-11ea-8325-7dca8278bba5.png)

**Comment by willyw2k** [comment]
Already Solved , Thanks @freekmurze @mbardelmeijer

**Comment by riasvdv** [comment]
@willyw2k Could you share what the solution was? So others might benefit from it if they come across this issue?

**Comment by willyw2k** [comment]
@riasvdv its wrong setting in my end im adding app folder in .gitignore

**Comment by riasvdv** [comment]
Ok! Closing this then
