### ISSUE TITLE
Too easy to forget to Save in Unlayer editor

### ISSUE THREAD

**Issue by jeffjacobsen** [spatie/mailcoach-support#223]
1 - Make changes to a Campaign email on the Content tab
2 - Forget to click Save Content at the bottom
3 - Click on the Delivery tab to send myself a Test email
4 - Go back to the Content tab and realize my changes are gone

It would be helpful to have a modal to warn me to save changes before leaving the Content edit tab

**Comment by freekmurze** [comment]
Agreed, we'll have to improve on this.

**Comment by riasvdv** [comment]
This is fixed in the 1.1.2 version of (https://github.com/spatie/laravel-mailcoach-unlayer/commit/41563055342836b46416d557f4fd898eb7dfa41c)! It will now ask you to confirm when you haven't saved any changes yet.
