### ISSUE TITLE
Installing on Forge

### ISSUE THREAD

**Issue by timoladoyinbo** [spatie/mailcoach-support#225]
Hi, I'm trying to install as a package using the git repository feature offered on Forge but I'm getting an issue with authentication. Please what's the best way to add my credentials for it to work without having it in my version control?

Thanks.

**Comment by freekmurze** [comment]
I suggest you place an `auth.json` in the composer home directory like described in our docs.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/483853/87431846-7d635300-c5e7-11ea-8574-441b60b35890.png">

https://mailcoach.app/docs/v2/package/general/installation-and-setup

**Comment by timoladoyinbo** [comment]
Thanks for the response. I have done that already, that is putting the auth.json in the home directory but still, get the same issue. I want to avoid putting it in the composer directory of the project as I'll be forced to include this in version control because of the automatic deploy.

**Comment by freekmurze** [comment]
In normal circumstances the home directory of composer is not equal the home directory of the user. If in your case it is, I would suggest configuring composer to use another home directory that is not version control.

**Comment by timoladoyinbo** [comment]
Thanks for the response. I think that might actually be the case here, I'll give it a try.
