### ISSUE TITLE
How to debug Unlayer error "The HTML is not valid"?

### ISSUE THREAD

**Issue by christophrumpel** [spatie/mailcoach-support#227]
Is there a good way to debug this Unlayer template error?
`The HTML is not valid (DOMDocument::loadHTML(): error parsing attribute name in Entity, line: 402).``

Is there a way to check the code when using the template editor?

**Comment by freekmurze** [comment]
Answered via Telegram.

**Comment by christophrumpel** [comment]
Yes, thanks again. For everyone else: You cannot see the code of the email without a paid version of Unlayer.
