### ISSUE TITLE
Can I use predis as a substitute for PHP Redis?

### ISSUE THREAD

**Issue by jmichaelterenin** [spatie/mailcoach-support#228]
Laravel 7
php 7.4
Purchased MailCoach
Order confirmation #14146359
brett @ explore.com

I've installed predis and set the REDIS_CLIENT=predis in the .env file
Tested a single email campaign, and the job just spins and says it's preparing. Laravel horizon dashboard  doesn't indicate any jobs in the queue.

Is there anything else I need to do to use predis, or is it just not possible?

**Comment by freekmurze** [comment]
Mailcoach relies on Laravel for connecting Redis. If something goes wrong there it's probably either:
- something wrong on your end (did you clear the config cache?)
- something wrong in Laravel (unlikely, but possible)

Could you test your setup by creating an app of your own, using predis there, and check if you can queue a job there.

Closing this for now, as I highly suspect this isn't a problem with Mailcoach itself.

**Comment by jmichaelterenin** [comment]
Ok, just wanted to confirm that predis could be used, thank you! I did clear the config cache. I'll keep working on it.

**Comment by jmichaelterenin** [comment]
It's a predis issue: `SELECT` failed: NOAUTH Authentication required. [tcp://127.0.0.1:6379] in the error log file. All the links I'm finding on this is related to using phpredis. If someone stumbles across this thread and can provide some insight, I'd greatly appreciate it.

**Comment by jmichaelterenin** [comment]
@freekmurze I was able to figure it out, as I had set a password for predis for security reasons on our main website, and had to do the same for the Laravel 7 install. For those that stumble upon this error, the missing/incorrect credentials are why this error comes up.
