### ISSUE TITLE
html tag (strong) not closed in view files

### ISSUE THREAD

**Issue by MianSaleem** [spatie/mailcoach-support#23]
Hello,

I have published views for the package and found that `strong` tag is not closed properly in `alreadyUnsubscribed.blade.php`, `subscribed.blade.php` & `unsubscribed.blade.php` view files of `resources/views/vendor/mailcoach/landingPages/` directory. The view file for `resources/views/vendor/mailcoach/landingPages/alreadyUnsubscribed.blade.php` is as following:

```
@extends('mailcoach::landingPages.layouts.landingPage', ['title' => 'Already unsubscribed'])

@section('content')
    <p>
        You were already unsubscribed from the list <strong class="font-semibold">{{ $emailList->name }}<strong>.
    </p>
@endsection
```

Instead closing the strong tag, it is being opened after `{{ $emailList->name }}` :(

**Comment by freekmurze** [comment]
Thanks for reporting this.

I've fixed this is the newly released `v1.2.3` 

Run `composer update` in a few minutes to pull it in.
