### ISSUE TITLE
Can I integrate MailCoach views inside my admin panel?

### ISSUE THREAD

**Issue by rajolm** [spatie/mailcoach-support#230]
Hi,
thanks for amazing work on this package (and other packages)

I want to ask if I can integrate MailCoach views inside my admin panel so it can be styled the same way as other pages inside my admin panel instead of visiting mailcoach built-in pages at /mailcoach route?
e.g. viewing campaigns and creating them using a page inside my admin panel
e.g. adding a page to edit campaigns and templates using Unlayer wysiwyg editor inside my admin panel?

can I do that?

**Comment by freekmurze** [comment]
> I want to ask if I can integrate MailCoach views inside my admin panel so it can be styled the same way as other pages inside my admin panel instead of visiting mailcoach built-in pages at /mailcoach route?

No, Mailcoach is meant to be used with the UI that we provide. I'm pretty sure that you could do some css hacks to override some of the styling, but we recommend using the UI that we ship.
