### ISSUE TITLE
Type of App\Mail\TransactionalTestMail::$theme must not be defined

### ISSUE THREAD

**Issue by kosmonowt** [spatie/mailcoach-support#232]
`(as in class Illuminate\Mail\Mailable) {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of App\\Mail\\TransactionalTestMail::$theme must not be defined (as in class Illuminate\\Mail\\Mailable) at /var/www/mailcoach/app/Mail/TransactionalTestMail.php:9)`

Hi there,
I am having that problem with 
- mailcoach 2.23.2, 
- php 7.4.3

When trying to send test mails.

Removing `string` in line 9 solves it.
Anyone else observing that problem?

**Comment by freekmurze** [comment]
Thanks for reporting this. We've already fixed this in the Mailcoach app skeleton.

https://github.com/spatie/Mailcoach/blob/2d1e7ed36a263360b425387ed19e24b438334a35/app/Mail/TransactionalTestMail.php#L13
