### ISSUE TITLE
Monaco and Unlayer

### ISSUE THREAD

**Issue by electronick86** [spatie/mailcoach-support#234]
Hi!

Could you tell me if it should be easy to use Monaco and Unlayer, and based on the user, switch the editor?

Thanks in advance!

**Comment by riasvdv** [comment]
Using both at the same time is not recommended, Monaco saves templates in raw HTML, but Unlayer uses its own JSON structure. You can't edit a campaign that's made with Unlayer in Monaco and vise-versa.
