### ISSUE TITLE
Error when adding mailgunFeedback route

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/mailcoach-support#236]
If I add `Route::mailgunFeedback('mailgun-feedback');` to my `RouteServiceProvider` as per [the instructions](https://mailcoach.app/docs/v2/package/handling-feedback/mailgun) I get `InvalidArgumentException: Attribute [mailgunFeedback] does not exist.`. I add it in the `map()` method as that's where `Route::mailcoach` is as well. Is this the correct place?

**Comment by riasvdv** [comment]
- Are you on the latest version of `laravel-mailcoach-mailgun-feedback`?
- Does it work if you put it in the `boot` method of your `RouteServiceProvider`?

**Comment by joostvanhoof** [comment]
I'm on `2.2.0` which I think is the latest? Looking back at my logs I now think that it tried to call the route before the package was fully installed and loaded on my production server. I'll monitor this closely and reopen this if it pops up again. Sorry if this was a mistake on my end!
