### ISSUE TITLE
Supression / Blacklist support

### ISSUE THREAD

**Issue by leeovery** [spatie/mailcoach-support#24]
Hey,

To keep subscribers from being emailed accidentally it might be an idea to implement a suppression/blacklist. 

A subscriber can unsubscribe from a list, but still get emails from other lists. This is desired and expected behaviour.

But if the user wants to unsubscribe from ALL lists, this would be a good use case to blacklist them, which means no matter which lists they are on, they won't receive emails.

Think of the user who feels angry for some reason and unsubscribes from the list, under the impression that they won't get any further emails. But without realising it they are on another list and as such a few days later receive another email! At this point they would (understandably) report the mail as spam, hurting the IP reputation. Having an "Unsubscribe from all future emails" link under the current unsubscribe link inside the email html would be a nice feature to have.

Just a thought.

Lee

**Comment by freekmurze** [comment]
For Mailcoach each list is separate from each other. So there isn't any behaviour that goes across all those lists.

You could implement the wanted behaviour like this in your own projects.

```php
Subscriber::where('email', $email)->each(fn(Subscriber $subscriber) => $subscriber->unsubscribe());
```

You could but that code somewhere in a controller of your own. You could add a [placeholder](https://mailcoach.app/docs/package/advanced-usage/creating-custom-placeholders) `blacklistUrl` that links to that controller.

(untested code, but you get the idea)

**Comment by vesper8** [comment]
@freekmurze It's pretty typical when clicking the unsubscribe button in a newsletter to be given the option to unsubscribe from this list or all lists.. Like with everything we can handle that ourselves, but I too would like to see support added for this feature to the core in the future.

**Comment by leeovery** [comment]
Thinking on this I might have implemented it like:

```
Subscriber -> Subscription -> EmailList
           -> Subscription -> EmailList
           -> Subscription -> EmailList
```

Subscriber is essentially the user record and holds the email and user details, like name etc.

A Subscriber has many Subscriptions, which have the relationship with the EmailList entity.

At least with this way the person in real life is represented via a single entity in the system which more closely resembles the real world. And that person has _subscribed_ to 1 or more _lists_

My two cents :) Im sure this was considered and discarded.

**Comment by freekmurze** [comment]
In an early version of the package we had it set up that way. But we decided to keep it very simple and let a subscriber belong to only one email list.

**Comment by leeovery** [comment]
Hey,

I keep coming up against issues relating to not having any type of suppression list or block list.

I feel that unsubscribing a subscriber upon receiving a bounce or complaint isn't quite enough. It would be trivial to accidentally resubscribe that user, which we really don't want to do.

Once they complain or we register a hard bounce we should really be hard-blocking that email in our system so we don't email them again, regardless of other settings or which list we are sending to.

My own thoughts are as follows (and I'm going to build this myself but honestly, it would be a decent addition to Mailcoach, IMO)...

On registering a bounce or complaint event, we add the email to a new DB table called `mailcoach_suppression_list`. 

We then ensure that the subscriber associated with the feedback is also unsubscribed on any other list(s) they might be on for good measure (based on the shared email).

Then we add behaviour to the abstract parent Segment so that any email addresses on the suppression list are NEVER emailed, regardless of other settings. All child Segments would inherit this behaviour so its impossible to email them.

I don't think it would be a complicated thing to add. I will be adding this in my own little Mailcoach wrapper which I've been hacking on. But as I said, at the very least, it's worth some further consideration. Email laws are fickle, especially in the US, and accidentally emailing people that have complained is dodgy ground.)

Lee

**Comment by vesper8** [comment]
I agree with all you've said @leeovery and absolutely want the same thing in my application so if you could please share your code here or somewhere that would be great. It's of utmost important that a user that's complained or that meant to fully unsubscribe never gets the chance to be emailed again whether through their error or ours.

@freekmurze This is another reason why it would be great if you could add the code to Github as a private repository so that we may actually submit PRs to help you improve this product.

As a side note, I saw Sendy being referenced a few times as being the inspiration behind this project which is a huge improvement in many ways, but just wanted to point out that Sendy does support both a suppression list as well as a blocked domain list. Clearly Sendy has had years and years to mature so it's normal that it has more features and I have no doubt that Mailcoach will see many new features added over time which I'm excited about. I think this one is a pretty important one given the strictness on emailing with the GDRP and other privacy laws.

**Comment by freekmurze** [comment]
> @freekmurze This is another reason why it would be great if you could add the code to Github as a private repository so that we may actually submit PRs to help you improve this product.

I'd like to have that too, but I still have to figure out a good, cost effective, way to do this.

Regarding blacklists: it seems that you are using mailcoach in a way that all email lists and campaigns are being sent for one company. I can also see Mailcoach being used where each email list belongs to another company (imagine a webdev agency that handles email lists for each of their clients). In that scenario, it makes no sense to unsubscribe someone from all email lists. I think that Mailchimp choose this route as well. 

That being said, I'll keep this request in mind and I'll consider changing my stance in the future. For now, if you want a blacklist, you'll have to handle that yourself.

**Comment by leeovery** [comment]
I’ve been working on a very simple api for mailcoach and will add the blacklist functionality to this “wrapper”. 

It could probably be a package. 

@freekmurze are you against that sort of thing being open sourced considering mailcoach is private?

I got it almost done over the weekend but realised I took a wrong turn somewhere. Going to refactor a bit to simplify. But it’s coming on nicely. 

There is another option. Most providers offer suppression lists. I would be very surprised if the mail providers that Mailcoach supports didn’t have support for this. So we could just push that list out to the provider and would be very safe. This is more for anyone else reading this, as another option.

**Comment by connecteev** [comment]
@freekmurze @leeovery 
Why not have an API to blacklist the subscriber from all (current and future) mailing lists? The API would be available for anyone that needs it.....agency or not. Agencies wouldn't use it. Also isn't the agency use-case less common anyway?

**Comment by freekmurze** [comment]
> It could probably be a package.
I don't mind open sourced add on packages for mailcoach, so go ahead.

> There is another option. Most providers offer suppression lists. I would be very surprised if the mail providers that Mailcoach supports didn’t have support for this. So we could just push that list out to the provider and would be very safe. This is more for anyone else reading this, as another option.
I'll investigate and update the docs around this soon.

**Comment by connecteev** [comment]
Also, love the @vesper8 and @leeovery idea to open this repo to paying subscribers, so we can all contribute PRs...it will make your job simpler @freekmurze , not to mention the package will mature a lot faster. I don't want to ever go back to Sendy again :) 

ps.  The idea of a package for a package sounds quite...tedious tbh.

**Comment by freekmurze** [comment]
> There is another option. Most providers offer suppression lists. I would be very surprised if the mail providers that Mailcoach supports didn’t have support for this. So we could just push that list out to the provider and would be very safe. This is more for anyone else reading this, as another option.

I'd like to keep the package as simple as possible right now. In my mind, it's now very clean with each lists being it's own world and not affecting each other. 

 I might change my stance on adding this feature in the future.

**Comment by freekmurze** [comment]
> Also, love the @vesper8 and @leeovery idea to open this repo to paying subscribers, so we can all contribute PRs...it will make your job simpler @freekmurze 

I'd also want this, but I have to figure out a way to do this, without having to pay GitHub for each person that wants access to the repo. I hope that's somehow possible.

>  I don't want to ever go back to Sendy again :)

Me neither.

> The idea of a package for a package sounds quite...tedious tbh.

I think that's ok if it's set up that way. We're already doing this for the feedback packages.

**Comment by connecteev** [comment]
@freekmurze have you considered GitLab? I think it has unlimited free contributors..

**Comment by freekmurze** [comment]
Nah, we defintely want to stick to GitHub for multiple reasons.

**Comment by vesper8** [comment]
I had no idea that Spark and Nova are doing this.. I mean.. paying Github for every user who's bought a license.. maybe ask Taylor how he did it?

Also.. considering both Spark and Nova are premium packages and there are tons of open-source packages for them on Github.. especially Nova.. I see no reason not to open source your API / Blacklist @leeovery ! I would definitely use it. That doesn't however mean that I don't hope some of these things get added to the core eventually, possibly as a user-submitted PR

**Comment by ryancwalsh** [comment]
> Also, love the @vesper8 and @leeovery idea to open this repo to paying subscribers, so we can all contribute PRs...it will make your job simpler @freekmurze , not to mention the package will mature a lot faster. I don't want to ever go back to Sendy again :)
> 
> ps. The idea of a package for a package sounds quite...tedious tbh.

I would definitely contribute to Mailcoach if pull requests were possible. One feature on my mind is the ability for Templates and Campaigns to use WYSIWYG like https://summernote.org/

**Comment by leeovery** [comment]
@ryancwalsh I believe that feature is in-hand already at Spatie 😉

**Comment by freekmurze** [comment]
Yeah, we're currently experimenting with various editors 

![photo_2020-02-03 14 58 57](https://user-images.githubusercontent.com/483853/73670324-518f8900-46a9-11ea-844b-44696cfd170f.jpeg)
