### ISSUE TITLE
Signed URLs in Mailcoach campaigns

### ISSUE THREAD

**Issue by connecteev** [spatie/mailcoach-support#241]
Maybe this functionality exists and is buried somewhere within the code and unit tests, but I read the Mailcoach documentation and watched all the videos and couldn't find an obvious way to do this.

I'd like to incorporate signed URLs in my emails. This means: if the subscriber (who has an account in my app) clicks on a secure link in the email, it would change their user preference or setting in the app, without needing to log into the web application. Laravel [offers this feature](https://laravel.com/docs/7.x/urls#signed-urls), and apparently it's also used by [OhDear](https://freek.dev/1713-using-laravels-signed-urls-to-add-action-links-to-emails)

What is the best-practice way to do this at the campaign-level in Mailcoach?

**Comment by freekmurze** [comment]
Mailcoach doesn't offer this out of the box. You might use a replacer for this. https://mailcoach.app/docs/v2/package/advanced-usage/creating-custom-placeholders

Your replacer might replace some kind of placeholder with a signed url generated by your replacer class.

**Comment by connecteev** [comment]
@freekmurze thanks for the tip.

How are you doing signed URLs in your newsletter, which seems to use Mailcoach? Are you using Replacers? The URLs look like this:

```
http://mailgun.spatie.be/c/xxxxxxxxAQAF-DtxoRVDhwaNL4j4VdlIpodK3fr8kcZm6DbgjQVsmFhjqtwAN5a3uIVlLUwbdWdtTDEIVuzjtFricqdAATVrMLCrTUxhuwnWmwR-xIGwBj-lbpBqvsZub9FOot2vEhHkRLjfR7vNB9ZmKm44mc
```

![image](https://user-images.githubusercontent.com/64816/92335121-dfb95c80-f048-11ea-978d-65c334f4e075.png)

**Comment by freekmurze** [comment]
Those aren't signed URLs generated by Laravel. Mailgun replaces all URLs in a mail in order to track opens/clicks.

**Comment by connecteev** [comment]
I see..
