### ISSUE TITLE
Idea: Geotracking where an email was opened from

### ISSUE THREAD

**Issue by connecteev** [spatie/mailcoach-support#244]
Apps like Mailtag do this. It would be good to know _where_ the email was opened from (IP, city, state, and country).

**Comment by freekmurze** [comment]
It's a good idea, but not many users are asking for this. 

If you need this fast, we'd accept a PR that adds this to laravel-mailcoach and the feedback packages.

**Comment by connecteev** [comment]
Not urgent, just sharing an idea
