### ISSUE TITLE
mailcoach.app/roadmap -  500 error

### ISSUE THREAD

**Issue by timothyasp** [spatie/mailcoach-support#245]
Sorry if this isn't the appropriate issue tracker for this.

Browsing [the roadmap](https://mailcoach.app/roadmap) from a recent email and getting a 500 error.  I'm sure you're aware, but just in case it slipped through, opening an issue.

Love the package btw.

**Comment by freekmurze** [comment]
Thanks for letting us know, we'll fix that soon!
