### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by Wulfheart** [spatie/mailcoach-support#246]
How does the mail tracking work? Is it GDPR-compliant?

**Comment by riasvdv** [comment]
Mail tracking works through the tracking of the providers, you can find more info in their respective GDPR policies:

Amzon SES: https://aws.amazon.com/compliance/gdpr-center/
Sendgrid: https://sendgrid.com/resource/general-data-protection-regulation-2/
Mailgun: https://www.mailgun.com/gdpr/
