### ISSUE TITLE
Improving ProcessSendgridWebhookJob with extra mysql index

### ISSUE THREAD

**Issue by electronick86** [spatie/mailcoach-support#249]
Hello,

I discovered (thanks Horizon) that the job ProcessSendgridWebhookJob tooks sometimes 3 seconds.

executing a `show processlist`on the mysql server,  realized that there was a lot of request with the pattern :
```sql
select * from `mailcoach_sends` where `uuid` = '0cf9ca26-40fd-4b11-a718-1917be9e6044' limit 1;
```
testing this request tooks 3 seconds.

I created an index on the column mailcoach_sends.uuid and the seepds instantly increased.

<img width="919" alt="Horizon_-_Metrics" src="https://user-images.githubusercontent.com/8201501/94373596-b56a3480-0106-11eb-8818-2b297c0ba7ac.png">

Do you thing that index should be used on every Mailcoach?

**Comment by freekmurze** [comment]
That's a good suggestion. I've added this by default on v3, which will be released this week.
