### ISSUE TITLE
Textarea not working in firefox

### ISSUE THREAD

**Issue by rocramer** [spatie/mailcoach-support#25]
The textarea is not working in Firefox. When opening a page the textarea looks like expected. If I'm clicking in, the textarea jumps to the right. After that the textarea has only a width of a few pixels.

I'm using Firefox Version 72.

Screenshot:

![Screenshot_2020-02-01 Settings Newsletter Mailcoach](https://user-images.githubusercontent.com/4487988/73594670-bf547d00-4510-11ea-94fe-7e6460f88b64.png)

**Comment by freekmurze** [comment]
Thanks for reporting, we'll fix this very soon.

**Comment by willemvb** [comment]
Strange, cannot reproduce on Firefox 72 in macOS Catalina or Windows 10. 
Which OS are you using?

**Comment by rocramer** [comment]
I'm using Ubuntu 19.10. In Chrome everything works fine. I'll try it later with a Windows machine.

**Comment by rocramer** [comment]
Tested it now: Problem exist as well on Windows 10 for Firefox but not for Chrome.

**Comment by rocramer** [comment]
Okay. Problem found. The https://languagetool.org/ extension causes the trouble. Wired because I'm using this plugin for years and I never experienced any broken input field until now.

**Comment by willemvb** [comment]
Good catch! After looking around for a while at this extension I found following issue: https://github.com/languagetool-org/languagetool/issues/2359

We also use CSS grid for layout, and I can confirm that they inject an element that breaks grid layouts. Hopefully it will be solved on their side in a few weeks!

**Comment by tiff** [comment]
@rocramer I'm one of the developers behind LanguageTool. I'm sorry for the trouble this might have caused. A fix is currently being rolled out. Thanks for using LT!
