### ISSUE TITLE
'419 page expired' when testing transactional email config

### ISSUE THREAD

**Issue by Vardkin** [spatie/mailcoach-support#250]
## Describe your issue
Thank you for releasing 3.0!
When testing transaction email configuration. `/settings/send-transactional-test-mail` returns `419 page expired`.
Transaction API key set using Sendgrid driver.

Edit: I noticed that is no CSRF token on the 'settings/send-transactional-test-mail'  page form.

---
## Health check:

**Environment**: production
**Debug**: OFF
**Horizon**: Active
**Queue** connection: OK
**Webhooks**: 0 unprocessed webhooks
**Schedule**: ran 0 minute(s) ago
**Default mailer**: smtp
**Mailcoach mailer**: null
**Campaign mailer**: null
**Transactional mailer**: null

## Technical details

**App directory**: /var/www/html
**User agent**: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
**PHP version**: 7.4.10
**MySQL version**: 5.7.25-google-log
**Laravel version**: 8.6.0
**Horizon version**: v5.1.0@09173d933845cb035eeee19ce8debf94b28bb717
**laravel-mailcoach version**: 3.0.0
**mailcoach-ui version**: 1.0.1

**Comment by Vardkin** [comment]
Confirmed that adding `@csrf` to `vendor/spatie/mailcoach-ui/resources/views/app/settings/transactionalMailConfiguration/sendTestMail.blade.php` on line 16 fixes this issue. Sadly, I do not see `spatie/mailcoach-ui` to make the PR.

**Comment by freekmurze** [comment]
I've just made the mailcoach-ui repo public

Feel free to make a PR that fixes this.
