### ISSUE TITLE
Dupliate query

### ISSUE THREAD

**Issue by vanthao03596** [spatie/mailcoach-support#254]
When visit email list subscriber i got duplicate query
![2](https://user-images.githubusercontent.com/34786441/95188048-2344e900-07f6-11eb-9122-f64b741a4669.png)

**Comment by freekmurze** [comment]
We'd accept a PR at laravel-mailcoach that fixes this.

**Comment by freekmurze** [comment]
Going to close this one for now as I considered it a bit of technical debt, but not something that makes the package unusable.
