### ISSUE TITLE
Hitting errors when trying to update via composer

### ISSUE THREAD

**Issue by LorenzoSapora** [spatie/mailcoach-support#256]
```bash
Invalid credentials for 'https://satis.mailcoach.app/packages.json', aborting.
https://satis.mailcoach.app could not be fully loaded, package information was loaded from the local cache and may be out of date
```

Credentials have not changed, they exist, and seem to be repeatable.

**Comment by yushkevichv** [comment]
Same problem. Write to email

**Comment by freekmurze** [comment]
Could you try to empty your composer cache and try again?

```
composer clear-cache
```

**Comment by LorenzoSapora** [comment]
Now it's hitting a hard error, and not continuing with updating composer.. hmm

```bash
$ composer update
Loading composer repositories with package information

In RemoteFilesystem.php line 746:
                                                                                  
  Invalid credentials for 'https://satis.mailcoach.app/packages.json', aborting.                                                                                
```

Double checked the key, it's exactly the same as in my purchases.

**Comment by AlexVanderbist** [comment]
Hi, sorry for the inconvenience. We've located and fixed the issue with the satis.mailcoach.app repository. Alternatively you can switch to the satis.spatie.be repository with the same authentication credentials.

**Comment by LorenzoSapora** [comment]
Is `satis.mailcoach.app` going to be depricated over `satis.spatie.be` at any point? Would it be wiser to use the spatie domain?

**Comment by freekmurze** [comment]
We will probably leave satis.mailcoach.app running for some time, but it's indeed better to use satis.spatie.be.  We will communicate this change with all Mailcoach users beginning 2021.

**Comment by LorenzoSapora** [comment]
Thanks for the clarification, Freek. I'll make the change.
