### ISSUE TITLE
First Login: A table was not found

### ISSUE THREAD

**Issue by surjithctly** [spatie/mailcoach-support#257]
After migrating database and creating user, I logged in, but it shows this error. 

I tried to rollback and then ran migration again but same error. 

Any help?

View error: https://flareapp.io/share/DPyLk86m#F61

![image](https://user-images.githubusercontent.com/1884712/95568208-95f5d480-0a41-11eb-86ab-616cb4f55db1.png)

**Comment by freekmurze** [comment]
It seems like the correct migration has not run. Did you publish the migration? How does your `database/migrations` directory look like?

**Comment by surjithctly** [comment]
I ran `php artisan migrate` this code. 

`database/migrations` look like this:

![image](https://user-images.githubusercontent.com/1884712/95569360-1cf77c80-0a43-11eb-9818-d8d3f7752dcd.png)

**Comment by riasvdv** [comment]
Did you clone https://github.com/spatie/mailcoach? You should use

`composer create-project spatie/mailcoach <project-name>` to have everything set up correctly.

**Comment by surjithctly** [comment]
Yes. I used that command only. 

Is this folder missing something? In local as well, I got the same files inside /migrations. 

This is database looks like: 

![image](https://user-images.githubusercontent.com/1884712/95569682-84153100-0a43-11eb-9077-36982f3c8869.png)

**Comment by riasvdv** [comment]
These commands should have ran after the create-project, you can try running them manually:

```
php artisan vendor:publish --tag mailcoach-migrations
php artisan vendor:publish --tag mailcoach-ui-migrations
php artisan mailcoach:prepare-git-ignore
php artisan mailcoach:execute-composer-hook
```

**Comment by surjithctly** [comment]
Oh I see. Its never documented, or not seen. Let me try it and get back to you.

**Comment by riasvdv** [comment]
> Its never documented

No, because they normally run automatically. What OS and PHP version are you on?

**Comment by surjithctly** [comment]
Its a Linode Basic Server, PHP 7.4. Managed by Serverpilot.

Anyway, After running your command, Asked to Install Redis, this also not shown any steps, so found another article. Now I can see the campaigns page finally.

**Comment by riasvdv** [comment]
You can see the requirements here https://mailcoach.app/docs/v3/app/general/requirements

**Comment by surjithctly** [comment]
Okay. Now getting the following error on Test Email. after SES setup.

How to fix this?

```
Error
Class 'Aws\Ses\SesClient' not found
https://mail.web3creative.com/settings/send-test-mail
```

![image](https://user-images.githubusercontent.com/1884712/95595134-783c6580-0a69-11eb-85dc-bf34ad977934.png)

**Comment by freekmurze** [comment]
Please refer to the Laravel docs to learn how to get started sending mails via SES.

**Comment by surjithctly** [comment]
Okay. Following Laravel Docs fixed it. But I still wonder why these info missing in docs. Even if its a link to them, if something is definitely needed to work, it should be mentioned right?

**Comment by surjithctly** [comment]
Also, I checked the debug page and saw this. Is it fine? or any changes required from my side? @freekmurze 

![image](https://user-images.githubusercontent.com/1884712/95649213-0ceea400-0afa-11eb-90c2-4cfe7011f9e8.png)
