### ISSUE TITLE
"Unable to locate publishable resources"

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#26]
`php artisan vendor:publish --provider="Spatie\Mailcoach\MailcoachServiceProvider" --tag="views"` (found at https://mailcoach.app/docs/package/working-with-lists/using-double-opt-in#customizing-the-subscription-confirmation-response) results in:

> Unable to locate publishable resources.
> Publishing complete.

I don't know if this is normal. It doesn't _feel_ like expected behavior because I don't see `/resources/views/vendor/mailcoach/` created or anything in it.

This is with 1.3.0 and also earlier versions too.

Thanks.

**Comment by freekmurze** [comment]
Thanks for reporting this.

The docs do not specify the right command.

Try this

```bash
php artisan vendor:publish --provider="Spatie\Mailcoach\MailcoachServiceProvider" --tag="mailcoach-views"
```

I'll update the docs 👍

**Comment by gosman** [comment]
> Thanks for reporting this.
> 
> The docs do not specify the right command.
> 
> Try this
> 
> ```shell
> php artisan vendor:publish --provider="Spatie\Mailcoach\MailcoachServiceProvider" --tag="mailcoach-views"
> ```
> 
> I'll update the docs 👍

Great product but docs leave a lot to be desired!!

**Comment by freekmurze** [comment]
If there are other things you see that can improved on the docs, let me know!
