### ISSUE TITLE
How to use with separate teams

### ISSUE THREAD

**Issue by georgeboot** [spatie/mailcoach-support#260]
We're looking at using Mailcoach for our app. We have multiple teams and each team can only see their own things.

How can we setup Mailcoach so that users of team 1 can only see lists and campaigns created by team 1, and vice versa for team 2?

**Comment by freekmurze** [comment]
This is currently not supported by Mailcoach itself. You could solve it by adding adding team_id columns on the mailcoach tables and with a middleware add global scopes.

We might add this functionality out of the box in Mailcoach v4.
