### ISSUE TITLE
Class 'Aws\Ses\SesClient' not found

### ISSUE THREAD

**Issue by leevigraham** [spatie/mailcoach-support#261]
## Describe your issue

Initial install with minimal customisation. Setup amazon SES following the docs here: https://mailcoach.app/docs/v2/app/mail-configuration/amazon-ses

Attempted to send a test email and got `Class 'Aws\Ses\SesClient' not found`

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/25124/95840124-83580400-0d8f-11eb-8acb-6a87389194f0.png">

---
## Health check:

**Environment**: prod
**Debug**: ON
**Horizon**: Inactive
**Queue** connection: OK
**Webhooks**: 1 unprocessed webhooks
**Schedule**: hasn't run
**Default mailer**: mailcoach
**Mailcoach mailer**: null
**Campaign mailer**: null
**Transactional mailer**: null

## Technical details

**App directory**: /home/forge/mailcoach.mytiki.life/releases/2
**User agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
**PHP version**: 7.4.5
**MySQL version**: 10.3.22-MariaDB-1:10.3.22+maria~xenial-log
**Laravel version**: 8.9.0
**Horizon version**: v5.2.1@8fbe70580d653e0f5c33ed9b151f6eebc16dfbf2
**laravel-mailcoach version**: 3.2.2
**mailcoach-ui version**: 1.0.3

**Comment by riasvdv** [comment]
Make sure you've followed Laravel's prerequisites for mailing with SES https://laravel.com/docs/master/mail#driver-prerequisites

**Comment by leevigraham** [comment]
requiring `aws/aws-sdk-php` sorted the issue I think.

**Comment by leevigraham** [comment]
Follow up question if it's not too much trouble… new to mailcoach / laravel… but is there a way to configure the mailers in the `mailcoach.php` config? I've set the values in the `config/mail.php` but I'm still being prompted.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/25124/95850225-3af31300-0d9c-11eb-95ea-d66f8604f7c3.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/25124/95850323-5eb65900-0d9c-11eb-89ba-08f3da9b83bf.png">

**Comment by freekmurze** [comment]
You can configure the mailers in `config/mail.php`
