### ISSUE TITLE
New install via 1-click DO has a lot of issues

### ISSUE THREAD

**Issue by jameslkingsley** [spatie/mailcoach-support#264]
## Describe your issue
I just installed Mailcoach via the 1-click setup in DigitalOcean, however, it has since had a lot of issues. Namely missing packages for SES, the editors don't work, the settings have UI bugs. I'm trying to fix the issues one by one manually but it's quite confusing and I'm not sure if I'm doing things right.

Is there an earlier version without these issues that I can completely re-install with?

---
## Health check:

**Environment**: production
**Debug**: ON
**Horizon**: Active
**Queue** connection: OK
**Webhooks**: 1 unprocessed webhooks
**Schedule**: ran 0 minute(s) ago
**Default mailer**: mailcoach
**Mailcoach mailer**: null
**Campaign mailer**: null
**Transactional mailer**: null

## Technical details

**App directory**: /var/www/html
**User agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
**PHP version**: 7.4.10
**MySQL version**: 5.7.31-0ubuntu0.18.04.1
**Laravel version**: 8.10.0
**Horizon version**: v5.2.1@8fbe70580d653e0f5c33ed9b151f6eebc16dfbf2
**laravel-mailcoach version**: 3.2.3
**mailcoach-ui version**: 1.0.3

**Comment by riasvdv** [comment]
> Namely missing packages for SES, the editors don't work, the settings have UI bugs. I'm trying to fix the issues one by one manually but it's quite confusing and I'm not sure if I'm doing things right.

It's a bit hard to help with this limited information, could you specify, preferably with screenshots or logs, what errors or bugs you're getting exactly?

**Comment by jameslkingsley** [comment]
I followed the instructions [in this video](https://mailcoach.app/docs/v3/app/installation/using-the-1-click-installer) and had the following:

- Attempts to send an email resulted in 500 error. After turning debug mode on, the error was due to missing the AWS PHP SDK package.
- Refreshing the Mail or Editor settings page showed all configuration fields for all options at once.
- Only the plain text area editor works - the Unlayer and Monaco editors don't load anything (blank div)
- The .env file is missing all of my configuration values (is this correct?)

I discovered that the Mailcoach v2 docs contain more info than the v3 ones, so I tried following those instructions and installing various packages but this ended up with duplicated database migrations.

**Comment by riasvdv** [comment]
> Attempts to send an email resulted in 500 error
Which 500 error? Could you share you logs with us? They are stored in storage/logs/laravel.log

> Refreshing the Mail or Editor settings page showed all configuration fields for all options at once.
> Only the plain text area editor works - the Unlayer and Monaco editors don't load anything (blank div)

This seems to point to a javascript error, could you take a look in your browser console if there are any and share a screenshot?

> The .env file is missing all of my configuration values (is this correct?)
Configuration you set in the UI is stored in the `config-mailcoach-app` folder

**Comment by jameslkingsley** [comment]
Sorry for the very delayed response.. we ended up going a different route entirely as some things changed in our project - and no longer have Mailcoach setup anywhere to test. Thanks for your help nonetheless!
