### ISSUE TITLE
Method toMailcoachFormat does not exist.

### ISSUE THREAD

**Issue by binaryk** [spatie/mailcoach-support#271]
Context: 

I followed all the steps to install v3.

I followed all steps to install unlayer. 

Tried to save my first template:
![image](https://user-images.githubusercontent.com/6833714/97780396-0d280f80-1b8d-11eb-88d3-d164e834f1a4.png)

![image](https://user-images.githubusercontent.com/6833714/97780361-d94cea00-1b8c-11eb-8df6-233e38427bce.png)

**Comment by binaryk** [comment]
Get rid of that method: 

![image](https://user-images.githubusercontent.com/6833714/97780450-6a23c580-1b8d-11eb-896e-dfe13a2de48c.png)

**Comment by binaryk** [comment]
Trying to edit the template and get this:

![image](https://user-images.githubusercontent.com/6833714/97780477-9f301800-1b8d-11eb-8023-ede4bccaf401.png)


I assume it may be related to the unlayer native library.

**Comment by riasvdv** [comment]
Can you check if your ad blocker is blocking Unlayer?

**Comment by binaryk** [comment]
It doesn't because it was working on the Unlayer sanbox itself.

**Comment by binaryk** [comment]
But it seems to be an issue only on mine, feel free to close the Issue.
