### ISSUE TITLE
Send campaigns not working

### ISSUE THREAD

**Issue by marju212** [spatie/mailcoach-support#272]
## Describe your issue
Campaign test mail is working fine but when I send the campaign the popup showing "send 1 mail" and will not close.

And the mail will not be sent. I also have unprocessed web hooks.

Im using postmark.

Rgds,

Marcus

---
## Health check:

**Environment**: production
**Debug**: OFF
**Horizon**: Active
**Queue** connection: OK
**Webhooks**: 25 unprocessed webhooks
**Schedule**: ran 0 minute(s) ago
**Default mailer**: mailcoach
**Mailcoach mailer**: null
**Campaign mailer**: null
**Transactional mailer**: null

## Technical details

**App directory**: /home/forge/bloppa.nu/releases/20201101075842
**User agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
**PHP version**: 7.4.11
**MySQL version**: 8.0.22
**Laravel version**: 8.12.3
**Horizon version**: v5.3.0@2d6e60011c3d58c86a6c38f03374167bb1232a0a
**laravel-mailcoach version**: 3.2.9
**mailcoach-ui version**: 1.0.3

**Comment by riasvdv** [comment]
Could you check horizon (bloppa.nu/horizon) and see if there are any failed jobs and if there are, what the exception tells you?

**Comment by marju212** [comment]
There aren't any failed jobs.

**Comment by marju212** [comment]
Sending mail from settings page is working fine.
Webhook test from postmark is ok.
Nothing found in the laravel logs.

**Comment by marju212** [comment]
Followed this guide, Horizon - Forge and Envoyer setup. 
https://medium.com/@driesvints/laravel-horizon-with-forge-and-envoyer-82a7e819d69f

**Comment by marju212** [comment]
Any idea how to solve this?

**Comment by riasvdv** [comment]
> Campaign test mail is working fine but when I send the campaign the popup showing "send 1 mail" and will not close.

So the popup never closes? Could you open your browser console and see if there are any errors after you click 'send'?

**Comment by marju212** [comment]
No, no errors. I did a composer update, all my mailgun settings was erased? 
Sometimes I got a message flashing Horizon not running - but its ok on the debug page.

**Comment by marju212** [comment]
Now I also got 'unauthorized' when sedning test mail. I used the Mailgun API credentials on the API security page.

**Comment by marju212** [comment]
I changed to postmarkapp, now test mail is working but still no campaign sent.

**Comment by riasvdv** [comment]
Did you install using the DigitalOcean one-click or in a project of your own?

It seems like something is wrong with your Horizon configuration

**Comment by marju212** [comment]
On my own - Forge and Envoyer setup.
And Horizon: https://medium.com/@driesvints/laravel-horizon-with-forge-and-envoyer-82a7e819d69f

**Comment by reefki** [comment]
@marju212 I think you should click on that "Send 1 mail" text, it's actually a button to confirm sending..

**Comment by marju212** [comment]
@reefki Thanks, now it works fine!
