### ISSUE TITLE
Unable to locate a class or view for component [icon-label]

### ISSUE THREAD

**Issue by MianSaleem** [spatie/mailcoach-support#275]
I tried to update mailcoach to v3 from v2 and getting the following error

```
InvalidArgumentException
Unable to locate a class or view for component [icon-label].
http://be-tec-net.test/lm/campaigns
```

Stack trace: https://flareapp.io/share/95J8ea0P

Can you please help me resolve this. Thank you

**Comment by freekmurze** [comment]
Did you run this command?

php artisan clear:views

**Comment by MianSaleem** [comment]
Yes, I did clear the views, cache and config too :(

**Comment by freekmurze** [comment]
Did you remove the cache in the bootstrap dorectory?

**Comment by MianSaleem** [comment]
yes, the cache were cleared too. I did again but still same error.

**Comment by freekmurze** [comment]
Then it's probably caused by something specific to your setup. Several users were able to upgrade.

When you find out what the problem was, please post it here to help others.

**Comment by riasvdv** [comment]
Did you republish the views? Make sure the views in resources/views/vendor/mailcoach are the latest

**Comment by MianSaleem** [comment]
@riasvdv Yes, it was the views. I was keep publishing the assets of thinking that these are views. Thank you very much @riasvdv & @freekmurze
