### ISSUE TITLE
Appending tags via import

### ISSUE THREAD

**Issue by mbardelmeijer** [spatie/mailcoach-support#277]
We've got the question for the ability to append tags via the import, instead of overwriting ("syncing") them. This is due to new lists that come in, but the existing tag is still relevant. I understand that this is client specific, so perhaps best to have this option per import.

I'm happy to give it a shot for implementation, but wanted to discuss the best way forward. I think we have 2 options for that:

1) Add a checkbox on the import action to allow the user to select the tags mode. This can be "append" (new default for safety?), and "replace".

2) We can add a column to the import list, where you can specify that per row.

3) Another option that i haven't thought about 😄

**Comment by freekmurze** [comment]
I think option 1) will be the simplest way. 👍  Thanks for your work on this.
