### ISSUE TITLE
SubscribedConfirmedEvent and other events

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#28]
https://mailcoach.app/docs/package/advanced-usage/handling-events seems incorrect because SubscribedConfirmedEvent does not exist (but UnconfirmedSubscriberCreatedEvent does).

Also (and maybe I should have opened a separate issue for this next question?), other mail campaign providers offer webhooks for the following events; I'm wondering how I can create listeners for these scenarios:

- Contact updated
- Contact email address changed (in case not handled by "Contact updated")
- Contact deleted
- Soft bounce (of this campaign for this contact)
- Hard bounce (of this campaign for this contact)
- Contact flagged the campaign as spam

Thanks!

**Comment by freekmurze** [comment]
For the contact updated events, you can listed for the events that eloquent itself fires for Subscriber.

Soft bounces are currently not handled by the package, we assume that the mail should receive in the end, or we get a hard bounce.

For handling a hard bounce and a complaint on spam, I've just added the `BounceRegisteredEvent` and `ComplaintRegisteredEvent` events in `v1.4.0`. I've added them to the docs: https://mailcoach.app/docs/package/advanced-usage/handling-events

I've also cleaned up the docs, removing any non existing events (thanks for reporting that).

**Comment by ryancwalsh** [comment]
Thank you!

I had never used Eloquent events before and had forgotten about them. https://laravel.com/docs/6.x/eloquent#observers is interesting.

I was able to run `php artisan make:observer MailcoachSubscriberObserver --model=\\Spatie\\Mailcoach\\Models\\Subscriber` but on second thought might not even need it for anything.

I definitely _will_ be using the new `BounceRegisteredEvent` and `ComplaintRegisteredEvent` events though!

**Comment by ryancwalsh** [comment]
I figured I'd post what I learned about AWS SES soft bounce events (and the difference between SES "events" and "notifications") in case it helps anyone else. 

### What "soft bounce" means in SES

https://github.com/awsdocs/amazon-ses-developer-guide/blob/ec08804/doc-source/sending-concepts-deliverability.md from 2019-09-06 says 

> "Soft bounce – A temporary email delivery failure. For example, the mailbox is full, there are too many connections (also called throttling), or the connection times out. Amazon SES retries soft bounces multiple times. If the email still cannot be delivered, then Amazon SES stops retrying it. Amazon SES notifies you of hard bounces and soft bounces that will no longer be retried. However, only hard bounces count toward your bounce rate and the bounce metric..."

Compare to Mailchimp https://mailchimp.com/help/soft-vs-hard-bounces/ 

> "If an email address continues to soft bounce in additional campaigns, the address will eventually be considered a hard bounce and cleaned from your audience. We'll allow seven soft bounces for an email address with no subscriber activity and up to 15 soft bounces for contacts with previous subscriber activity before converting a soft bounce into a hard bounce."

And https://sendgrid.com/blog/email-bounce-management/ 

> "We continue to attempt to send these messages for up to 72 hours until the message is delivered. If a message is continuously deferred for 72 hours, we convert these addresses to a block/deferral list.  (A deferral list a not a suppression list.)"

As [Freek said](https://github.com/spatie/mailcoach-support/issues/28#issuecomment-581114688), "Soft bounces are currently not handled by the package, we assume that the mail should receive in the end, or we get a hard bounce."

So if that's okay with you, then you're all set.

In my case, since I wanted my main (non-Mailcoach) database to have a note for every Mailcoach soft bounce, I needed to create my own custom `SesEventFactory` class which included `SoftBounce::class` within `protected static array $sesEvents`.

### The difference between SES "events" and "notifications"

Before I get into that, an additional factor is that in my case, I also use SES for my transactional emails from this same sender email address.

I'm now using https://github.com/spatie/laravel-webhook-client to process the webhook calls related to my SES transactional emails.

I duplicated a lot of code from https://github.com/spatie/laravel-mailcoach-ses-feedback/tree/1.2.0/src/SesEvents

Okay, now we'll move on to how I encountered the difference between events and notifications.

I wanted to disable Email Feedback Forwarding since I recently got ~80 "Delivery Status Notification (Failure)" emails from MAILER-DAEMON@amazonses.com after a Mailcoach campaign. It was annoying to get a barrage of errors like that.

In [2014, Sendy](https://sendy.co/forum/discussion/2855/delivery-status-notification-failure-hard-bounces-vs-soft-bounces/p1) said 

> disable 'Email Feedback Forwarding' in your Amazon SES account so that you won't receive emails like these as bounces and complaints will be automatically registered in Sendy when they happen.

I figured my own Mailcoach / custom system could handle the feedback automatically, too.

How to disable Email Feedback Forwarding in SES:

1. Visit SES (maybe something like https://console.aws.amazon.com/ses/home?region=us-east-1#verified-senders-email:)
1. Check the box of the sender email address
1. Click "View Details" > "Notifications" > "Edit Configuration"

It says:

> Enable email feedback forwarding to have Amazon SES send bounce and complaint notifications to you by email.
> 
> You can disable email feedback forwarding; however, if you don't configure a method of tracking bounces and complaints, Amazon SES will send bounce and complaint notifications to the email address in the Return-Path or Source field of your emails.

I learned the hard way *not* to point Amazon SES bounce and complaint notifications to the Mailcoach SNS endpoint; SES notifications and events are [not the same thing](https://forums.aws.amazon.com/thread.jspa?threadID=272810), and Mailcoach is currently not set up to handle notifications.

> Notifications differ from event publishing in a few important ways.
> 
> First, they differ in terms of their scope. You configure notifications for individual identities (email addresses or domains). If you send email from an identity that uses notifications, and that email results in a bounce or complaint, you receive a notification (that is, a message with the notificationType header) through the SNS topic that you specified for the sending identity. On the other hand, you configure event publishing at the configuration set level. Multiple sending identities can use the same configuration set to send email. If you send email from multiple identities, you can receive bounce or complaint event notifications (with the eventType header) through a common SNS topic.
> 
> Second, they differ in the number of notification types that are available. Identity-based notifications can only send notifications for bounces, complaints, and deliveries. You can use event publishing to send notifications for send, reject, delivery, bounce, complaint, click, open, and rendering failure events.
> 
> Third, they differ slightly in the amount of information they provide. For example, the event publishing version of the bounce notification includes some information about the email that caused the bounce—including the subject, headers, configuration set, and message tags—that is not included in an identity-based bounce notification.

My approach probably isn't the most elegant or efficient way, but I created a `SesNotificationFactory` that is very similar to https://github.com/spatie/laravel-mailcoach-ses-feedback/blob/1.2.0/src/SesEventFactory.php but points to classes that instead of being like `Spatie\MailcoachSesFeedback\SesEvents\SesEvent` use my abstract `App\Events\SesNotifications\SesNotification`.

A lot of my code feels like near duplication, which is unfortunate.

But here is an example of a difference. My `App\Events\SesEvents\Complaint` has:

```
public function canHandlePayload(): bool {
    return $this->payload[self::EVENT_TYPE] === self::THIS_EVENT_TYPE;
}
```

And my `App\Events\SesNotifications\Complaint` has:

```
public function canHandlePayload(): bool {
    return $this->payload[self::NOTIFICATION_TYPE] === self::THIS_NOTIFICATION_TYPE;
}
```

where `self::EVENT_TYPE` and `self::NOTIFICATION_TYPE` are defined in the abstract classes as 'eventType' and 'notificationType'.



So what I've done, and what I think seems to be working, is:

My `App\Providers\RouteServiceProvider` has:

```
Route::mailcoach(Routes::MAILCOACH); //https://mailcoach.app/docs/package/general/installation-and-setup
Route::sesFeedback(Routes::SES_FEEDBACK_MAILCOACH); //https://mailcoach.app/docs/package/handling-feedback/amazon-ses#adding-the-webhooks-route
Route::webhooks(Routes::SES_TRANSACTIONAL_EMAILS_CFG_SET_EVENTS, Routes::SES_TRANSACTIONAL_EMAILS_CFG_SET_EVENTS); //This one is for 'events' from the transactional emails Configuration Set. https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-retrieving-sns-examples.html
Route::webhooks(Routes::SES_SENDER_FEEDBACK_FORWARDING_NOTIFICATIONS, Routes::SES_SENDER_FEEDBACK_FORWARDING_NOTIFICATIONS); //This one is for 'notifications' (not Configuration Set events) for a specific sender email address. 
```

Notice those 2 last lines.



My `webhook-client.php` config file has 2 configs in the array.

The one for `Routes::SES_TRANSACTIONAL_EMAILS_CFG_SET_EVENTS` points to `\App\Jobs\ProcessTransactionalSesWebhookJob::class`, which extends `\Spatie\MailcoachSesFeedback\ProcessSesWebhookJob`.

The one for `Routes::SES_SENDER_FEEDBACK_FORWARDING_NOTIFICATIONS` points to `\App\Jobs\ProcessSesSenderNotificationsWebhookJob::class`, which also extends `\Spatie\MailcoachSesFeedback\ProcessSesWebhookJob`.

And I have SNS topics with "subscriptions" that point to the correct routes on my system.
