### ISSUE TITLE
Record clicks and opens data

### ISSUE THREAD

**Issue by reefki** [spatie/mailcoach-support#283]
I'm installing Mailcoach as a package and I'm trying to figure out how to get clicks and opens data from webhook, for example with Amazon SES, it returns an IP address for both events and link tags information for clicks.

This way I can get additional metrics on the campaign statistic like geolocation data by IP address and add subscribers to certain tags based on the link (with tags: `ses:tags="value"`) they are clicked.

There are `CampaignOpenedEvent` and `CampaignLinkClickedEvent`, but those don't have the payload data on the event properties so I tried to listen to the `WebhookCallProcessedEvent` event which contains the needed data, and I'm able to get the `Send` model with:

```
$payload = json_decode($event->webhookCall->payload['Message'], true);

if (! $messageId = Arr::get($payload, 'mail.messageId')) {
	return;
}

$send = Send::findByTransportMessageId($messageId);
```

It's fortunate for `CampaignClick` and `CampaignLink` because I can query them by comparing the link in the payload against the one stored in the database but no for `CampaignOpen`.

I think it would be a great feature addition for Mailcoach if it also stores the opens and clicks data into the `mailcoach_campaign_opens` and `mailcoach_campaign_clicks` tables because I believe most users also will be happy if they can know at least the IP address of people who click or open the campaign.

Thanks

**Comment by freekmurze** [comment]
Thanks for your suggestion. We might improve on this in the next major version.
