### ISSUE TITLE
Not seeing user menu

### ISSUE THREAD

**Issue by larsjanssen6** [spatie/mailcoach-support#284]
Hi spatie, 

Today I bought mail coach very happy with it. However when setting up mailgun I have to configure the signing secret. But, I do not see a menu at the top right so I cannot go to the page where this can be configured.

From the documentation:

<img width="1426" alt="transactional" src="https://user-images.githubusercontent.com/7254997/100520322-7fe0d680-319d-11eb-99d5-fb0b0fe8da05.png">

What I see:

<img width="1410" alt="Schermafbeelding 2020-11-28 om 17 09 33" src="https://user-images.githubusercontent.com/7254997/100520332-8c652f00-319d-11eb-8af9-c0c55fa3f66e.png">

Where is my user menu? Am I missing something here?

Thanks!

**Comment by freekmurze** [comment]
Hi @larsjanssen6,

we installing Mailcoach as a package in an existing Laravel app, we assume that you already have user management in your app.

To get that user menu, you can installing the Mailcoach full app using Composer: https://mailcoach.app/docs/v3/app/installation/using-composer
