### ISSUE TITLE
Tag mark invalid in Entity

### ISSUE THREAD

**Issue by AshPowell** [spatie/mailcoach-support#289]
## Describe your issue
Hi, 

So 2 issues, one is I'm getting this error when my HTML email contains the <mark> tag:
The HTML is not valid (DOMDocument::loadHTML(): Tag mark invalid in Entity, line: 285).

And then there's also 4 unprocessed webhooks, I don't understand why? There are no failed jobs and all jobs have been processed.

Thanks!

---
## Health check:

**Environment**: production
**Debug**: OFF
**Horizon**: Active
**Queue** connection: OK
**Webhooks**: 4 unprocessed webhooks
**Schedule**: ran 0 minute(s) ago
**Default mailer**: mailcoach
**Mailcoach mailer**: null
**Campaign mailer**: null
**Transactional mailer**: null

## Technical details

**App directory**: /home/forge/domain
**User agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
**PHP version**: 7.4.13
**MySQL version**: 8.0.22
**Laravel version**: 8.17.0
**Horizon version**: v5.6.0@4e21779357d1f1abc0282a940855be635bf4f1be
**laravel-mailcoach version**: 3.5.0
**mailcoach-ui version**: 1.1.0

**Comment by freekmurze** [comment]
Hi,

first issue: your HTML probably contains an error. Mailcoach protects you for using invalid HTML. Please lint your HTML, there  are many online services for this.

second issue: this is probably due to the way you configured Horizon. it's hard to debug without any extra info.

**Comment by AshPowell** [comment]
It gives me the line the linting is failing at - 
`<h1>Include your Business in our huge <mark>Black Friday Promotion</mark></h1>
`

There are no errors in that syntax as far as I'm aware?

Horizon has had no other configuration except the standard that comes with the package, have I missed something? I have one active daemon on forge that is running horizon, jobs have been completed and it all seems to be working fine, the only way I saw something seemed to be off is via the debug screen saying there are unprocessed webhooks.

**Comment by freekmurze** [comment]
I would let your html be linted by another service that might offer you more details around the error.

Our tests indicate that all webhooks are handled as expected. I'm assuming this has something to do with your particular setup. If there is anything that we should change in our code to avoid that problem, I'm open for a PR. 

Closing this PR as probably we don't need to make any code changes, but feel free to continue the conversation.

**Comment by AshPowell** [comment]
It seems DOMDocument::loadHTML() doesn't like html5 tags - it fails using `<mark>Text</mark>` and a bunch of other html5 tags such as footer etc.

**Comment by riasvdv** [comment]
Mail clients don't like those either, so it's best to stick to none of the newer tags

**Comment by AshPowell** [comment]
> Mail clients don't like those either, so it's best to stick to none of the newer tags

The majority of the popular mail clients display `<mark>` tags just fine - But that is a valid point.

Maybe a notice vs. a complete block would be better though
