### ISSUE TITLE
No user icon 

### ISSUE THREAD

**Issue by rocramer** [spatie/mailcoach-support#29]
There is no user icon in the top right corner. Other than that I can't get into the mail configuration. I tried the `/mailcoach/settings/mail-configuration` and `/mailcoach/settings/send-test-mail` endpoint and get a 404.

![Screenshot_2020-02-02 Campaigns Mailcoach](https://user-images.githubusercontent.com/4487988/73613892-50ebe980-45fa-11ea-8684-4ebac2e50572.png)

**Comment by freekmurze** [comment]
If you installed mailcoach as a package, there's no user management or email settings management. It is assumed that there is already user management elsewhere in you app and you use the Laravel config files to specify email settings.

If you need the users management / email settings provided by Mailcoach, use [the full app](https://mailcoach.app/docs/app/installation/using-composer). If you know your way around Laravel you could also copy those screens from the full app to the app where you installed Mailcoach as a package.
