### ISSUE TITLE
Is there a way to specify EmailList on a separate server?

### ISSUE THREAD

**Issue by AshPowell** [spatie/mailcoach-support#290]
So we have mailcoach up and running on one server, and it would be nice to use the package to subscribe users and work with lists from our main server.

So for example:
`
$emailList = EmailList::create(['name' => 'my email list name', 'ip' => '127.0.0.1']);
$emailList->subscribe('john@example.com');
`

This would be perfect - just not sure if it's possible?

**Comment by freekmurze** [comment]
This isn't possible out of the box.  What you could try to is use a custom `EmailList` model that uses a non-standard db connection. That db connection could point to the db on the other server.

**Comment by AshPowell** [comment]
Ok thank you
