### ISSUE TITLE
Suggestion for Single Sign On

### ISSUE THREAD

**Issue by csogilvie** [spatie/mailcoach-support#292]
Not sure where the best place to suggest items for the Roadmap might be, but have you considered the ability to allow people to set up Mailcoach Authentication to be based off of Laravel Socialite to enable organisations to authenticate off their Microsoft 365 details etc.?

**Comment by riasvdv** [comment]
Thanks for the suggestion, if you install laravel-mailcoach as a package in your own project, all authentication could be done using Laravel Socialite.

We'll look into it if we want to add this to the stand alone project in the future as well.
