### ISSUE TITLE
[Advise] Purging the mailcoach_sends table?

### ISSUE THREAD

**Issue by electronick86** [spatie/mailcoach-support#293]
Hello guys!

The bigger Mailcoach instance I have runs since this summer and I just see that the database dumps was quite big.
The biggest table of the `mailcoach_sends` which has ~27Mo rows into it.

Could you telm me whats could be the impact of purging this table with records older than X months? The `campaign_opens` and `campaign_clicks` are more 'valuable' as they allow me to segment based on the subscriber behaviour (ex: I some campaign are only sent to subscribers recently subscribed OR that open 1+ email in the last 60 days).

The problem is that if I remove the sends, the associated "clicks" and "opens" will be also deleted.

Do you have any advice with that? Thanks a lot!

**Comment by riasvdv** [comment]
You could try making the `send_id` nullable on the opens & clicks tables, and change the `on delete cascade` to `on delete set null`, which would allow you to delete the sends without affecting the opens & clicks.

I don't know exactly if this has any consequences in the UI of the app, but I don't think we use the relationship from open to send or click to send anywhere in the code.

Let me know how it goes and if you run into any issues and this could be a change we make by default for v4

**Comment by freekmurze** [comment]
Closing this as we're not going to handle this in the current version, but feel free to continue the conversion
