### ISSUE TITLE
Lang file typos

### ISSUE THREAD

**Issue by LorenzoSapora** [spatie/mailcoach-support#294]
Hey, I've noticed some English/German/Dutch typos, but can't seem to find them in the `spatie/mailcoach` or `spatie/mailcoach-ui` packages. Could you point me in the direction of the `de.json` and `nl.json` files?

I can see them in my package files, but I can't locate them on the repos themselves, so assuming they're pulled in from a vendor?

Thanks.

**Comment by riasvdv** [comment]
You can find them here https://github.com/spatie/laravel-mailcoach/tree/master/resources/lang
