### ISSUE TITLE
Unprocessed mailgun webhooks

### ISSUE THREAD

**Issue by Propaganistas** [spatie/mailcoach-support#295]
Hi

It seems all of **Mailgun**'s webhooks get processed, but their processed state isn't persisted, resulting in a skewed debug page. No fails or errors in Horizon.

![Schermafbeelding 2020-12-06 om 12 35 04](https://user-images.githubusercontent.com/6680176/101279023-8b488900-37bf-11eb-9443-6ff25c6ac179.png)

![Schermafbeelding 2020-12-06 om 12 36 04](https://user-images.githubusercontent.com/6680176/101279029-a1eee000-37bf-11eb-82a0-7695923fc87e.png)

![Schermafbeelding 2020-12-06 om 12 36 49](https://user-images.githubusercontent.com/6680176/101279040-ba5efa80-37bf-11eb-9e2e-f58c5d39333f.png)

**Comment by freekmurze** [comment]
If you already know where they should be persistent, send a PR. We'll investigate this soon.

**Comment by Propaganistas** [comment]
I don't know any of the internals of mailcoach. Looking forward to your investigation

**Comment by riasvdv** [comment]
Can you run a `composer info` in your project and see which version of `spatie/laravel-mailcoach-mailgun-feedback` you're on?

**Comment by Propaganistas** [comment]
The unprocessed webhooks all range from `2020-09-30` 'till now. Worth mentioning: at `2020-09-29` I performed the upgrade to v3.

The following versions are applicable:

At `2020-09-30`:
* `spatie/laravel-mailcoach`: 3.0.4
* `spatie/laravel-mailcoach-mailgun-feedback`: 2.3.0

Now:
* `spatie/laravel-mailcoach`: 3.5.0
* `spatie/laravel-mailcoach-mailgun-feedback`: 2.3.1

**Comment by riasvdv** [comment]
Those versions definitely include the functionality that sets the processed_at column, it's all tested functionality as well so there should be no issues.

Could you add a log statement after this line https://github.com/spatie/laravel-mailcoach-mailgun-feedback/blob/master/src/ProcessMailgunWebhookJob.php#L35 to verify that everything was executed?

And another log statement here: https://github.com/spatie/laravel-mailcoach/blob/master/src/Listeners/SetWebhookCallProcessedAt.php#L11 to see if the listener is called?

This should give a bit more info as where it goes wrong.

**Comment by Propaganistas** [comment]
Got something. My mailgun sending domain is not uniquely bound to mailcoach. Other application parts are using the same domain as well for regular transactional email such as password resets.

As a consequence of this setup, mailgun also sends webhooks to mailcoach for all other mails.
The webhook processor attempts to find a `Send` model but fails, so the job is early returned.

https://github.com/spatie/laravel-mailcoach-mailgun-feedback/blob/master/src/ProcessMailgunWebhookJob.php#L28

It's up for debate if a webhook should be considered as processed if no related `Send` was found...

**Comment by freekmurze** [comment]
> It's up for debate if a webhook should be considered as processed if no related Send was found...

I think we should indeed mark those as processed

**Comment by riasvdv** [comment]
Fixed in laravel-mailcoach-mailgun-feedback v2.3.2

**Comment by Propaganistas** [comment]
Thank you
