### ISSUE TITLE
Placeholders in Template not merged on sending campaign

### ISSUE THREAD

**Issue by SDJeff** [spatie/mailcoach-support#296]
## Describe your issue

I tested one campaaign and pulled in ::campaign.name:: and ::subscriber.first_name:: in the content.
But neither in the preview nor in the outbox the placeholders are replaced by the actual values.
I inserted the placeholders with the help of the editor.
What is wrong?

---
## Health check:

**Environment**: local
**Debug**: ON
**Horizon**: Active
**Queue** connection: OK
**Webhooks**: 0 unprocessed webhooks
**Schedule**: hasn't run
**Default mailer**: mailcoach
**Mailcoach mailer**: null
**Campaign mailer**: null
**Transactional mailer**: null

## Technical details

**App directory**: /home/vagrant/Code/mailcoach
**User agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
**PHP version**: 7.4.13
**MySQL version**: 5.7.32-0ubuntu0.18.04.1
**Laravel version**: 8.17.2
**Horizon version**: v5.6.0@4e21779357d1f1abc0282a940855be635bf4f1be
**laravel-mailcoach version**: 3.5.0
**mailcoach-ui version**: 1.1.0

**Comment by SDJeff** [comment]
Okay. The placeholders are not rendered in the preview or test mail. They are finally filled out after sending the campaign. 
### Improvement
Perhaps it is possible to fill the preview with the data of the first subscriber in the list to see a "real" preview. Thx. Problem solved. 

Please close the issue then!

**Comment by freekmurze** [comment]
I think using the first one might be confusing too. We're going to leave it as it is for now.
