### ISSUE TITLE
Sending Campaign again not running

### ISSUE THREAD

**Issue by SDJeff** [spatie/mailcoach-support#297]
## Describe your issue

I sent out the testmail with effort. But if i click "Send now" feedback said X Mails sent.

But neither in the JobQueue nor in the mailbox the mail to the recipients of the list appears.
In the overview you will not see the date for the outgoing mail of the campaign.

![image](https://user-images.githubusercontent.com/2220942/101280326-d3b87480-37c8-11eb-82dc-24ae5928754d.png)

---
## Health check:

**Environment**: local
**Debug**: ON
**Horizon**: Active
**Queue** connection: OK
**Webhooks**: 0 unprocessed webhooks
**Schedule**: hasn't run
**Default mailer**: mailcoach
**Mailcoach mailer**: null
**Campaign mailer**: null
**Transactional mailer**: null

## Technical details

**App directory**: /home/vagrant/Code/mailcoach
**User agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
**PHP version**: 7.4.13
**MySQL version**: 5.7.32-0ubuntu0.18.04.1
**Laravel version**: 8.17.2
**Horizon version**: v5.6.0@4e21779357d1f1abc0282a940855be635bf4f1be
**laravel-mailcoach version**: 3.5.0
**mailcoach-ui version**: 1.1.0

**Comment by riasvdv** [comment]
The campaign is still in draft, after you click the "send campaign" button you have to confirm, did you confirm?

**Comment by SDJeff** [comment]
Okay. Yes my fault. I closed the window and didn't recognized that i have to click the red button again. I was thinking the modal window was the confirmation that he sent out x mails already. Sorry. Please close!
