### ISSUE TITLE
Why "caching" config in files?

### ISSUE THREAD

**Issue by fibis** [spatie/mailcoach-support#298]
Is there a reason why the mailcoach config is cached and stored in files in the `config-mailcoach-app` folder? For deployments like on Kubernetes are stateless deployments always easier to handle. This is not possible when configuration files are written to the file system that need to survive a container restart.

**Comment by freekmurze** [comment]
The full app is meant to be used by users that don't want to tinker with the normal Laravel config. That's why we store it in a json file and don't work via the default config files.
