### ISSUE TITLE
Events need public properties or getters

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#30]
Related to https://github.com/spatie/mailcoach-support/issues/28#issuecomment-581114688, I think you accidentally set the properties to private instead of public in `BounceRegisteredEvent` and `ComplaintRegisteredEvent`.

I think either they need to be public or there needs to be a public "getter" function that exposes their value. 

Thanks.

**Comment by freekmurze** [comment]
Whoops, my bad, I've made those properties public in the newly tagged `v1.4.1`
