### ISSUE TITLE
Update Subscriber via API

### ISSUE THREAD

**Issue by AshPowell** [spatie/mailcoach-support#300]
Hi, 

Is it possible to update a subscriber via the API?

For example, updating tags, names etc. Reposting to subscribe results in an unprocessable entity response, would be nice to be able to update a subscribers details via the API too :)

**Comment by freekmurze** [comment]
This was added yesterday through this PR: https://github.com/spatie/laravel-mailcoach/pull/383 👍

**Comment by AshPowell** [comment]
Legend

**Comment by AshPowell** [comment]
Sorry for the notifications, any eta on the release?

**Comment by freekmurze** [comment]
It is already released in 3.7.0
https://github.com/spatie/laravel-mailcoach/releases/tag/3.7.0

**Comment by AshPowell** [comment]
Thanks, missed that one :)

With the docs not being updated yet could you give me a hint as to the URL structure to update a subscriber?

**Comment by AshPowell** [comment]
`Route::apiResource('email-lists.subscribers', SubscribersController::class)->only(['index', 'store']);
`

I may be wrong but looking at the routes it seems it doesn't have the new update method

**Comment by AshPowell** [comment]
Sussed it nvm
