### ISSUE TITLE
[false positive] Registered clicks on Sending, without any opens

### ISSUE THREAD

**Issue by wkhayrattee** [spatie/mailcoach-support#301]
Hello,
Just after I clicked on Send campaign, I see the system registered a click, without any opens.. and there could not have been any opens just after 2 secs delay.. I can confirm that as all the contact were internal members.

See screenshot:

![image](https://user-images.githubusercontent.com/7369626/102086617-ca1ab680-3e31-11eb-9e97-d5c29f27f19f.png)

**Comment by freekmurze** [comment]
Hi, Mailcoach just processes that webhooks that are sent by your email sending service. If those webhooks are sent seemingly too early, it might be best to content your email sending service.
