### ISSUE TITLE
Feature: Ability to create automated workflows

### ISSUE THREAD

**Issue by viezel** [spatie/mailcoach-support#31]
As Maiilcoach is a developer-focused app

Must web app has workflows for various jobs:
- lead warmer campaigns
- App tutorial
- Best practice
- Onboarding flows
- Winback (Notifications based on usage)

In the land of personalization and staying relevant for customers, we need to know if a user has completed step A, or clicked on link B. This is possible with Maiilcoach using link tracking, opening tracking and segments. 
It is much more effective to send emails with the right content to a specific segment rather than sending newsletters out to anymore. 

## Workflow builder Example 
Here is an example flow from Campaign Monitor:

![image](https://user-images.githubusercontent.com/312065/73630808-7824d400-4657-11ea-8a3a-58f5883a36f5.png)

## Inspiration for Requirements

The workflow builder uses a basic rule engine with conditions to plan out which emails a user/segment should receive. Typically you want to add conditions with either custom fields, segments or user interaction with an email, such as "user clicked at least 1 link". 
It would require MailCoach to create Emails in advance, and when building the Workflow.

- Laravel Workflow: https://github.com/brexis/laravel-workflow uses (https://symfony.com/doc/current/components/workflow.html)
- DotNet backend, but React based Builder: https://github.com/optimajet/DWKit (demo: http://demo.dwkit.com/admin?apanel=workflow&aid=VacationRequest)
- Another React based Workflow builder https://github.com/ram4git/workflow-builder

## Why build it?

Mailcoach has the potential of being much more than "just" a newsletter app. I can easily be the Laravel focused email platform for any type of business. Being able to build various kinds of emails supporting sales (leads), customer success (onboarding). And lets be honest, no one has filled this gap in the Laravel community yet. 

Competitors like Campaign Monitor, Mailchimp, etc have vast functionality, but most Laravel focused developers would have it all covered by using MailCoach with Workflows.

_Let me know what you think, and let's bounce back ideas on this matter_

**Comment by freekmurze** [comment]
Thank you for your suggestion.

We've considered this, but opted to start with only the email campaigns like you find them in Mailcoach now.

Adding a flow like this right, takes a lot of effort. Right now, there are no plans for this on the table. If Mailcoach does well commercially, we might add this in the future.

**Comment by viezel** [comment]
Sad to hear that @freekmurze. I wonder if the community can build a package to support this. Is it open for extension?

**Comment by freekmurze** [comment]
Sure, it's open for extension: you can publish every action and publish any view. But my feeling is that this is an entirely different use cause that can't be implemented well without making some breaking changes. 

Feel free to make an attempt though.

**Comment by ryancwalsh** [comment]
@viezel I think this could be awesome. 

I always loved the idea of https://www.activecampaign.com/ and https://www.mautic.org/ but was totally disappointed with them in practice.  Maybe Mailcoach (or an addon to Mailcoach) can offer those automated workflows.
