### ISSUE TITLE
If nothing has happened, don’t send the weekly summary

### ISSUE THREAD

**Issue by hanspagel** [spatie/mailcoach-support#33]
My first weekly summary was sent and all numbers are 0. I set up a bunch of lists, but people don’t subscribe to all lists on a regular basis. It’s good to know if a few people subscribed this week, but I don’t need the info that nothing happened. What do you think?

![IcVyTTsgsi](https://user-images.githubusercontent.com/1577992/73642583-36eded80-4672-11ea-87d9-c858515f37ca.png)

Mailchimp has daily or weekly summaries, but doesn’t send them in this case. I don’t know about other services.

**Comment by freekmurze** [comment]
Hi @hanspagel,

thanks for your suggestion.

To keep things simple, I'm going to leave it like it is. My guess is that most people want to get that mail, even though nobody subscribed for a week. The fact that nobody subscribed is also newsworthy for most imho.

You can however, turn off the this kind of mail on the email list settings screen (last option)

<img width="603" alt="image" src="https://user-images.githubusercontent.com/483853/73647513-ee3b3200-467b-11ea-9710-28e21ba3fc79.png">
