### ISSUE TITLE
Subscribe API for AJAX forms

### ISSUE THREAD

**Issue by hanspagel** [spatie/mailcoach-support#34]
With the predefined pages and the possibility to configure other URLs in the form Mailcoach is already very flexible and should work in most cases.

I’d love to see an API to subscribe users with AJAX though. I feel it improves the user experience to keep the context of the page when subscribing.

Leaving this here as a suggestion. If this feels out of scope for you, just close it.

**Comment by freekmurze** [comment]
> I’d love to see an API to subscribe users with AJAX though.

how would that look like?

**Comment by hanspagel** [comment]
I added this route to the project:

```php
<?php
// routes/api.php

use App\Http\Controllers\Api\SubscribeController;

Route::post('subscribe/{emailListUuid}', '\\'.SubscribeController::class)->name('mailcoach.api.subscribe');
```

And this custom Controller:

```php
<?php
// app/Http/Controllers/Api/SubscribeController.php

namespace App\Http\Controllers\Api;

use Spatie\Mailcoach\Enums\SubscriptionStatus;
use Spatie\Mailcoach\Http\Front\Requests\CreateSubscriptionRequest;
use Spatie\Mailcoach\Models\Subscriber;
use Symfony\Component\HttpFoundation\Response;

class SubscribeController
{
    public function __invoke(CreateSubscriptionRequest $request)
    {
        if (!$emailList = $request->emailList()) {
            return response()->json([
                'success' => false,
                'code' => 'list_not_found',
                'message' => 'Could not find the list.',
            ], 404);
        }

        if (SubscriptionStatus::SUBSCRIBED === $emailList->getSubscriptionStatus($request->email)) {
            return $this->getAlreadySubscribedResponse($request);
        }

        $subscriber = Subscriber::createWithEmail($request->email)
            ->withAttributes($request->subscriberAttributes())
            ->syncTags($request->tags())
            ->subscribeTo($emailList)
        ;

        return $subscriber->isUnconfirmed()
            ? $this->getSubscriptionPendingResponse($request, $subscriber)
            : $this->getSubscribedResponse($request, $subscriber);
    }

    public function getAlreadySubscribedResponse(CreateSubscriptionRequest $request): Response
    {
        return response()->json([
            'success' => false,
            'code' => 'already_subscribed',
            'message' => 'You were already subscribed to this list.',
        ], 409);
    }

    protected function getSubscriptionPendingResponse(CreateSubscriptionRequest $request, Subscriber $subscriber): Response
    {
        return response()->json([
            'success' => true,
            'code' => 'subscription_pending',
            'message' => 'We’ve sent you an email to confirm your subscription.',
        ], 202);
    }

    protected function getSubscribedResponse(CreateSubscriptionRequest $request, Subscriber $subscriber): Response
    {
        return response()->json([
            'success' => true,
            'code' => 'subscribed',
            'message' => 'You are now subscribed to the list '.$subscriber->emailList->name.'.',
        ], 201);
    }
}
```

**Comment by vesper8** [comment]
I believe @leeovery is working on an API wrapper which I hope he will release soon, he talks about it here https://github.com/spatie/mailcoach-support/issues/24#issuecomment-581273026

It would be great if this was added to the core but in the meantime, an open-source API will be a welcome alternative to having all of us create our own

**Comment by freekmurze** [comment]
Closing this for now, as right now we're not focusing on getting this sort of API in the core. I believe a 3th party package is the way to go for now.

I'll reconsider adding an API in the future since some people have already asked for this.

**Comment by leeovery** [comment]
I am hacking on it now. _Hopefully_, will have something done next week or so. Don't have much spare time.

It'll be opinionated but it'll be a good start at the very least. Then we can tweak it together :)

I'm also going to re-engineer my Laravel Newsletter package (which I'm renaming Contact-Front) to work with my Mailcoach API. So 2 abstractions  later ( 🙄) you'll be able to do:

```php
ContactFront::subscribe($email, $listNames, $attributes);
ContactFront::unsubscribe($email, $listNames, $attributes);
ContactFront::unsubscribeFromAll($email, $listNames, $attributes);
ContactFront::buildCampaign($email, $listNames, $attributes)
    ->scheduleToSendAt(now()->addDay())
    ->send();

...etc
```

That package is driver-based, so you can swap out the Mailcoach impl. with SendInBlue, or any others I add later.

Thinking Mailcoach API will use Passport in its simplest way. And will provide a webhook server so you can be notified over the wire when stuff happens.

**Comment by freekmurze** [comment]
@leeovery Thank you for all the work you put into this 👍

**Comment by leeovery** [comment]
Are you kidding? lol

I feel I owe Spatie so much this is the **VERY** least I can do!!! :)

But thank you.

**Comment by leeovery** [comment]
Ive pushed up my WIP here: https://github.com/leeovery/mailcoach-api

Feel free to submit issues with ideas etc. Im happy with the structure and flow.

You can subscribe to 1 or more lists, unsubscribe from 1 or more lists, update contact details, and send campaigns (now or scheduled).

Theres no auth yet, or events, or webhooks. 

Very much WIP
