### ISSUE TITLE
Repo is no longer letting me download via composer update

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#35]
This morning, I tried to run `composer require -vvv "spatie/laravel-mailcoach:^1.4.0"` to get all the latest changes.

I don't remember what the error message was, but I noticed that my `auth.json` file was missing. And I know I didn't delete it.

So I recreated it with my key and tried again.

I have also tried `composer clearcache`.

Then `composer require -vvv "spatie/laravel-mailcoach:^1.4.0"`  reaches:

```
Updates: spatie/laravel-mailcoach:1.4.2
  - Updating spatie/laravel-mailcoach (1.4.0 => 1.4.2): Downloading https://satis.mailcoach.app/dist/spatie/laravel-mailcoach/spatie-laravel-mailcoach-ba188cf6116be3ce8989cd1eaf09d2da1855e65a-zip-cb4d02.zip
Downloading (100%)Writing /home/vagrant/.cache/composer/files/spatie/laravel-mailcoach/0b2710f3c9da7c6e9be714076cd41b64ff0e2886.zip into cache from /home/vagrant/Code/myproject/vendor/spatie/laravel-mailcoach/699de2f72f844e44a184eb9ab2289634.zip
Executing command (CWD): unzip -qq  '/home/vagrant/Code/myproject/vendor/spatie/laravel-mailcoach/699de2f72f844e44a184eb9ab2289634.zip' -d '/home/vagrant/Code/myproject/vendor/composer/30f9fcd4'
    Update failed (Could not delete /home/vagrant/Code/myproject/vendor/composer/30f9fcd4: )
    Would you like to try reinstalling the package instead [yes]?
```

which is unusual. If I chose "No", I get:
```
Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  Could not delete /home/vagrant/Code/myproject/vendor/composer/30f9fcd4:
```

If I try again and choose Yes, I get:
```
  - Installing spatie/laravel-mailcoach (1.4.2): Executing command (CWD): git --version

    Cloning to cache at '/home/vagrant/.cache/composer/vcs/git-github.com-spatie-laravel-mailcoach.git/'
Executing command (CWD): git clone --mirror 'git@github.com:spatie/laravel-mailcoach.git' '/home/vagrant/.cache/composer/vcs/git-github.com-spatie-laravel-mailcoach.git/'
Enter passphrase for key '/home/vagrant/.ssh/id_rsa':
```
I don't use a key called `id_rsa`, so I don't know why I'm ever getting that prompt.

I try pressing Enter and then see:
```
Executing command (CWD): git config github.accesstoken
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Executing command (CWD): hostname
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+vboxHomestead+2020-02-03+1359
to retrieve a token. It will be stored in "/home/vagrant/Code/myproject/auth.json" for future use by Composer.
Token (hidden):
```
But this wasn't mentioned in your instructions and feels weird.

None of this was required in the past couple days; everything had been working.

I don't think anything changed on my side. It was working yesterday before I went to sleep and now isn't working when I woke up.

Any ideas?

Thanks!

**Comment by ryancwalsh** [comment]
I went ahead and created a token because https://stackoverflow.com/a/49518636/470749 says it's probably due to GitHub's API rate limit.

I also ran `export COMPOSER_PROCESS_TIMEOUT=600` because I hit a timeout limit.

Now when I run `composer require -vvv "spatie/laravel-mailcoach:^1.4.0"`, I still am prompted twice for `Enter passphrase for key '/home/vagrant/.ssh/id_rsa':`, and I press Enter both times and get:
```
[RuntimeException]
  Failed to execute git clone --no-checkout 'https://***:***@github.com/spatie/laravel-mailcoach.git' '/home/vagrant/Code/myproject/vendor/spatie/laravel-mailcoach' && cd '/home/vagrant/Code/myproject/vendor/spatie/laravel-mailcoach' && git remote add co
  mposer 'https://***:***@github.com/spatie/laravel-mailcoach.git' && git fetch composer && git remote set-url origin 'https://github.com/spatie/laravel-mailcoach.git' && git remote set-url composer 'https://github.com/spatie/laravel-mailcoach.git'

  Cloning into '/home/vagrant/Code/myproject/vendor/spatie/laravel-mailcoach'...
  remote: Repository not found.
  fatal:***@github.com/spatie/laravel-mailcoach.git/' not found
```

I apologize in advance since this smells like it's a problem local to me and not related to your repo (though, again, I have no idea what could have changed locally). But I'd LOVE hearing any suggestions. Thanks.

**Comment by ryancwalsh** [comment]
But none of my other Composer dependencies seem to be having problems, so maybe something _did_ happen specific to Mailcoach.

**Comment by freekmurze** [comment]
From our end we didn't change anything regarding our satis server (= the private composer server). There's nobody reporting similar problems. 

Can you require the package outside of your vagrant environment?

**Comment by ryancwalsh** [comment]
Thank you so much for your response.

Since then, I've been trying to use my partner's Mac to try to run it, but the Mac started having hardware problems 🤦‍♂️, so I was getting nowhere. 

Then what I did was **restart Windows** (the main computer where I've been working) and renamed `vendor` to `vendor2` (essentially deleting it by moving it away from its normal spot) and also `mv ~/.composer/cache ~/.composer/cache2`.

Then everything seemed to work. So I think this was one of those cases where Windows is just not a great developer environment, even when coding within an Ubuntu VirtualBox.

I apologize for the distraction. Thanks again.

**Comment by freekmurze** [comment]
No aplogies necessary, glad you got it working again 👍
