### ISSUE TITLE
[Feature] Allow spatie/laravel-tags instead of built in tagging system

### ISSUE THREAD

**Issue by LorenzoSapora** [spatie/mailcoach-support#36]
The tag system is lacking a certain amount of flexibility that the other tagging system allows for. For example tagging users country, user type, etc. The segmentation system would also need some minor tweaks to allow tags from different types.

**Comment by freekmurze** [comment]
spatie/laravel-tags is a big dependency. We probably aren't going to pull it in. Could you give examples of functionality you're now missing?

**Comment by LorenzoSapora** [comment]
- Tag types
Being able to categorise tags is useful for narrowing the focus. For example, in my current mailing system I have country, user tiers, user specific tags (what the user would like to see), and quite a few more. At the moment it's just a big pool of tags for that list.

- Translation
In `spatie/laravel-tags` we have json translations for tag names/slugs

- Segmentation
In the segmentation section, I can pick tags, but I'd like the option to pick from types. 
INCLUDE, country, netherlands
EXCLUDE, user_tier, > 3

I really like the segmentation, but feel very limited by the tagging system.

**Comment by freekmurze** [comment]
I'm thinking you could solve tag types and segmentation right now by just prefixing your tags.

Translations is indeed a tricky one.

Currently we'd like to keep mailcoach simple and don't have plans of extending the tag system. Should more users ask for this, I'll reconsider our stance.
