### ISSUE TITLE
Sentry package conflict

### ISSUE THREAD

**Issue by m1guelpf** [spatie/mailcoach-support#37]
Hey Spatie team (and thanks for building Mailcoach)!

I'm running into some issues while getting it running. Apparently, Mailcoach requires `ocramius/package-versions ^1.5`, which is locked at `^1.2.0` for everyone using the Sentry Laravel package. I understand this is not on your side, but keeping into account it's gonna be really difficult to get sentry to make the change (it's not a direct dependency, but a second-level dependency through `jean85/pretty-package-versions`), could you maybe consider supporting the older version if it provides all the required functionality?

Thank you!

**Comment by freekmurze** [comment]
Hi Miguel, thanks for bringing this to my attention.

I've lower the required version of that package to `^1.2.0`.

This change is available starting from mailcoach `v1.4.3`.

**Comment by cwhite92** [comment]
Never thought I'd see the day when @freekmurze DOWNGRADES a dependency 😱
