### ISSUE TITLE
Segment based on attributes?

### ISSUE THREAD

**Issue by goaround** [spatie/mailcoach-support#38]
I would like to let my subscribers choose a region where they live. I created an extra attribute `region` for that. Tags are in my option not a good fit for this purpose because a subscriber should only choose one region. Now I would like to send a newsletter with specific content for each region.

But here is my problem: I can only create Segements bases on Tags inside the App or by extending the `Spatie\Mailcoach\Support\Segments\Segment` with a databse query: https://mailcoach.app/docs/package/advanced-usage/segmenting-lists

I have about 20 regions. I've tried to create a Segment class and pass an individual region like `RegionSegment('norway')` but `Spatie\Mailcoach\Models\Campain::segment` only accepts a string and stores it inside database. My workaround is for now to create 20 Segment classes with only a short string diff. Thats feels wrong in my opinion.

I think it would be very helpful to support Segments based of attributes inside the App or at least inside as a Segment class.

**Comment by ziming** [comment]
Support this, I have a use case where I want to segment by the preference attributes they have in their UserProfile model such as month/year of birth, minimum deal size (amount), interested topics.etc

Certain email campaigns may only be sent to users whoose UserProfile had certain minimum game points as well

**Comment by freekmurze** [comment]
@goaround I'll see if I can improve on this.

Could you show me what you would do if you had total freedom? How would your `Segment` class look like?

**Comment by goaround** [comment]
Sure, I even added a secound attribute "frequency" because I would like to give my subscriber the choice between a daily & weekly newsletter:

```
<?php

class RegionFrequencySegment extends Segment
{

    public string $region = 'all';
    public string $frequency = 'daily';

	public function __construct( string $region = 'all', string $frequency = 'daily' ) {
        $this->region = $region;
        $this->frequency = $frequency;
    }

    public function description(): string {
        return 'Get a Segment based of Region and Frequency';
    }

    public function getSubscriptionsQuery( Subscription $subscription, Campaign $campaign ): bool
    {
        return Subscription::query()
            ->where( 'status', SubscriptionStatus::SUBSCRIBED )
            ->where( 'region', $this->region )
            ->where( 'frequency', $this->frequency )
            ->where('email_list_id', $campaign->emailList->id);
    }
}
```

I think even better would be using Tags and Attributes (including extra_attributes) inside the App to create Segments.

**Comment by riasvdv** [comment]
@goaround You can now pass an object to the `segment()` function on a campaign since 1.7.1, this allows you to instantiate the segment with values

https://mailcoach.app/docs/package/advanced-usage/segmenting-lists#using-an-instantiated-segment-object

**Comment by goaround** [comment]
@riasvdv awesome, thank you!
