### ISSUE TITLE
Accept custom attributes on CreateSubscriptionRequest?

### ISSUE THREAD

**Issue by goaround** [spatie/mailcoach-support#39]
As already mentioned here: https://github.com/spatie/mailcoach-support/issues/38 I've added custom attributes to my Subscribers. The next question is, how to accept these attributes on form requests to `/subscribe/`?

I think the only way is to extend `Spatie\Mailcoach\Http\Front\Controllers\SubscribeController` and replicate `__invoke` to accept a custom `CreateSubscriptionRequest` class with a custom `$request->subscriberAttributes()` function. Or is there a better way to handle this case?

**Comment by freekmurze** [comment]
I'm thinking that what you are describing is the way to go 👍
