### ISSUE TITLE
can it work with mailtrap for local testing?

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#4]
I am getting an error saying the mail configuration is missing, but what I would like to do is use mailtrap.io for local testing, can it work with it or it absolutely requires SES or Mailgun or Sendgrid?

**Comment by freekmurze** [comment]
In the UI you can select smtp and put in the details of your mailtrap.io connection there. Does that work for you?

**Comment by vesper8** [comment]
@freekmurze Yes it does work.

I guess the tracking ability doesn't work through Mailtrap though? I did a test and the open/click did not register and there is a broken image in the top left corner of the default template which I assume is the tracking pixel that isn't loading because it was sent from a local .test domain

Oddly I do believe https://github.com/jdavidbakr/mail-tracker email 'open' / link 'click' does work when testing via mailtrap so it must be failing for another reason here? I think a lot of people use mailtrap so it would be worth investigating

**Comment by vesper8** [comment]
Oh.. I can see why the unsubscribe is not working.. there is a typo `unsubscribeUrl ` !== `unsubcribeUrl `

**Comment by freekmurze** [comment]
We're probably not going to make adjustments for this. My feeling is that the open and click tracking is tested in the mailcoach testsuite and you shouldn't bother with testing that in your testsuite.
