### ISSUE TITLE
Statistics all show 0 (probable conflict of SES Configuration Sets)

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#40]
/mailcoach/campaigns/1/summary says 0 for everything even though I have opened the email (and downloaded the images) and clicked a link. I don't know what I'm doing wrong. 

I was very excited to see that my inbox received the campaign and that its links used my custom subdomain and then correctly bounced to my real domain (so I guess I configured SES and SNS correctly).

Does the fact that the "Send now" button worked mean that at least my Horizon and Redis are working?

I'm totally new to Horizon, so I wouldn't be surprised if I've done _something_ wrong. 

One problem I'm having with it is that I can't get the HorizonServiceProvider "gate" function to work because it never even gets called. I don't know why. I saw it get called yesterday, but today I haven't been able to get that to work, so I needed to ssh into my staging server and temporarily change my `.env` to say `APP_ENV=local` so that /horizon/dashboard would load without a 403 error.

But even after doing that temporary hack, everything I see in the Horizon dashboard is foreign to me; I don't know what activity I _should_ be seeing and how to know if anything is wrong.

I even manually ran:
```
php artisan mailcoach:calculate-statistics
Start calculating statistics...
Calculating statistics for campaign id 1...
All done!
```
But the stats still say 0.

Also, instead of using "Send now" for my Campaign 2, I tried to schedule it, but it still says "This campaign is scheduled to be sent at 2020-02-04 22:45." even though that time has passed.

So then I just ran:
```
php artisan mailcoach:send-scheduled-campaigns
Checking if there are scheduled campaigns that should be sent...
Sending campaign `2` (2)...
All done!
```

But now /mailcoach/campaigns/2/summary continually says "Campaign 2 is preparing to send to test" and there is no email in my inbox.

Ohhh that was because the Horizon process had stopped. So now Campaign 2 sent.

But now even with Horizon definitely running, the stats are still incorrect for both campaigns, even when I manually run:

```
php artisan mailcoach:calculate-statistics
Start calculating statistics...
Calculating statistics for campaign id 2...
All done!
```

I'd appreciate any hints! Thanks!

**Comment by ryancwalsh** [comment]
I just checked my tables, and these are empty: mailcoach_campaign_clicks, mailcoach_campaign_links, mailcoach_campaign_opens, mailcoach_send_feedback_items.

I looked up the chain from registerOpen() and see ProcessSesWebhookJob and earlier is MailcoachSesFeedbackServiceProvider.

I don't know what this line does, but sesFeedback camelCased sticks out to me since I've never seen that elsewhere:

`Route::macro('sesFeedback', fn (string $url) => Route::post($url, '\\' . SesWebhookController::class));`

I (just now) looked up what route macros are (https://www.atyantik.com/laravel-routes-improvised-routing/), and I searched my IDE for `Route::sesFeedback` and found it in App\Providers\RouteServiceProvider map().

And that's what https://mailcoach.app/docs/package/handling-feedback/amazon-ses#adding-the-webhooks-route says.

Ths is what I have:
```
    public function map()
    {
        $this->mapApiRoutes();
        $this->mapWebRoutes();
        Route::mailcoach(\App\Helpers\Routes::MAILCOACH); 
        Route::sesFeedback(\App\Helpers\Routes::SES_FEEDBACK_MAILCOACH); 
    }
```
And `\App\Helpers\Routes::SES_FEEDBACK_MAILCOACH` resolves to 'ses-feedback'.

And my mailcoach config array has:

```
'ses_feedback' => [//https://mailcoach.app/docs/package/handling-feedback/amazon-ses#setting-the-configuration-name-in-your-laravel-app
        'configuration_set' => 'mailcoach',
    ]
```
So I'm not sure what is wrong.

**Comment by ryancwalsh** [comment]
I found the webhook_calls table and see that it has exactly 5 records, and all of them have a message like "You have chosen to subscribe to the topic arn:aws:sns:us-east-1:024633319577:mailcoach.\nTo confirm the subscription, visit the SubscribeURL included in this message."

But my AWS SNS console already said Status Confirmed automatically (without me finding those DB records and visiting the special URL) just like your instructions said it would.

**Comment by ryancwalsh** [comment]
Oh shoot. I see a problem but don't know how to solve it. When I just took a closer look at the Mailcoach campaigns I received, I noticed that the subdomain of the links in the email body are the subdomain that my _other_ SES configuration set is supposed to use.

**Before Mailcoach existed, I was already using SES (and a configuration set and SNS) for tracking opens and clicks of my _transactional_ emails from my system.** I still want all of that to be possible.

How can I prevent whatever conflict is happening and get Mailcoach SES tracking to work?

**Comment by freekmurze** [comment]
@ryancwalsh I'm sorry you're having troubles with this. Thanks for the detailed explanation. 

@riasvdv Can you take a look at this?

**Comment by ryancwalsh** [comment]
When I look at https://console.aws.amazon.com/ses/home?region=us-east-1#configuration-set-list:, I see 4 configuration sets. 

Acelle and Mailbluster I could probably delete. But WalshSns is my main one for transactional emails. And now there is also "mailcoach".

![image](https://user-images.githubusercontent.com/2086493/73806845-a3630c80-4798-11ea-9ae1-1337221cee58.png)

I'm really surprised that somehow Mailcoach sent campaigns whose links (in the body of the email) used the "Engagement Tracking Domain" listed here under WalshSns. I can't figure out how that could have happened.

'WalshSns' is in my services.php config file under 'ses.options.ConfigurationSetName'.

So my understanding of this Configuration Sets page and how they work must be incorrect. 

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-configuration-sets.html says "You apply a configuration set to an email by including a reference to the configuration set in the headers of the email." That's what I thought, but that doesn't seem to be what's happening.

It feels as if my SES account somehow has WalshSns set as a _default_ configuration set.

But that doesn't make sense because I remember wanting to figure out how to do that [a year ago](https://stackoverflow.com/questions/52805117/is-there-a-way-to-specify-a-default-configuration-set-on-amazon-ses#comment94895824_52805117) and never figuring it out. I don't think there is any SES setting anywhere allowing for a default configuration set. I think if header doesn't specify one, none will be applied.

**Comment by riasvdv** [comment]
I think what's happening here is that Mailcoach is setting the configuration set header, but the SES driver of Laravel is overwriting it when the mail passes through because of what's set in your `services.php` file.

Is there any way you can verify this by removing the configuration from `services.php`?

**Comment by ryancwalsh** [comment]
Ok, I commented out 'WalshSns' and then ran Xdebug while using 'Send now' for a campaign, and I see the 'mailcoach' Configuration Set name where I'd expect:

![image](https://user-images.githubusercontent.com/2086493/73849933-cd4c1b80-47f8-11ea-84ae-323c7393c1a7.png)

![image](https://user-images.githubusercontent.com/2086493/73849943-d210cf80-47f8-11ea-9c5e-e69934c0528a.png)

![image](https://user-images.githubusercontent.com/2086493/73849951-d63ced00-47f8-11ea-8e05-7bc5d7167011.png)

And I check my inbox, and the Mailcoach campaign correctly uses the "mc" subdomain for its links. Great.

And when I uncomment 'WalshSns' and send a new Mailcoach campaign, the subdomain for its links is "eml". Incorrect.

When I originally set up my transactional SES emails and tracking, I was pretty sure that my location of 'services.ses.options.ConfigurationSetName' was custom made up by me and isn't conventional. I don't know how a Mailcoach dependency could be reading from there.

**I've been poking around like crazy and still haven't been able to figure out how there is any conflict at all in the code.** I appreciate any ideas. Thanks.

**Comment by ryancwalsh** [comment]
I used Xdebug all the way to the "send" function in SesTransport and see that 'mailcoach' correctly is set in the header even when my 'WalshSns' value exists elsewhere in my config. It's what I'd expect, because I wouldn't think there would be any way for my custom config to influence what header Mailcoach sets in SES:

![image](https://user-images.githubusercontent.com/2086493/73851924-54e75980-47fc-11ea-863d-8ea426b0372d.png)

But this is bonkers: in my inbox, I see the links using the "eml" subdomain, which indicates that SES used my WalshSns configuration set.

So that means (I think) something is happening within `$this->ses->sendRawEmail()` or later (e.g. remotely at SES) where the 'mailcoach' X-Configuration-Set header is being overridden. Ideas? Thanks.

**Comment by ryancwalsh** [comment]
I temporarily refactored SesTransport.php temporarily to more easily understand it and use Xdebug.

![image](https://user-images.githubusercontent.com/2086493/73853591-23bc5880-47ff-11ea-8612-7465c11405bc.png)
![image](https://user-images.githubusercontent.com/2086493/73853601-28810c80-47ff-11ea-8ef8-4061e08fe926.png)

`\Illuminate\Mail\TransportManager createSesDriver()` passes the whole 'services.ses' config array (which obviously includes my 'services.ses.options.ConfigurationSetName') to a new `\Aws\Ses\SesClient()`.

So now my 2 remaining questions are:

 1. Why would 'options.ConfigurationSetName' get used anywhere at all? I now see that ConfigurationSetName is an option within `sendEmail()` but haven't found documentation saying it's an option within the SesClient() constructor.
 1. Why would only _some_ of my transactional emails have been using WalshSns? So far, only the transactional emails that I _wanted_ to have the WalshSns header had them, and others didn't (i.e. everything was working as I wanted), which doesn't seem possible if `\Illuminate\Mail\TransportManager` is always inserting the whole config as an argument. (I wonder if my mails, which I sent via `Mail::later`, never relied on `\Illuminate\Mail\TransportManager`.)

In any case, my next step will be to try moving my WalshSns config value to a different place in the config (outside of 'options') and seeing if all of the following can be true simultaneously: Mailcoach sends with the appropriate subdomain and tracking, my tracking-enabled transactional emails send with the "eml" subdomain, and my tracking-disabled transactional emails send with no configuration set.

Fingers crossed that I can close this issue soon.

**Comment by ryancwalsh** [comment]
I think I've taken this as far as I can take it and now need your help, and I have ideas about how you can probably solve this.

First, I figured out what led me to create the config the way that I had it. https://laravel.com/docs/5.7/mail#driver-prerequisites (and still true in https://laravel.com/docs/6.x/mail#driver-prerequisites) gives that example of having 'services.ses.options.ConfigurationSetName'. 

**So I think you'll want to add a prominent note in https://mailcoach.app/docs/package/handling-feedback/amazon-ses about the consequences.**

Okay, now for testing my 3 scenarios after I removed 'services.ses.options' from my config:

 1. ✔ Mailcoach successfully sent an email with the correct "mc" subdomain. I haven't checked whether stats work yet since I'm working locally at the moment and don't have an ngrok endpoint in AWS, but I bet they'll work.
 1. ❌ Unfortunately my tracking-enabled transactional emails sent with _two_ X-SES-CONFIGURATION-SET headers:

```
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
X-SES-CONFIGURATION-SET: WalshSns
X-SES-CONFIGURATION-SET: mailcoach
```
 3. ❌ Unfortunately my tracking-disabled transactional emails sent with a mailcoach header instead of none:

```
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
X-SES-CONFIGURATION-SET: mailcoach
```

To solve # 2, **perhaps you could edit `AddConfigurationSetHeader` to first check for an existing X-SES-CONFIGURATION-SET and only add 'mailcoach' if X-SES-CONFIGURATION-SET doesn't already exist?**

I'm not sure how to solve # 3, but I think **maybe you could edit `MailcoachSesFeedbackServiceProvider`** such that `AddConfigurationSetHeader` only gets called if Mailcoach is the sender (and not for any other processes that want to use SES to send mail).

Thoughts?

**Comment by riasvdv** [comment]
Thanks for the very detailed investigation into this issue, I wasn't aware that the `services.ses.options.ConfigurationSetName` was an actual setting that Laravel uses.

We'll try to refactor the implementation of our ses package to overwrite that configuration when Mailcoach is the sender

**Comment by ryancwalsh** [comment]
@riasvdv Thanks. Could you please do it in a way that also allows me to have my own ConfigurationSetName set elsewhere (such as where I moved it, to `services.ses.ConfigurationSetName`, which is _outside_ of `services.ses.options`) since I don't actually want Laravel to be magically aware of my configuration set name since I want to attach it only to a subset of my transactional mails selectively.

I actually don't understand how my mails weren't _all_ (accidentally) getting that header added, given that I had used the conventional placement of the config.

But I think you understand my 3 goals (https://github.com/spatie/mailcoach-support/issues/40#issuecomment-582476627). I'd appreciate if your update to Mailcoach would make that possible.

Thanks so much! :-)

**Comment by riasvdv** [comment]
@ryancwalsh I've tagged a new version of Mailcoach (1.6.0) and the mailcoach-ses-feedback package (1.1.0), please let me know if these versions solve all your issues.

**Comment by ryancwalsh** [comment]
@riasvdv Thanks for your update. I'm trying right now but /mailcoach/campaigns/3/summary seems stuck saying "Campaign 3 is preparing to send to test". I even used ssh and ran:
```
php artisan mailcoach:send-scheduled-campaigns
Checking if there are scheduled campaigns that should be sent...
All done!
```

For Campaign 4, I tried using "Send now", but that still says "Campaign test4 is preparing to send to test" at /mailcoach/campaigns/4/summary.

I still haven't gotten the knack of Horizon. I don't know why I've had such trouble getting Mailcoach campaigns to send.

**Comment by ryancwalsh** [comment]
/horizon/recent-jobs shows tons of jobs (mostly CalculateStatisticsJob but also SendCampaignJob), but they all say "-" for Runtime and have a Pause button for Status.

/horizon/dashboard shows:
![image](https://user-images.githubusercontent.com/2086493/73968814-4e361080-48e8-11ea-94bd-764bfaf5921f.png)

In the meantime, I'll try testing # 2 and 3 from https://github.com/spatie/mailcoach-support/issues/40#issuecomment-582476627

Thanks.

P.S. I solved the Horizon gate issue (https://github.com/spatie/mailcoach-support/issues/40#issue-560030249) here: https://github.com/laravel/horizon/issues/563#issuecomment-582706653

**Comment by ryancwalsh** [comment]
I'll track the Horizon issue separately here: https://github.com/spatie/mailcoach-support/issues/46

**Comment by ryancwalsh** [comment]
Okay, I think we've made some progress because # 2 and 3 from https://github.com/spatie/mailcoach-support/issues/40#issuecomment-582476627 seem like they are working _and_ my latest Mailcoach campaign sent with a link that used the proper "mc" subdomain.

The only problems now are:

1. The link didn't work (resulted in `This site can’t be reached / server IP address could not be found.  / DNS_PROBE_FINISHED_NXDOMAIN`)
1. The opens and clicks still aren't being processed (even though I see in Horizon `ProcessSesWebhookJobQueue: mailcoach-feedback \| Tags: Spatie\MailcoachSesFeedback\SesWebhookCall:47 | 2020-02-06 15:07:27 | 0.31s |  
-- | -- | -- | --` https://github.com/spatie/mailcoach-support/issues/46#issuecomment-583086006
![image](https://user-images.githubusercontent.com/2086493/73974771-f7820400-48f2-11ea-8085-184df7393b20.png)

I just checked my tables, and these are still empty: mailcoach_campaign_clicks, mailcoach_campaign_links, mailcoach_campaign_opens, mailcoach_send_feedback_items.

There's a chance that this means that Mailcoach code is working properly but that my SES or CloudFlare DNS settings aren't quite right.

I'll keep poking around. I'd also love to hear any suggestions. Thanks!

**Comment by riasvdv** [comment]
> This site can’t be reached / server IP address could not be found. / DNS_PROBE_FINISHED_NXDOMAIN

This is most definitely an issue with the DNS not being set up correctly

**Comment by ryancwalsh** [comment]
In the webhook_calls table, I only see "Send" and "Delivery" types. The latest was 2020-02-06 20:16:37 UTC.

But my https://console.aws.amazon.com/ses/home?region=us-east-1#edit-configuration-set:mailcoach says "Event types:Bounce, Click, Complaint, Delivery, Open, Reject, Rendering Failure , Send"

And https://console.aws.amazon.com/ses/home?region=us-east-1#verified-senders-domain: says "Verified" for this "mc" subdomain. The fact that it says "Verified" makes me think my CloudFlare DNS is correct.

**Comment by ryancwalsh** [comment]
I took a guess based on my existing CloudFlare settings and added a CNAME of "mc" to "r.us-east-1.awstrack.me" even though the instructions at https://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-custom-open-click-domains.html#configure-custom-open-click-domain-https and https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-domain-procedure.html don't clearly describe doing that.

And now my Mailcoach campaign's link correctly redirects where it should.

And webhook_calls shows new records for Open and Click.  It took maybe a minute for the webhook calls to arrive.

And /mailcoach/campaigns/4/summary shows the stats!

**It seems to be working now, and I'm pumped! Thanks!**

**Comment by freekmurze** [comment]
I'm very happy that you managed to solve this. Thank you for all your detailed reports that made Mailcoach better. I hope you can now enjoy sending out lots of campaigns, without being bothered with technical problems.
