### ISSUE TITLE
Implement a text editor for content

### ISSUE THREAD

**Issue by 1stevengrant** [spatie/mailcoach-support#43]
My clients aren't technical and so I would love to be able to have some predefined templates that campaigns can use and then have a text editor field that just allows them to format the body of the message as they see fit.

**Comment by freekmurze** [comment]
We’re going to improve on this and will add an easy to use editor in the next couple of weeks.

**Comment by 1stevengrant** [comment]
nice - and fast response too 💪🏻

**Comment by vesper8** [comment]
@freekmurze any it's been almost 3 weeks, I'm very excited about this template editor, any update on the ETA?

**Comment by freekmurze** [comment]
I guess we'll release this in the next few weeks.
