### ISSUE TITLE
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')' 

### ISSUE THREAD

**Issue by karlgray** [spatie/mailcoach-support#44]
I have done a clean install using php 7.4 and am getting this error **in the browser**.

syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')' 
vendor/spatie/laravel-mailcoach/src/MailcoachServiceProvider.php:61

**On the command line** when running
php artisan migrate

I get this error.

 Symfony\Component\Debug\Exception\FatalThrowableError  : syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

  at /var/www/vhosts/xxxxxx/yyyyyy/mailcoach/vendor/spatie/laravel-mailcoach/src/MailcoachServiceProvider.php:61
    57|     public function register()
    58|     {
    59|         $this->mergeConfigFrom(__DIR__ . '/../config/mailcoach.php', 'mailcoach');
    60| 
  > 61|         $this->app->singleton(QueryString::class, fn () => new QueryString(urldecode($this->app->request->getRequestUri())));
    62| 
    63|         $this->app->singleton(Version::class, function () {
    64|             $httpClient = new HttpClient();
    65| 

  Exception trace:

  1   Composer\Autoload\includeFile("/var/www/vhosts/gray.me.uk/mailcoach.gray.me.uk/mailcoach/vendor/composer/../spatie/laravel-mailcoach/src/MailcoachServiceProvider.php")
      /var/www/vhosts/gray.me.uk/mailcoach.gray.me.uk/mailcoach/vendor/composer/ClassLoader.php:322

  2   Composer\Autoload\ClassLoader::loadClass("Spatie\Mailcoach\MailcoachServiceProvider")
      [internal]:0

I am not a laravel developer just a normal user who wants to evaluate Mailcoach.

**Comment by ryancwalsh** [comment]
I'm not an expert and don't work for Spatie but wonder if this issue is happening: https://github.com/spatie/mailcoach-support/issues/10#issuecomment-581044520

**Comment by freekmurze** [comment]
I suspect that you are not running PHP 7.4 for your web requests. Create a file called `test.php` in your public directory with this contents


```php
<?php
phpinfo();
```

And verify the PHP version you are using.

If it's PHP 7.4, let me know and I'll reopen this issue.

**Comment by karlgray** [comment]
Thank you both for your fast response.
Yes, it was plesk that was misreporting the version.  changed it to 7.3 and back to 7.4 restarted nginx and all is fine now.  Apologies and thanks.

**Comment by freekmurze** [comment]
No apologies needed. Hope you'll enjoy Mailcoach.

**Comment by Dgalhotra** [comment]
I'm using 7.4 still getting that error
