### ISSUE TITLE
500 errors related to https://mailcoach.app/api/latest-version

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#45]
My Slack has occasionally been buzzing my phone with 500 errors related to https://mailcoach.app/api/latest-version:

```
GuzzleHttp\Exception\ServerException, Code: 500: Server error: GET https://mailcoach.app/api/latest-version resulted in a 500 Internal Server Error
```

**Comment by freekmurze** [comment]
Seems to be stable now. Make sure you use a real cache driver (and not array), so Mailcoach only tries to reach that endpoint only once a day.

**Comment by ryancwalsh** [comment]
@freekmurze This is still happening for me.

**Comment by ryancwalsh** [comment]
I have `CACHE_DRIVER=redis` and I'm getting these errors multiple times per minute, which means there are probably two problems: the cache isn't working how you expected, and the server is generating 500 errors.

**Comment by freekmurze** [comment]
I've made the latests version checking more robust in the newly released `v1.6.2`.

If you're still getting too much 500 errors, let me know!

**Comment by ryancwalsh** [comment]
Yes I still get them every couple seconds whenever I'm browsing my production Mailcoach page.

**Comment by freekmurze** [comment]
Ok, let’s go to the bottom of this. Could you post the exception backtrace here?

**Comment by ryancwalsh** [comment]
Rollbar and Slack have only been showing me:

```
GuzzleHttp\Exception\ServerException, Code: 500: Server error: `GET https://mailcoach.app/api/latest-version` resulted in a `500 Internal Server Error` response:
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width= (truncated...)
```

**Comment by ryancwalsh** [comment]
Oh wait, I found more:

```
REMOTE_ADDR
162.158.63.197
Trace
#0 /apps/myproject/releases/25/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create()
#1 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler()
#3 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run()
#5 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /apps/myproject/releases/25/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /apps/myproject/releases/25/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Promise\Promise->wait()
#10 /apps/myproject/releases/25/vendor/guzzlehttp/guzzle/src/Client.php(96): GuzzleHttp\Client->request()
#11 /apps/myproject/releases/25/vendor/spatie/laravel-mailcoach/src/Support/HttpClient.php(20): GuzzleHttp\Client->__call()
#12 /apps/myproject/releases/25/vendor/spatie/laravel-mailcoach/src/Support/Version.php(45): Spatie\Mailcoach\Support\HttpClient->getJson()
#13 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(383): Spatie\Mailcoach\Support\Version->Spatie\Mailcoach\Support\{closure}()
#14 /apps/myproject/releases/25/vendor/laravel/framework/src/Illuminate/Cache/CacheMan…
```
When visiting /mailcoach/campaigns/2/summary

**Comment by freekmurze** [comment]
Are you able to visit the mailcoach.app url directly?

**Comment by ryancwalsh** [comment]
Often it works. But often it doesn't. It worked a bunch of times just now in Chrome on Windows 10, and then just now I also got this:
![image](https://user-images.githubusercontent.com/2086493/74089447-40f75e00-4a6f-11ea-93d1-cbf01ce3610c.png)

**Comment by freekmurze** [comment]
I've made this more robust on the server side as well. Is [the endpoint](https://mailcoach.app/api/latest-version) now working for you?

**Comment by ryancwalsh** [comment]
Still the same. Initially it works, but after some browser page refreshes, 500 error.

**Comment by freekmurze** [comment]
The strange thing is that I’m not seeing any errors at our side. If Irefresh multiple times it keeps working even with cache turned off.

Maybe the error is somehow cached at your end? Could you try hitting that endpoint with another device or via another network?

**Comment by ryancwalsh** [comment]
Using Brave browser in Private mode, the behavior was the same. Most initial requests worked, then 500 after refreshes. Same with Chrome Incognito and Firefox Private.

**Comment by freekmurze** [comment]
Good news: I can replicate this behaviour. Looking into a possible fix...

**Comment by freekmurze** [comment]
Ok, I got it now. I've made some server side improvement and added a fix in mailcoach itself.

Could you update to the latest version and try again?

My apologies for the hassle.

**Comment by freekmurze** [comment]
Closing this as I'm fairly sure the problem has been solved. If not, let me know and I'll reopen.

**Comment by ryancwalsh** [comment]
Thanks. I haven’t noticed this problem since then! 😃👍

**Comment by ryancwalsh** [comment]
Thanks. I haven’t noticed this problem since then! 😃👍
