### ISSUE TITLE
Special characters like ❤ don't work in Preview

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#48]
![image](https://user-images.githubusercontent.com/2086493/74049539-53f02c80-49a2-11ea-9919-83e1679f67d5.png)

![image](https://user-images.githubusercontent.com/2086493/74049607-75e9af00-49a2-11ea-96c8-794047fe295e.png)

**Comment by freekmurze** [comment]
@willemvb can you take a look at this one?

**Comment by willemvb** [comment]
We are sending mails out in UTF-8, and the interface also uses UTF-8 encoding.

Include `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />` in the `<head>` section of your mail and it should work. 

I'll think about a good way to make this more clear (eg. in the docs)!

**Comment by ryancwalsh** [comment]
@willemvb Ok, thanks. Without the meta tag, my mails were _already sending fine_ with this special character: ❤.

Now adding the meta tag, they also work well in the Preview display.
