### ISSUE TITLE
changelog or possibility to get notified of updates?

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#5]
Just wondering if there will be a changelog on the website, or if I can be emailed anytime an update is pushed so I know when to update my app.

Or alternatively, will we get access to a private repository here on Github where we can use the "watch" feature to get notified. I know Laravel Spark/Nova does it this way by granting access to private repositories.

**Comment by freekmurze** [comment]
Good suggestion, I'll look into it. I think in short term we will add a releases page to our site.

The mailcoach UI will display a little notice in the footer if there's an update available. 

I suspect that we won't update the skeleton app that much. The package can be updated with a simple `composer install`.

**Comment by freekmurze** [comment]
Oh, and there also should already be a CHANGELOG.md in `/vendor/spatie/laravel-mailcoach`

**Comment by vesper8** [comment]
@sebastiandedeyne @freekmurze  It would be nice if you added the changelog in the online docs

also, I see you released 1.7.x and there is no changelog for this (just updated to 1.7.2)

**Comment by freekmurze** [comment]
We'll add this soon.

**Comment by vesper8** [comment]
@freekmurze still wishing there was a public changelog accessible in the docs section of mailcoach.app

having to do a composer update and get the changelog from the vendor folder is not at all convenient

**Comment by freekmurze** [comment]
The chanelog can also be read here: https://mailcoach.app/roadmap
