### ISSUE TITLE
How to schedule future campaign to send to non-openers of a certain campaign

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#50]
Let's say I send Campaign 1 on Monday at 08:00 with subject "hello" to 12k people.

How can I schedule a resend of that same campaign to send on Tuesday at 14:00 with subject "greetings" (even though the body will be the same as the original campaign) that will only send to the recipients of Campaign 1 who were not tracked as having opened it _by the time the Tuesday campaign is scheduled to send_.

Generally, I send a new campaign every "odd" day, and on "even" days, I want to send a resend of the previous day's campaign but with a new subject line and a different time of day and only send it to the recipients who hadn't opened the first version of that campaign.

And I want to be able to schedule out these sequences sometimes many days in advance (and trust that the determination of who the recipients will be won't happen until the last moment based on tracked opens).

I want to be able to schedule these all from the GUI rather than code.

https://sendpulse.com/ currently allows me to do this, but I want to close my SendPulse account and migrate to Mailcoach ASAP.

Do you have any suggestions? The docs at https://mailcoach.app/docs/package/advanced-usage/segmenting-lists are sparse and don't hint at how to seamlessly build all of this into the web GUI.

If in the short run you have hints about how I can do it programmatically (no GUI), that will be better than nothing. I'd love to schedule my first campaign by Feb 9 if possible with a schedule resend the next day to non-openers.

Thanks! :-)

**Comment by ryancwalsh** [comment]
One idea I'll try is to call `$subscriber->addTag(self::TAG_PREFIX . $campaign->id);` in my CampaignOpenedEventListener.

1. I can use the GUI to create Campaign 1 and schedule it. 
1. Then I can duplicate Campaign 1 and call it Campaign 1 Resend and change its subject.
1. Then I go into a "test" subscriber of mine and create a tag like "Open 1" (if TAG_PREFIX = "Open ").
1. Then I create a new segment at /mailcoach/email-lists/1/segments where "Exclude with tags" = "Any" "Open 1".
1. Then I schedule Campaign 1 Resend (which is really Campaign ID 2) for the following day and will use that segment.

**This should achieve my goal, right?**

One problem I foresee is that tags and segments will soon get unwieldy since I'll be doing this every day.

And steps 3 and 4 can feel cumbersome compared to other systems.

Another problem is that clicks don't always seem to fire CampaignOpenedEvent: https://github.com/spatie/mailcoach-support/issues/51

**Comment by freekmurze** [comment]
> This should achieve my goal, right?

I think so, yes.

> One problem I foresee is that tags and segments will soon get unwieldy since I'll be doing this every day.

I'm thinking you could clean up the tags you don't need with a scheduled artisan command.

> And steps 3 and 4 can feel cumbersome compared to other systems.

True, we try to only add features that could be interesting for 90% of users, so the UI keeps very calm. I don't think we'll add this behaviour in the core soon, but luckily Mailcoach is extensible enough to add this behaviour on your own. I agree it can be a bit cumbersome.

> Another problem is that clicks don't always seem to fire CampaignOpenedEvent: #51

Meanwhile, I've answered to that one as well: you can add the behaviour you want there too.
