### ISSUE TITLE
Clicks aren't always tracked as opens

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#51]
If a subscriber clicks a link in a campaign when their email client is set to not download images (and therefore the open wouldn't be tracked that way), Mailcoach should still call registerOpen and fire CampaignOpenedEvent.

![image](https://user-images.githubusercontent.com/2086493/74088739-8d3ea000-4a67-11ea-9f1b-75fdeb94d1fe.png)

**Comment by freekmurze** [comment]
I'm inclined to just use follow the SES events that get sent to Mailcoach. I can image that some people find it interesting to know how many people block the open tracking.

If you want a click to count as an open as well (when there are no opens), listen for the `CampaignLinkClickedEvent` and add the behaviour you want there.
