### ISSUE TITLE
Scheduling newsletter takes the server time, not my local timezone

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/mailcoach-support#53]
Most servers are configured to run in UTC, but if I'm in the UI and schedule a newsletter to be sent at 8AM, I expect that UI to show me my _current_ timezone.

Right now, it uses the date on the server, which is a bit tricky to schedule things.

![Schermafbeelding_2020-02-09_om_08_05_36](https://user-images.githubusercontent.com/407270/74097990-12cb5a00-4b13-11ea-81f2-1cb3f93e3d38.png)

**Comment by freekmurze** [comment]
You can change the `timezone` setting in the `config/app.php` config file. I've now added a note on this in the installation instructions.
