### ISSUE TITLE
Mail configuration: send test email uses same from/to instead of config default

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/mailcoach-support#54]
Hi!

When configuring the email settings in `/settings/mail-configuration`, you can configure a default from address. If you then test your configuration in `/settings/send-test-mail`, it sets the `to` and `from` of the test e-mail to the e-mail address you're sending the test email _to_, instead of using the mail config default from address I just configured.

![Schermafbeelding_2020-02-09_om_08_16_33](https://user-images.githubusercontent.com/407270/74098146-de589d80-4b14-11ea-9a29-174bb5a9d950.png)

I believe it should set the `from` address to whatever was configured to be the default in my mail config.

Otherwise, it gives a false result to test e-mail deliverability, as it may spoof e-mail addresses.

![Schermafbeelding 2020-02-09 om 08 16 42](https://user-images.githubusercontent.com/407270/74098129-b0735900-4b14-11ea-9552-268d10a54fda.png)

**Comment by mattiasgeniar** [comment]
In fact, I don't think the `test email` even uses those settings, I think I had to configure my mailgun account in `.env` and `config/mail.php` before I could send a test message? I could be remembering this wrongly, there was _some_ thing in Mailgun that required me to configure `config/mail.php` before I could send a test e-mail.

**Comment by freekmurze** [comment]
Mailcoach will set the default from email address to the one that was specified in the UI here: https://github.com/spatie/Mailcoach/blob/eec9935dd77fbcc0f851e4bafa8c966e835d6ec2/app/Support/MailConfiguration/Drivers/MailgunConfigurationDriver.php#L29

Could it be that you have your config cache? Try `php artisan cache:clear`.

**Comment by freekmurze** [comment]
Meanwhile I've updated the app so the cache config will get cleared when you update the email settings in the Mailcoach UI

**Comment by mattiasgeniar** [comment]
Nice, added that one!
