### ISSUE TITLE
When invalid HTML is detected, show the error message of the parser

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/mailcoach-support#55]
I had an incorrectly encoded `&` in my mail body, and the form input for sending a new campaign wouldn't accept my HTML.

Because the `HtmlRule()` validation just validates true/false, without exposing the error, you're a bit blind as the user.

I would like to see the `exception` being thrown to also be shown in the UI so I wouldn't have to dive in the code to find why the `DOMDocument` complained.

**Comment by freekmurze** [comment]
In the newly released `v1.6.5` you'll see the error message given by `DOMDocument`.
