### ISSUE TITLE
TXT version of an HTML newsletter is not being generated

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/mailcoach-support#56]
When sending the HTML newsletter, the TXT version didn't get generated and included in the mail body. The mail body looked like this.

```
--_=_swift_1581080361_e47830b5eca1ea529600cfd87daf9ec8_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable



--_=_swift_1581080361_e47830b5eca1ea529600cfd87daf9ec8_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www=
.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns=3D"https://www.w3.org/1999/xhtml" style=3D"-ms-text-size-adjust=
: 100%; -webkit-text-size-adjust: 100%; margin: 0 auto !important; padding:=
 0 !important; height: 100% !important; width: 100% !important;">
<head style=3D"-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;"=
>
```

With no data in `text/plain`.

It might be because my HTML couldn't be converted to TXT? Or there might be something else that's preventing it, but I couldn't figure that out just yet and the preview/final confirmation screen didn't show any warnings.

While personal, I'd _love_ ❤️ to see a (opt-in) option of providing the TXT version of the newsletter myself in the UI or database. :-)

**Comment by freekmurze** [comment]
The html to text conversion is being done in the `ConvertHtmlToTextAction` class. You can new up this class, pass the `$html` to the `execute` method. Right now, exceptions are being suppressed. To see the error you can put a `dump` statement to see the exception in the catch block.

Right now those errors are indeed being ignored because it is assumed that most received will be able to display html content. I'll improve on this behaviour in a future version of the package.

Could you let me know the exception message you got.

**Comment by mattiasgeniar** [comment]
OK I don't get any exceptions, the TEXT version is generated from the HTML fine, but isn't being added to the e-mail itself.

Seems like this might be a bug in the SwiftMailer implementation that it's not adding that text/plain version?

**Comment by mattiasgeniar** [comment]
To confirm, the latest issue of freek.dev contained this mail body:

```
--_=_swift_1581068379_8fae16ff759e91be077015dc2b017129_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable



--_=_swift_1581068379_8fae16ff759e91be077015dc2b017129_=_
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<html><!doctype html>
<html lang=3D"en" xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:=
schemas-microsoft-com:office:office">
<head>
```

Also without text/plain

**Comment by riasvdv** [comment]
@mattiasgeniar We've fixed some things in 1.6.10, the "Send test mail" button wasn't including the plaintext version in the email and we're now suppressing DOM errors when generating the plaintext version.

Let me know if this fixes it for you!

**Comment by mattiasgeniar** [comment]
Hm I'll test, but Freek's newsletter didn't include the TXT version either, so I Don't think it's just about the "send test mail" button though

**Comment by riasvdv** [comment]
The issue with Freek's newsletter was that it was throwing an exception on an invalid Doctype, which should be fixed now as we're suppressing them.

**Comment by mattiasgeniar** [comment]
Confirmed, this works - thanks!
