### ISSUE TITLE
ImportSubscriberRow not considered?

### ISSUE THREAD

**Issue by goaround** [spatie/mailcoach-support#57]
I would like to customize the Subscriber Import. The `App\Support\ImportSubscriberRow` class seems perfectly for this case. I modified the class but when I run an Import it seems that the class is not considered.

FYI: I created a the app using `composer create-project spatie/Mailcoach`

**Comment by freekmurze** [comment]
`ImportSubscribersRow` can't be customised. You can however customise the `ImportSubscribersAction`.  See the `actions` key in `config/mailcoach.php`.
