### ISSUE TITLE
ErrorException: Class 'Str' not found

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#58]
`ErrorException: Class 'Str' not found (View: /vendor/spatie/laravel-mailcoach/resources/views/app/emailLists/subscribers.blade.php)` when I try to search using the Filter box at **/mailcoach/email-lists/2/subscribers** which goes to **/mailcoach/email-lists/2/subscribers?filter[search]=test**

**Comment by freekmurze** [comment]
This has been fixed in `v1.6.8`
