### ISSUE TITLE
Cannot update subscriber if same email address exists on another list

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#59]
Steps to reproduce:

1. Create 2 separate email lists.
1. Add the same subscriber (i.e. same email address) to both lists.
1. Visit /mailcoach/email-lists/1/subscriber/1/details
1. Try to add a tag and save.
1. See error "There already is a subscriber with this email."

UpdateSubscriberRequest seems to have trouble.

**Comment by freekmurze** [comment]
I’ll take care of this soon!

**Comment by ryancwalsh** [comment]
I appreciate your quick responses! :-)

This one isn't a rush for me; it's not stopping me from sending my first real Mailcoach campaign.

I just started sending to a batch of 1,000 real subscribers, and assuming all looks good, I'll send the rest later today and will schedule a send to non-openers tomorrow.  Woohoo!

**Comment by freekmurze** [comment]
This is fixed in `v1.6.9`.

Have fun sending out your campaign.

**Comment by ryancwalsh** [comment]
Thanks!

And thanks for the quick fix.

My /mailcoach/campaigns/7/summary has been stuck showing the `fas fa-sync fa-spin text-blue-500` spinner for the whole 53 minutes since sending the campaing to 1,000 subscribers. 

But `SELECT 
    created_at, updated_at
FROM
    mailcoach_sends
ORDER BY created_at DESC` shows that all 1,000 were sent between 18:00 and 18:02:33 UTC.

This shows 100-300 per minute early on (around 18:00) but then tapering to 1 or 2 per minute recently:

```
SELECT 
    DATE_FORMAT(`created_at`, '%Y-%m-%d %H:%i') AS timeChunk,  
    COUNT(*) AS cnt
FROM
    webhook_calls
WHERE
    payload LIKE '%Send%'
GROUP BY timeChunk
ORDER BY timeChunk DESC;
```

The same is true if I switch `'%Send%'` to `'%Delivery%'`.

Is the spinner related to webhook calls still coming in?

Maybe I'll go ahead and send to the other 11,000 on the list, because I don't think I see any problems.

**Comment by freekmurze** [comment]
Normally you should see a progress bar that's slowly filling on the campaign summary screen. 

Any mail that should be sent out or is already sent out is indeed represented by a row in the `mailcoach_sends` table. The `created_at` represents the date that it was scheduled.

 A successfully sent mail will have the `sent_at` property filled. Failed mails will have the `failed_at` property filled (you can also see a failure reason in `failure_reason`. Mails that do not have `sent_at` or `failed_at` filled are still pending.

You can learn more about the sending process in this video: https://mailcoach.app/video-course/how-mailcoach-was-built/sending-a-campaign

If you followed the installation instructions currently the webhook calls should be handled via a queue, so they shouldn't interfere with the sending itself.

There's too little to go on here to help you further, but if you have more questions let me know. Feel free to open up an new issue with more information.
