### ISSUE TITLE
unsubscribeUrl typo

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#6]
when creating my first campaign, I noticed in the Delivery tab this message Without a way to unsubscribe, there's a high chance that your subscribers will complain. Consider adding the ::unsubscribeUrl:: placeholder.

But looking at the 'Preview' it does show an Unsubscribe button. And looking at the content tab it does show href="::unsubcribeUrl::"

In the delivered mail, the ::unsubcribeUrl:: was not replaced and just stayed as is, which caused an error when I tried to click on it.

The reason is there is a typo in the default template: `'unsubscribeUrl' !== 'unsubcribeUrl'`

**Comment by freekmurze** [comment]
Thanks for reporting this.

I've fixed this in `TemplateSeeder` for newly installed apps. In your current app, you should manually update it. 

We're still figuring a good way of automating updates to the skeleton app.
