### ISSUE TITLE
Never-ending spinner

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#60]
I think I know the problem I wrote about at https://github.com/spatie/mailcoach-support/issues/59#issuecomment-584303847, which I'll also paste below: 

~~
My /mailcoach/campaigns/7/summary has been stuck showing the `fas fa-sync fa-spin text-blue-500` spinner for the whole 53 minutes since sending the campaing to 1,000 subscribers. 

But `SELECT 
    created_at, updated_at
FROM
    mailcoach_sends
ORDER BY created_at DESC` shows that all 1,000 were sent between 18:00 and 18:02:33 UTC.

This shows 100-300 per minute early on (around 18:00) but then tapering to 1 or 2 per minute recently:

```
SELECT 
    DATE_FORMAT(`created_at`, '%Y-%m-%d %H:%i') AS timeChunk,  
    COUNT(*) AS cnt
FROM
    webhook_calls
WHERE
    payload LIKE '%Send%'
GROUP BY timeChunk
ORDER BY timeChunk DESC;
```

The same is true if I switch `'%Send%'` to `'%Delivery%'`.

Is the spinner related to webhook calls still coming in?

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 
**UPDATE:**

I am using a PersonalizedReplacer, and in that PersonalizedReplacer, I forgot to add `use Log;` at the top even though I did have a log statement within the `replace` function.

At the schedule campaign send time, my phone got a Slack error saying `Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Services\Mailcoach\Replacers\Log' not found`, and I thought "oh, no problem... I'll fix that quickly now locally, and then once I deploy to production again before I send the next campaign, everything will be fine".

But I didn't "connect the dots" until now that this failed send was the reason that the spinner kept spinning.

This whole time, the spinner message had been saying **Campaign is sending to 1000/1001 subscribers of Main**. I should have realized "oh, yeah, there was that one failure, so it's never going to complete".  Sorry.

Maybe that status message could mention the errors instead of spinning indefinitely. 

If I hadn't set up my system to have good error logging, I never would have known. (And even with it, I took this long to figure it out 🤦‍♂️ haha.)

Thanks again for all of your help and encouragement. And for the great videos. :-)

**Comment by freekmurze** [comment]
In a future release, I'll try to improve the behaviour when something goes wrong. 

Thanks for letting me know the whole story 👍
