### ISSUE TITLE
Site improvement (new favicon & videos redirect)

### ISSUE THREAD

**Issue by fcaivano** [spatie/mailcoach-support#61]
Just two comments

- Changing favicon
Although there's not full support yet for changing favicon when using dark mode on browsers (https://bugs.chromium.org/p/chromium/issues/detail?id=889087) maybe a different favicon, the same logo over a blue background would work better?
This is how i currently see it:
![image](https://user-images.githubusercontent.com/2979774/74266782-7e0b5c80-4cca-11ea-808d-20453eda94e7.png)

A little bit hard to find when having multiple tabs open in darkmode.
Something like this would work better:
![mailcocah](https://user-images.githubusercontent.com/2979774/74267287-641e4980-4ccb-11ea-9271-59f3436bb36c.png)

- When one goes to: https://mailcoach.app/videos

If logged in and already bought the access to the videos, there's no easy way to tell how to access them.
Maybe a notification boxes with a button to redirect to the actual url:
https://mailcoach.app/video-course

Just ideas from navigating the site.

The rest, the real important stuff, it's just amazing :D

Thanks!

**Comment by willemvb** [comment]
Thanks for your valuable input!

I've updated favicons on the public site (will come to the sold app/bundle soon as well).

<img width="180" alt="image" src="https://user-images.githubusercontent.com/1336390/74332529-36ea9d80-4d96-11ea-8e2d-36134e19a4e2.png">

The navigation also changed a bit: once you're logged in, the nav is in 'logged-in' state even on public pages.
I also added a little heads-up on the video-page.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/1336390/74332411-f559f280-4d95-11ea-8da5-bc3fe9d9ab97.png">
