### ISSUE TITLE
Race condition can potentially result in multiple subscribers to same list with same email

### ISSUE THREAD

**Issue by tdondich** [spatie/mailcoach-support#64]
I have some jobs that automatically subscribe users to a campaign list.  However, multiple of these jobs might be fired off at the same time.  It's possible that if these two jobs run at the same time from queue workers, that multiple records will be created, making duplicated subscriber records for a list.

I'm assuming a unique index for list id and email will help resolve this.  Just wanted to bring this up.

**Comment by freekmurze** [comment]
Great suggestion, thanks! I've added this in the default migration.

**Comment by tdondich** [comment]
❤️
