### ISSUE TITLE
Events as more complex variant of Tags?

### ISSUE THREAD

**Issue by beberlei** [spatie/mailcoach-support#66]
Drip and ConvertKit have both introduced the notion of events instead of tags, to better allow segmentation based on time, and amount of things. With tags i can say "did something", but i don't know when and how often it happend.

with Events i could say "has done something twice in the last 30 days".

Datamodel would be something like:

Event:
- SubscriberId
- EventName
- Date

**Comment by freekmurze** [comment]
This is something we'll consider for `v2`.
