### ISSUE TITLE
Postmark Feedback Support

### ISSUE THREAD

**Issue by beberlei** [spatie/mailcoach-support#67]
I would like to add support for Postmark, but looking at the existing feedback channels I see no clear way to get this hooked up. Could you provide some pointers where to start?

**Comment by freekmurze** [comment]
Hi Benjamin,

great that you want to do this!

In Mailcoach, a mail that was sent is represented by a `Send` model. This model has several methods to register clicks, links, complaints and bouces: `registerOpen`, `registerClick`, `registerBounce` and `registerComplaint`.

Mail service providers use webhooks to send feedback. Our feedback packages are open source. You'll find them here:
- https://github.com/spatie/laravel-mailcoach-mailgun-feedback
- https://github.com/spatie/laravel-mailcoach-sendgrid-feedback
- https://github.com/spatie/laravel-mailcoach-ses-feedback

All these package receive webhooks from the service they are built for. Under the hood, we [use](https://github.com/spatie/laravel-mailcoach-mailgun-feedback/blob/b720d545871fd15cb74a3d853546ac33f8a3c057/src/MailgunWebhookController.php#L12-L16) our [laravel-webhook-client](https://github.com/spatie/laravel-webhook-client) package to listen for incoming webhooks. They also validate [the signature on the webhook](https://github.com/spatie/laravel-mailcoach-mailgun-feedback/blob/b720d545871fd15cb74a3d853546ac33f8a3c057/src/MailgunWebhookController.php#L12-L16).

For each webhook request that comes in, a queue job is started. [The job](https://github.com/spatie/laravel-mailcoach-mailgun-feedback/blob/b720d545871fd15cb74a3d853546ac33f8a3c057/src/ProcessMailgunWebhookJob.php) is determines (via an [event factory](https://github.com/spatie/laravel-mailcoach-mailgun-feedback/blob/master/src/MailgunEventFactory.php)) which event is being sent. There's also [a video](https://mailcoach.app/video-course/writing-clear-code/refactor-if-blocks-to-dedicated-classes) available in the video course on that subject.

Per event there is a dedicated class that [calls the right method on the `Send` object](https://github.com/spatie/laravel-mailcoach-mailgun-feedback/blob/b720d545871fd15cb74a3d853546ac33f8a3c057/src/MailgunEvents/OpenEvent.php#L16).

If you have more questions, let me know!

If you want, I could already create a repo for you to work in with some scaffold, so you only need to add the bits to validate the signature and to determine which event is being sent.

**Comment by renatonascalves** [comment]
Just a note that Postmark is not an email marketing delivery tool like Mailchimp.

https://postmarkapp.com/support/article/831-why-cant-i-send-bulk-emails

**Comment by emilsundberg** [comment]
@renatonascalves Postmark has recently launched bulk emails, see https://postmarkapp.com/blog/api-bulk-the-final-frontier but I think you need to contact them enable it.

From the linked post:

> So I’m pleased to announce that we’ve launched 🚀 brand new infrastructure for managing what we call “API bulk”, that is, similar messages sent to multiple recipients.

**Comment by beberlei** [comment]
@renatonascalves @emilsundberg Yes, we are part of the bulk mail beta with our account.

**Comment by renatonascalves** [comment]
Interesting! I'm an active user of Postmark and didn't get an email with this news. Thanks for sharing. :)

**Comment by freekmurze** [comment]
@beberlei I've created a repo here for you to work in: https://github.com/spatie/laravel-mailcoach-postmark-feedback

I've already set some things up. Things for you to implement:
- `PostmarkSignatureValidator`
- `canHandlePayload` on each `PostmarkEvent`
-  tests

If you have any questions, do let me know. Happy to help you!

**Comment by freekmurze** [comment]
Closing this here, if there are any questions, post them on the issue tracker of https://github.com/spatie/laravel-mailcoach-postmark-feedback
