### ISSUE TITLE
“Upgrade available” is shown - even with the latest version

### ISSUE THREAD

**Issue by hanspagel** [spatie/mailcoach-support#69]
Is it just me or is the “Upgrade available”, even after running `composer update`? Do I miss something?

![bwY3J1qkPK](https://user-images.githubusercontent.com/1577992/74646101-7be94800-5179-11ea-85da-abdac6750147.png)

**Comment by freekmurze** [comment]
Could you try clearing your cache and let me know if the problem persists?

**Comment by hanspagel** [comment]
Did another update to 1.7.1, seems to be fixed. Can’t reproduce it anymore, not sure if it was a cache thing or if you added a fix. Thanks in both cases!

**Comment by rodrigolopespt** [comment]
getting this with the new version 3.0.6
