### ISSUE TITLE
seeders included for audiences including one list with 137 real emails

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#7]
I noticed that the standalone app (possibly the Laravel package too) comes with seeders for two email lists ('my audience' and 'sint'). The 'sint' list in particular appears to contain 137 real emails. I don't know if this is intended but it would seem risky to have people accidentally email all those people

**Comment by freekmurze** [comment]
Thanks for reporting this!

The `sint` list contains email addresses generated with faker. They are not real. I clean up the seeders so there's only one list seeded.
