### ISSUE TITLE
Data too long for column 'confirmation_mail_content'

### ISSUE THREAD

**Issue by hanspagel** [spatie/mailcoach-support#70]
`confirmation_mail_content` & `welcome_mail_content` are migrated as strings to the database. That leads to a QueryException when I try to add content longer than 255 chars to the customized confirmation mail or customized welcome mail.

It’s not unusual to have HTML emails longer than 255 characters, I think longText would be a more appropriate column type.

**Comment by freekmurze** [comment]
You're right. I've changed this in the default migration.
