### ISSUE TITLE
<![if !mso]> causing the app to trigger invalid html

### ISSUE THREAD

**Issue by prolonginc** [spatie/mailcoach-support#71]
Hello I have the following tags in my html email template `	<![if !mso]> and  	<![endif]-->` and it will not let me save the email html when i try to save it in the campaign content. throwing `The HTML is not valid (DOMDocument::loadHTML(): htmlParseStartTag: invalid element name in Entity, line: 60).` error

**Comment by riasvdv** [comment]
An mso conditional works like this:

`<!--[if !mso]> and <![endif]-->`

You forgot the `<!--`at the opening tag (should be parsed as an HTML comment)

**Comment by prolonginc** [comment]
thank you sir.
