### ISSUE TITLE
App is not running

### ISSUE THREAD

**Issue by philsam** [spatie/mailcoach-support#72]
The app is not running after following the setup steps

Symfony\Component\Debug\Exception\FatalThrowableError
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'

vendor/spatie/laravel-mailcoach/src/MailcoachServiceProvider.php:62

<img width="843" alt="Screen Shot 2020-02-17 at 1 48 28 PM" src="https://user-images.githubusercontent.com/8139955/74688408-4732bc00-518c-11ea-93e0-df7ddad91ffa.png">

**Comment by freekmurze** [comment]
Please make sure you are running PHP 7.4

**Comment by arthurkirkosa** [comment]
I'm having the same issue and I'm running php 7.4.3

**Comment by freekmurze** [comment]
@arthurkirkosa Do you know for sure? The version of PHP on the CLI might differ from the one handling web requests.

**Comment by arthurkirkosa** [comment]
Yes. Restarted valet and it works now
