### ISSUE TITLE
UnsubscribedEventListener (and other listeners) infinite loop

### ISSUE THREAD

**Issue by ryancwalsh** [spatie/mailcoach-support#73]
I have my main Laravel app and its database of contacts, and now I have Mailcoach installed as a package, and it has a table of subscribers. I want to keep its subscribers table completely in sync with the relevant columns of my contacts table.

Before using Mailcoach, when I used 3rd party email campaign providers, I'd use an API to update the third party whenever there were any changes to my contacts table (such as when an admin either unsubscribed a contact, changed its name, updated its email address, etc).  

Additionally, to keep the tables in sync from the other direction, the 3rd party email campaign provider would send webhook calls whenever a subscriber unsubscribed, bounced, etc.

To prevent infinite loops, the 3rd party knew _not to trigger the webhook calls_ whenever what _caused_ the subscriber updates was _my use of the API_. 

Since Mailcoach didn't seem to have this awareness, I was getting infinite loops during unsubscribes or complaints.

I finally came up with a solution that _seems_ to be working, and I wonder what you think about it and whether you'd recommend handling it differently.

In my UnsubscribedEventListener's "handle" function, I wrap everything with this conditional statement:

```
if (!CT::isFunctionInDebugBacktrace(Send::class . '->registerBounce') && !CT::isFunctionInDebugBacktrace(Send::class . '->registerComplaint') && !CT::isClassInDebugBacktrace(\App\Services\MailcoachService::class)) {// exclude Bounces and Complaints (because they will be handled in their own listeners) and the cases where the Unsubscribe originated here in my app instead of in Mailcoach (e.g. when an admin manually unsubscribes a contact)
   //main code here
}
```

Other listeners now also check for similar conditions (e.g. `if (!CT::isClassInDebugBacktrace(\App\Services\MailcoachService::class))`).

I'd never needed to use `debug_backtrace()` before (which my `isFunctionInDebugBacktrace` relies on), so this approach feels unusual. But I guess it's working.

Thoughts? Thanks.

**Comment by freekmurze** [comment]
I don't think it's bad to use `debug_backtrace`. There's a high change that you're depending on that function everyday, since Eloquents relationships make use of it too.

If you want an alternate approach, you could take a look at Eloquents `withOoutEvents` static method. Here's an example from my blog: https://github.com/spatie/freek.dev/blob/535362c340e13276af3e7a0061c311588668de77/app/Models/Post.php#L48

**Comment by ryancwalsh** [comment]
Thank you! I'd never heard of `withoutEvents` and see it explained here: https://stackoverflow.com/q/29407818/470749
