### ISSUE TITLE
Documentation on Segmenting lists using a query outdated?

### ISSUE THREAD

**Issue by goaround** [spatie/mailcoach-support#74]
Hi,

I think the dokumentation on segmenting lists using a query is outdated or incorrect: https://mailcoach.app/docs/package/advanced-usage/segmenting-lists

I can't find any reference to the function `getSubscriptionsQuery` in the package. I think the correct function is called `subscribersQuery` like used inside this test: https://github.com/spatie/laravel-mailcoach-tests/blob/be3aef1c53281bc98a3c56dc8d41fce332c3d0d7/TestClasses/TestSegmentQueryOnlyJohn.php

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. 

The docs have been updated.

**Comment by goaround** [comment]
Makes way more sense now, thank you!
