### ISSUE TITLE
SES feedback route receives duplicate events from SNS subscription

### ISSUE THREAD

**Issue by jbraband** [spatie/mailcoach-support#75]
I have troubleshooted the following described issue to death over 2 days and have come to the conclusion that I have something misconfigured in AWS (SES and/or SNS).

What is happening is once a campaign hits my inbox, I'll open it. Over the next 10 minutes, I'll see 1-8 requests come in from SNS for the same MessageID. The same occurs for click events as well. Sometimes I will see just a single webhook, sometimes its as many as 8.

**Troubleshooting steps taken:**
- I attached an SQS queue as a second subscriber to my mailcoach SNS topic. With both subscribers active, I see the duplicates in both the SQS queue and my webhook_calls database table (that the spatie/laravel-webhook-client package uses).
- I attached a third subscriber that emails me with the event information. unfortunately this does not send the MessageID from SNS like the other subscribers so it's not possible to match them up perfectly

My thought is that since I see the duplicate events in the SQS queue, then the problem does not exist in Mailcoach. Those events never see my code or Mailcoach's code. Direct from SES > SNS > SQS.

Has anyone run into this situation with SES > SNS > multiple events?

I can certainly provide more details if needed.

**Comment by ryancwalsh** [comment]
Yes, I've been experiencing this. I haven't quite figured it out yet. I received 9 "complaint" events from one subscriber. It seems unlikely that the subscriber reported my campaign as spam 9 times.

**Comment by jbraband** [comment]
digging through SNS FAQs page (https://aws.amazon.com/sns/faqs/#Reliability), I found this:

> **Q: How many times will a subscriber receive each message?**
> Although most of the time each message will be delivered to your application exactly once, the distributed nature of Amazon SNS and transient network conditions could result in occasional, duplicate messages at the subscriber end. Developers should design their applications such that processing a message more than once does not create any errors or inconsistencies.

Perhaps this is a "thing" that happens with SNS. the open and click tables would need to capture the MessageID from the SNS payload to prevent duplicate opens/clicks.

**Comment by freekmurze** [comment]
I'm thinking we could filter out duplicate message in this class. It'll get called right before a payload of a webhook is processed.

https://github.com/spatie/laravel-mailcoach-ses-feedback/blob/0469bd45b82ac2f7afaf26480347faabda0126ba/src/ProcessSesWebhooksProfile.php#L10

Here we could add a check if there exists a record in the `webhook_calls` table with the MessageID in the payload.

I do worry about the performance when `webhook_calls` contains many rows though. 

Suggestions for alternative solutions are welcome. If you need this to be fixed very fast, send a PR to the feedback package. Otherwise I'll try to address this soon myself.

**Comment by jbraband** [comment]
I'll look and see if there's a straight forward way to get the MessageID from the webhook through to the mailcoach_clicks and mailcoach_opens tables.

although now that I think about this, that isn't going to work since SES is just one of the mail options. guessing you dont want that.

**Comment by jbraband** [comment]
with performance of looking up the SES message_id in mind, another approach would be to add a migration to the laravel-mailcoach-ses-feedback package for a table called mailcoach_ses_processed_messages

id
ses_message_id
created_at
updated_at

that table would be queried before processing for the message_id and then inserted into after a new message is processed.

@freekmurze how do you feel about a migration for the spatie/laravel-mailcoach-ses-feedback package?

I can work on a PR once I get into work today

**Comment by jbraband** [comment]
Another option is to put a collection of processed MessageIDs in redis.

Pros:
less cumbersome than database table
if cache is wiped, we're only dealing with metrics, some opens/clicks might get duplicated in the aggregate counts, but probably not enough to change trends

Cons:
cache could be wiped and opens/clicks could be duplicated

**Comment by jbraband** [comment]
With either a database table or using redis, I'd propose that it gets cleaned out with a scheduled command every day, wiping message_ids that are older than 24 hours. Let's keep that list clean and lean :)

@freekmurze i have my environment set up to develop this PR. as the package maintainer, I'd like to get your thoughts on database versus redis before I proceed.

disclaimer: my first non-documentation PR :)

**Comment by ryancwalsh** [comment]
@jbraband Thanks for working on this. I just noticed a case today where I got *28* notifications about the same complaint.

**Comment by jbraband** [comment]
I have a PR near ready to go without tests. I'll do the tests while waiting for feedback on the code additions.

The fork is here https://github.com/LeutholdGroup/laravel-mailcoach-ses-feedback

Writing the message_id record was tricky. At first I had attached a listener to the CampaignOpenedEvent (and the three other events), but didn't see a non-disruptive way to get the message_id from the original payload into that listener without changes to the laravel-mailcoach package.

The next commit will be adding a public method to the abstract SesEvent class which will store the message_id. That method will be called from handle in each of the four event type classes after $send->register____________() is called.

Hopefully will get that committed soon after the bus ride home so that @freekmurze and team can eyeball the PR Thursday morning.

**Comment by jbraband** [comment]
@freekmurze @ryancwalsh please review the draft PR linked above

**Comment by freekmurze** [comment]
We'll continue the conversation around this in that PR. Thanks for your work.
