### ISSUE TITLE
Email not sending from server, mailgun is configured and working

### ISSUE THREAD

**Issue by philsam** [spatie/mailcoach-support#76]
@freekmurze   local.ERROR: There are no commands defined in the "email-campaigns" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"email-campaigns\" namespace. at /mailcoach/vendor/symfony/console/Application.php:598)

**Comment by philsam** [comment]
Update: Mail is now sending, but why do I get that error in the log file?

**Comment by freekmurze** [comment]
There seems to be an error in the `App\Console\Kernel.php` file.

In that file replace the line that contains "email-campaigns" with this one:

```
$schedule->command('mailcoach:send-scheduled-campaigns
')->everyMinute();
```

I've updated this application template too, and will inform existing users soon.
