### ISSUE TITLE
Can't extend ImportSubscribersAction

### ISSUE THREAD

**Issue by goaround** [spatie/mailcoach-support#77]
I try to write my own Import Action for the MailChimp export. I've extended `Spatie\Mailcoach\Actions\Subscribers\ImportSubscribersAction` to implement my own `ImportSubscriberRow`. But if I change the `import_subscribers` action inside `config/mailcoach.php` I always get this Exception:

> Spatie\Mailcoach\Exceptions\InvalidConfig
> The class currently specified in the mailcoach.actions.import_subscribers key 'App\Actions\Subscribers\ImportMailchimpSubscribersAction' should be or extend Spatie\Mailcoach\Actions\Subscribers\ImportSubscribersAction. 

Here is my `ImportMailchimpSubscribersAction::class`

```
namespace App\Actions\Subscribers;
use Spatie\Mailcoach\Actions\Subscribers\ImportSubscribersAction;

class ImportMailchimpSubscribersAction extends ImportSubscribersAction
{
[...]
}
```
And the part of the `config/mailcoach.php`

```
/*
 * Actions concerning subscribers
 */
[...]
'import_subscribers' => \App\Actions\Subscribers\ImportMailchimpSubscribersAction::class, 
[...]
```

I don't understand the problem or I'm up in the air...

**Comment by freekmurze** [comment]
On first sight, I don't see anything wrong with your code.

I've added [this test](https://github.com/spatie/laravel-mailcoach-tests/blob/f0d796399c8c02c30fa887d0dd2f63b68ccc07a1/Features/CustomizableActionTest.php#L110-L121) that verifies the action can be customised.

Could you past the entire stack trace of the exception you're getting?

**Comment by goaround** [comment]
@freekmurze I tried your CustomImportSubscribersAction class inside my app and I get the same error.

Here is the full stack trace: https://flareapp.io/share/17DKERPv#F1

**Comment by freekmurze** [comment]
Thanks for the stack trace (❤️❤️❤️ for using a Flare share), but II cannot reproduced this.

After [this line](https://flareapp.io/share/17DKERPv#F73L13), try to find out what is the contents of the `$configuredClass` and `$actionClass` variables.

**Comment by goaround** [comment]
After a lot of trial & error I updated my PHP to 7.4.3 and that fixed my issue. 😌
