### ISSUE TITLE
yarn run prod ends in empty css

### ISSUE THREAD

**Issue by stefanbauer** [spatie/mailcoach-support#79]
If you run `yarn run prod`, this ends in an empty CSS file.

```
 DONE  Compiled successfully in 1939ms                                                                                                                                                                    1:14:17 PM

       Asset      Size  Chunks             Chunk Names
/css/app.css   0 bytes       0  [emitted]  /js/app
  /js/app.js  84.9 KiB       0  [emitted]  /js/app
```

**Comment by stefanbauer** [comment]
Well, I know that this isn't working because I've to publish the assets. But maybe in the standalone application, it makes sense to integrate that build into the webpack.mix.js as well that `yarn run prod` will work.

**Comment by sebastiandedeyne** [comment]
Sorry, but gonna need a lot more context 😅 

Where exactly are you running `yarn run prod`? In the default Mailcoach skeleton app, or in the Mailcoach package?

Did you change anything in the assets?

Why do you want to run this in the first place?

**Comment by stefanbauer** [comment]
Sure, here you are:

> Where exactly are you running yarn run prod? In the default Mailcoach skeleton app, or in the Mailcoach package?

Standalone application

> Did you change anything in the assets?

No.

> Why do you want to run this in the first place?

There is no reason YET. But because it's a regular Laravel application and I'd like to add something or modify anything I'd expect that a `yarn run prod` would still work. The easiest way to achieve that is just merge the regular output with the vendor css I think. And everything's fine, isn't it?

**Comment by sebastiandedeyne** [comment]
Got it!

I don't think it's an issue, the CSS actually _is_ empty.

https://github.com/spatie/Mailcoach/blob/master/resources/sass/app.scss

Running `yarn run production` builds the application assets, Mailcoach assets are prebuilt and loaded from `vendor`.

**Comment by stefanbauer** [comment]
Actually, I thought the same. But here it didn't work. Locally it did, but as soon as you deployed it, no CSS was loading. Only after published the assets which shouldn't be necessary, because it's part of the standalone application, isn't it?

**Comment by sebastiandedeyne** [comment]
Hey Stefan, sorry, I replied right before I left on vacation and forgot to pick it back up after…

Is this still an issue? It could be that the assets were accidentally gitignored, which would cause them to not be available on the server. Having `vendor` instead of `/vendor` in your repo's `.gitignore` file can cause this.

**Comment by freekmurze** [comment]
I'm assuming this isn't a problem anymore. Let us know if this should be reopened.
