### ISSUE TITLE
composer.lock in .gitignore

### ISSUE THREAD

**Issue by stefanbauer** [spatie/mailcoach-support#80]
When using mailcoach as a standalone application, imho `composer.lock` shouldn't be available in `.gitignore`. Otherwise, when running `composer install` on a production machine I never know which packages get installed and if it's still working afterwards.

**Comment by freekmurze** [comment]
I'm going to take the optimistic route here, and not add that file, so people always have the latest version of the dependencies of which I assume they'll work.

**Comment by maxacarvalho** [comment]
@freekmurze I saw that `composer.lock` file inside the `.gitignore` today.  
"Problem" here is, when I need to update the packages, `composer install` won't do.

For example, my Forge deploy recipe will run `composer install --no-interaction --prefer-dist --optimize-autoloader`, which will not bump the package's versions, I need a `composer update` for that.

What's your approach when you need to update the packages having the lock file ignored?

**Comment by freekmurze** [comment]
AFAIK, when no lock file is present, `composer install` should install the current versions of the dependencies and not the lower ones.

**Comment by maxacarvalho** [comment]
Hi @freekmurze 

Once I saw that the lock file was in the `.gitignore` and found this issue, I simply tried to hit the deploy button on Forge.  
After that I ran `composer outdated --direct` on my server and still got the list of outdated packages as well as the "**new updates available**" message inside the Mailcoach app. So that does not work apparently.  

Then I did a test, removed the lock from the `.gitignore` file, ran `composer update` and pushed my changes. This time the "new updates available" message was gone and the `composer outdated --direct` returned only major versions.

Here's a copy of my `composer.json`:

```json
{
    "name": "spatie/mailcoach",
    "type": "project",
    "keywords": [
        "mailcoach",
        "spatie"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://satis.mailcoach.app"
        }
    ],
    "require": {
        "php": "^7.4",
        "ext-json": "*",
        "aws/aws-sdk-php": "^3.121",
        "facade/ignition": "^2.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.5",
        "laravel/framework": "^7.0",
        "laravel/horizon": "^4.3",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "spatie/laravel-flash": "^1.5",
        "spatie/laravel-json-api-paginate": "^1.7",
        "spatie/laravel-mailcoach": "^2.10",
        "spatie/laravel-mailcoach-mailgun-feedback": "^2.0",
        "spatie/laravel-mailcoach-monaco": "^1.0",
        "spatie/laravel-mailcoach-postmark-feedback": "^2.0",
        "spatie/laravel-mailcoach-sendgrid-feedback": "^2.0",
        "spatie/laravel-mailcoach-ses-feedback": "^2.0",
        "spatie/laravel-mailcoach-unlayer": "^1.0",
        "spatie/laravel-query-builder": "^2.8",
        "spatie/laravel-welcome-notification": "^2.0",
        "spatie/valuestore": "^1.2",
        "wildbit/swiftmailer-postmark": "^3.1"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.6.7",
        "beyondcode/laravel-dump-server": "^1.3",
        "friendsofphp/php-cs-fixer": "^2.16",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^9.0",
        "spatie/laravel-tail": "^4.2"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "format": [
            "vendor/bin/php-cs-fixer fix"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag mailcoach-assets --force",
            "@php artisan vendor:publish --tag mailcoach-monaco-assets --force",
            "@php artisan horizon:publish"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "link-mailcoach-assets": [
            "rm -rf public/vendor/mailcoach",
            "ln -s $(pwd)/vendor/spatie/laravel-mailcoach/resources/dist public/vendor/mailcoach"
        ]
    }
}
```

**Comment by freekmurze** [comment]
I think the issue being raised here is that it easy to forget to remove `composer.lock` for `.gitignore` when installing the project. I'll add a command that gets executed on install to automate that.

**Comment by maxacarvalho** [comment]
Oh!!!!!! Now I got it.

You expect that whoever is installing the app, removes the lock from the ignore file after installing it.

No problem with that, I believe a note on the installation docs would be enough. I'd never thought of checking the ignore file 🤷‍♂️

Thanks @freekmurze!

**Comment by freekmurze** [comment]
Yeah, it's not that common that you have to do this, and I should have added it to the docs from day one.

Meanwhile, I've automated it so it shouldn't be a problem for future installs: https://github.com/spatie/Mailcoach/blob/4724f0c241c01c2048e05ef97b49fc7c717fae9c/composer.json#L98
