### ISSUE TITLE
Add possibility to use segments in segments

### ISSUE THREAD

**Issue by stefanbauer** [spatie/mailcoach-support#82]
It would be nice if I could use segments in segments 👍 Let me know if you need more details. But the use case should be clear.

**Comment by freekmurze** [comment]
Please add some examples here 👍

**Comment by stefanbauer** [comment]
Here is a common example from convertkit that uses a lot of people:

![image](https://user-images.githubusercontent.com/3192662/75043536-892b6d00-54c0-11ea-90ba-e06249e9f3f3.png)

**Comment by freekmurze** [comment]
I agree that it might be nice to have this option available in the UI.  I'll revisit this issue when creating the major version.

Meanwhile you can accomplish the behaviour you want using code. Take a look at instantiated Segment objects as mentioned on this page in the docs: https://mailcoach.app/docs/package/advanced-usage/segmenting-lists
