### ISSUE TITLE
Possibility to use lists and segments

### ISSUE THREAD

**Issue by stefanbauer** [spatie/mailcoach-support#83]
Would be really nice feature (but I think it's not that easy) to use a different list in a segment. Something like this:

If you have 2 Lists

- Customers
- Pre-Launch Email Collector

Then a segment in the Pre-Launch Email Collector would be `People that are interested but not signed up` ends in

- Not in list Customers

**Comment by freekmurze** [comment]
This suggestion goes against the base idea that every list is a separate entities that shouldn't know anything about another list. Segmention should be done using tags, not lists.

There's actually also so code in place that prevents you from sending mails to subscribers that not belong to the list coupled to the campaign.

**Comment by stefanbauer** [comment]
Then I don't get the idea of lists, based on your licensing model. Can you give me an example of different lists, that make sense? In your screenshots at the documentation, there are lists like `flareapp`, `freek.dev` and some more. This isn't a real example, because that will - based on your license model - never ever work. So I'm curious about some real life examples for different lists (within on project).
