### ISSUE TITLE
Scheduler Issue

### ISSUE THREAD

**Issue by prolonginc** [spatie/mailcoach-support#84]
in the kernel.php of the self-hosted version the command shows:
 `$schedule->command('email-campaigns:send-scheduled-campaigns')->everyMinute();`
while I believe it should be:
`$schedule->command('mailcoach:send-scheduled-campaigns')->everyMinute();`
unfortunately I cannot PR it since its not OSS. 

Thank you.

**Comment by freekmurze** [comment]
Change that command manually in your copy of mailcoach. Meanwhile I've corrected it in the master version. Thanks for bringing this to my attention.
