### ISSUE TITLE
Standalone installation + main application 

### ISSUE THREAD

**Issue by T-Spoon** [spatie/mailcoach-support#9]
Hey!

Looking forward to trying out Mailcoach - but I have a question around the standalone setup.

**Scenario:** I have a primary Laravel app, and I'd like to install Mailcoach as a standalone app on a different server.  But I'd like to sync the user list from the primary application to the Mailcoach app.  Is this possible?

I could of course install Mailcoach as a dependency inside the primary application - but I want to avoid "polluting" the main app with a ton of mailing stuff (extra DB tables, events, redis, etc) if possible.

Essentially I'd like to treat Mailcoach similarly to Mailchimp - where I can just call API's to subscribe users to mailing lists.  Is there any such API?

**Comment by vesper8** [comment]
Couple of ways you can do this if you don't want to install the standalone app on the same server as your main app.

You could do it all manually by opening up your mysql port to a whitelisted ip and setting up your remote connection in the database.php, then you could perform the sync. This is a bit tricky to accomplish I find but totally doable.

I personally do something very similar using a combination of https://github.com/stechstudio/laravel-ssh-tunnel and https://github.com/socialblue/laravel-database-synchronizer

Took me about an hour to set up and it works very well. Then you can perform a sync between tables on two different servers using whatever eloquent conditions you want.

Or you could also expose a secure api endpoint on either side and do the sync that way if you don't have a very large amount of users.

Either way this is totally out of scope of this package to perform a cross-server db sync.

However I do think it would be a very nice addition to add several api endpoints to Mailcoach to allow for basically all features to be managed via api. Hope this can be considered a new feature by @freekmurze

**Comment by freekmurze** [comment]
Some people have asked for an API so I'll certainly consider adding it in the future.

If you need an API now, I'd install the mailcoach inside a new Laravel app and host that app on a separate server.

In your new app you can add an API yourself. Working with the Mailcoach models and functionality should be pretty straightforward. Take a look at our package docs for code examples: https://mailcoach.app/docs/package/general/welcome

**Comment by desaintflorent** [comment]
I'm wondering @freekmurze what is your preference on this Standalone vs Main debate  ? 
How which criteria  would you choose one or the other ?

If i have an already working app with lot's of databases would you separate services with Mailcoach on a standalone server, or would you prefer have everything on one main server ?
On top of newsletter, I'm also planning on sending emails based on user activity from the main app.

**Comment by freekmurze** [comment]
Of course, it depends on your project, but generally I prefer to install mailcoach as a package inside the app that already has users management.

**Comment by Hesesses** [comment]
I would love to use mailcoach as separate "micro service" with API access. 

Our main app would create lists and subscribers etc using API.

I would also like to give our marketing team access to login mailcoach, create newsletter content with simple editor / drag & drop tools, choose lists and send.

**Comment by vesper8** [comment]
@Hesesses I believe you achieve the first part with https://github.com/leeovery/mailcoach-api

**Comment by Hesesses** [comment]
Thanks @vesper8. 
Just wanted to say that the standalone install with user management etc would be a killer feature
