### ISSUE TITLE
Update SNS Destination Screenshot

### ISSUE THREAD

**Issue by goaround** [spatie/mailcoach-support#91]
I followed the documentation for the Amazon SES setup but selected only Reject, Bounce, Complaint als Event types as visible in the screenshot: https://mailcoach.app/images/docs/app/mail-configuration/amazon-ses-sns-destination.png

Would be nice if you could update the screenshot or make it more clear that you have to select Click & Open, too if you would like to use the tracking.

**Comment by freekmurze** [comment]
Thanks for bringing this to our attention. I've updated the screenshot.
