### ISSUE TITLE
Laravel Horizon requires an update

### ISSUE THREAD

**Issue by LorenzoSapora** [spatie/mailcoach-support#92]
Laravel upgrade docs require `laravel/horizon` to be version `^4.0`.

Simple change:

composer.json:

```json
-"laravel/horizon": "^3.4",
+"laravel/horizon": "^4.0",
```

**Comment by freekmurze** [comment]
We're currently working on adding Laravel 7 support (see #94). We'll be sure to use Laravel Horizon v4 there.
