### ISSUE TITLE
Could not find a matching version of package spatie/laravel-mailcoach.

### ISSUE THREAD

**Issue by chimalsky** [spatie/mailcoach-support#93]
This package is awesome! I love all of Spatie's work and am so empowered by your guys' frilless expertise. 

When I attempt to install the mailcoach app then I have no trouble. However, whenever I attempt to require it as a package via composer, I have trouble. 

On my desktop, I followed the instructions in the documentation -- adding auth.json to same directory of composer binary -- and I continued to get the error message I've included below. When I returned to my desktop several days later composer was magically able to require the mailcoach package. 

Now I'm trying to require Mailcoach the package via composer on my macbook and am having the same issue. The command that I am running is
`composer require "spatie/laravel-mailcoach:^1.0.0"`

Here is the complete error message:
```

[InvalidArgumentException]
  Could not find a matching version of package spatie/laravel-mailcoach. Chec
  k the package spelling, your version constraint and that the package is ava
  ilable in a stability which matches your minimum-stability (dev).
```

**Comment by freekmurze** [comment]
> This package is awesome! I love all of Spatie's work and am so empowered by your guys' frilless expertise.

Thanks for your kind words

What is the output of `php -v` on your CLI? Could you try adding an `auth.json` in the directory of your project?

**Comment by chimalsky** [comment]
My PHP CLI version is 7.4.3 
```
PHP 7.4.3 (cli) (built: Feb 20 2020 12:23:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

And if I` phpinfo()`from within my app I also get that same version. 

Unfortunately I receive the same error message as above, even when I copy `auth.json` into my project directory.

I've tried  `composer require "spatie/laravel-mailcoach:^1.0.0"` both with laravel 7 and 6.18 just to see if it might work with either version but no luck.

It's strange because I can install the Mailcoach App but not the package. Have you heard of anyone else in this situation?

In case it might be helpful my composer version is 1.9.3

**Comment by freekmurze** [comment]
We didn't get any other reports on this except you. Try running `composer update -vvv`. It might contain a hint why composer can't pull in laravel-mailcoach.

**Comment by freekmurze** [comment]
Did you get it to work?

**Comment by freekmurze** [comment]
Closing now, let know if you still need any help with this.

**Comment by chimalsky** [comment]
Sorry, I haven't tried since then. I'm not in a rush right now with this so no worries on closing it for now. I'll report back when I do try.

**Comment by TwilightDuck** [comment]
Hi,

I ran into the same issue and I figured it out. 
You need to add the repositories key in your composer.json ABOVE the require key.
