### ISSUE TITLE
Add support for Laravel 7

### ISSUE THREAD

**Issue by freekmurze** [spatie/mailcoach-support#94]
We're currently working on adding Laravel 7 support. It takes some time because our UI heavily relied on BladeX and we're converting those views to native Blade Components. We're also adding support for multiple mail configurations

ETA: end of this week, early next week.

**Comment by vesper8** [comment]
@freekmurze Will you continue to update the Laravel 6 branch once you push these updates or will we all be forced to upgrade to Laravel 7 in order to receive support past the 1.8.0 version?

**Comment by freekmurze** [comment]
We will probably still push bug fixes for the current v1 version for some time.

We highly recommend upgrading to v2 though when it comes out.

**Comment by freekmurze** [comment]
v2 has been released.
