### ISSUE TITLE
Extend "First 24h performance graph" for email tracking

### ISSUE THREAD

**Issue by connecteev** [spatie/mailcoach-support#96]
Hi @freekmurze - I see that one of the features of Mailcoach is to track opens, clicks etc and have a "First 24h performance graph". Is there a reason why this is limited to 24h? 
For example, depending on the type of industry / domain, not all your subscribers will be checking their email daily. It would be great if we could extend the tracking horizon (why not make it infinite?)

Thanks for your work on mailcoach.

**Comment by freekmurze** [comment]
Thanks for your suggestion.

We have to strike a balance with providing good defaults and allowing configuration options. We decided to only have a 24h graph because that would be ok for most. We'll consider adding a config option for this in the future.

**Comment by freekmurze** [comment]
Closing now, but will revisit later.

**Comment by connecteev** [comment]
@freekmurze sounds good, thank you for the future consideration.

**Comment by connecteev** [comment]
Hi @freekmurze can we bump this up to extend the period for the performance graph? thanks...
