### ISSUE TITLE
[Enhancement Suggestion] Append UTM query string and double opt in bypass

### ISSUE THREAD

**Issue by david-nguyen** [spatie/mailcoach-support#98]
Firstly thanks for making this package. I've been using Sendy for a while now but wanted something better integrated with my Laravel app. I had two suggestions I think would be very helpful.

- textbox for a utm query string - this would basically append a utm query string to all links in the email for tracking purposes, really helpful to see how well an email does for e-commerce businesses
- a server-side way to subscribe, for example, I have a list that requires double opt-in - but another flow that requests if someone would like to subscribe to the list at checkout. Currently can't think of a way to subscribe someone without the double opt-in unless I use a second list.

Thanks for hearing me out!

**Comment by freekmurze** [comment]
Thanks for your suggestions.

- UTM query: You could achieve this by overriding the `PrepareEmailHtmlAction` (take a look at the config file, it's listed there), and in that action search for any links in the HTML and append the value you want. I'll consider adding this to the UI in the future.

- You can by pass double opt-in when you require Mailcoach as a package: https://mailcoach.app/docs/v2/package/working-with-lists/subscribing-to-a-list#skipping-opt-in-when-subscribing

Closing this issue, but if you have questions on this, let me know!
