### ISSUE TITLE
Cant send emails using sendgrid

### ISSUE THREAD

**Issue by fwartner** [spatie/mailcoach-support#99]
<img width="1792" alt="Bildschirmfoto 2020-03-12 um 09 11 35" src="https://user-images.githubusercontent.com/6692500/76501031-da84a780-6441-11ea-84bf-042ff7299788.png">

Getting this error even if everything is properly configured..

**Comment by freekmurze** [comment]
Could add this line

```
$config->set('mail.mailers.mailcoach.port', 587);
```

to the `registerConfigValues` function of `App\Support\MailConfiguration\Drivers\SendgridConfigurationDriver`

and try again?

**Comment by fwartner** [comment]
Worked! Thank you!

**Comment by fwartner** [comment]
Now i have the same issue on Transactional..

**Comment by fwartner** [comment]
`$config->set('mail.mailers.mailcoach-transactional.port', 587);` was fixing the issue.

**Comment by freekmurze** [comment]
My apologies for the hassle, and thanks for reporting this problem.

**Comment by fwartner** [comment]
No problem :)
